base_url = "https://192.168.10.30"
work_dir = "./downloads"

[[dns_zones]]
zone = "homelab.moyer.wtf"
ip_address = "192.168.10.27"
username = "root"
internal_alias_zones = []

[[dns_zones]]
zone = "hivemind.moyer.wtf"
ip_address = "192.168.1.4"
username = "root"
internal_alias_zones = ["dmz.moyer.wtf", "dmz.thomasmoyer.org"]

[[dns_zones]]
zone = "dmz.moyer.wtf"
ip_address = "192.168.20.2"
username = "root"
internal_alias_zones = []