# Global Configuration
# inventory = "System Inventory - Nodes.csv"
inventory = "https://docs.google.com/spreadsheets/d/13_PKWWAwS4JkLwrF78o3XiEfk9QGEI5Xbe2Mfte6mEI/edit?gid=1887097199#gid=1887097199"
caddy_ip = "192.168.20.3" # Uncomment and set if needed
caddyfile="../proxy/Caddyfile"
ssh_user = "root"
ssh_port = 22

# Global Router Configuration (Mikrotik)
# Applies to all VLANs unless overridden in [servers.vlan]
router_host = "192.168.1.1" # Replace with your Mikrotik IP
router_user = "admin"
router_port = 22

user_vlan = "hivemind"

# DNS Server Mappings
# Format: [servers.<vlan_name>]
# host = "ip_or_fqdn"
# type = "pihole" or "mikrotik"
# user = "username" (optional, overrides global ssh_user)
# port = 22 (optional, overrides global ssh_port)
# include_access_fqdn = true/false (optional, defaults to false)
# use_sudo = true/false (optional, defaults to false)

[servers.hivemind]
host = "pihole.hivemind.moyer.wtf"
type = "pihole"
user = "tom-tom"
include_access_fqdn = true
use_sudo = true

[servers.dmz]
host = "pihole.dmz.moyer.wtf"
type = "pihole"
user = "root"

[servers.homelab]
host = "pihole.homelab.moyer.wtf"
type = "pihole"
user = "root"

[servers.shady]
host = "192.168.1.1"
type = "mikrotik"
user = "admin"
