// distinct from the Python script, this lives in your dnscontrol directory
var REG_NONE = NewRegistrar("none");
var DSP_CF = NewDnsProvider("cloudflare");

// Load the JSON data generated by Python
var externalData = require("./external_records.json");

var records = [];
var domainName = "moyer.wtf";

for (var i = 0; i < externalData.length; i++) {
    var rec = externalData[i];
    var subdomain = "@";
    
    // Strip domain from FQDN to get subdomain
    if (rec.name === domainName) {
        subdomain = "@";
    } else if (rec.name.endsWith("." + domainName)) {
        subdomain = rec.name.slice(0, -(domainName.length + 1));
    } else {
        // Skip records that don't match the domain
        console.log("Skipping record not in " + domainName + ": " + rec.name);
        continue;
    }

    var proxyMod = rec.proxied ? CF_PROXY_ON : CF_PROXY_OFF;

    // Add A record
    records.push(A(subdomain, rec.target, proxyMod));
}

D(domainName, REG_NONE, DnsProvider(DSP_CF),
    records
);