// distinct from the Python script, this lives in your dnscontrol directory
var REG_NONE = NewRegistrar("none");
var DSP_CF = NewDnsProvider("cloudflare");

// Load the JSON data generated by Python
var externalData = require("./external_records.json");

// Derive root domain from FQDN (works for standard TLDs like example.com/org/wtf)
function getDomain(fqdn, fallback) {
    if (!fqdn) return fallback;
    var parts = fqdn.split(".");
    if (parts.length < 2) return fallback;
    return parts.slice(-2).join(".");
}

var defaultDomain = "moyer.wtf";
var groupedRecords = {};

for (var i = 0; i < externalData.length; i++) {
    var rec = externalData[i];
    var domain = rec.domain || getDomain(rec.name, defaultDomain);
    var subdomain = "@";

    // Strip domain from FQDN to get subdomain
    if (rec.name === domain) {
        subdomain = "@";
    } else if (rec.name.endsWith("." + domain)) {
        subdomain = rec.name.slice(0, -(domain.length + 1));
    } else {
        // Skip records that don't match the derived domain
        console.log("Skipping record not in " + domain + ": " + rec.name);
        continue;
    }

    var proxyMod = rec.proxied ? CF_PROXY_ON : CF_PROXY_OFF;

    if (!groupedRecords[domain]) {
        groupedRecords[domain] = [];
    }

    // Add A record
    groupedRecords[domain].push(A(subdomain, rec.target, proxyMod));
}

for (var domain in groupedRecords) {
    var recs = groupedRecords[domain];
    D(domain, REG_NONE, DnsProvider(DSP_CF),
        recs
    );
}
