from __future__ import annotations

import argparse
import curses
import datetime as _dt
import ipaddress
import logging
import os
import re
import secrets
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, TypeVar

import pandas as pd

from .config import (
    DEFAULT_SHEET_URL,
    get_config_value,
    get_table,
    load_toml_or_exit,
    pre_parse_config,
    resolve_path_relative_to_config,
)
from .logging_utils import configure_logging
from .mikrotik_utils import mikrotik_quote, sanitize_filename_component
from .sheets import (
    as_str,
    configure_sheet_csv_retention,
    normalize_column_name,
    normalize_ip,
)

logger = logging.getLogger(__name__)

_T = TypeVar("_T")

COMMENT_MARKER = "generated by python -m homelab mikrotik"
ADDRESS_LIST_CADDY_HOSTS = "hlb-caddy-hosts"
ADDRESS_LIST_BACKEND_PREFIX = "hlb-backend"
ADDRESS_LIST_HAIRPIN_SOURCES = "hairpin-sources"
ADDRESS_LIST_HAIRPIN_PREFIX = "hlb-hairpin"
DHCP_MAC_PREFIX = "BC:24:11"
ALLOWED_EXPOSURES = {"public", "private", "local"}


def _backend_group_list_name(protocol: str | None, backend_port: int) -> str:
    protocol_part = protocol.strip().lower() if protocol else "any"
    return f"{ADDRESS_LIST_BACKEND_PREFIX}-{protocol_part}-{backend_port}"


def _hairpin_target_list_name(*, protocol: str, port: int) -> str:
    protocol_part = protocol.strip().lower() or "any"
    return f"{ADDRESS_LIST_HAIRPIN_PREFIX}-{protocol_part}-{port}"


def _generate_random_mac(prefix: str = DHCP_MAC_PREFIX) -> str:
    prefix_upper = prefix.strip().upper()
    random_hex = secrets.token_hex(3).upper()
    suffix = ":".join(random_hex[i:i + 2] for i in range(0, 6, 2))
    return f"{prefix_upper}:{suffix}"


def _load_sheet_df(
    *,
    sheet_url: str,
    gid: int,
    timeout_seconds: float,
    label: str,
) -> pd.DataFrame:
    # Use the singleton cache from sheets.py
    from .sheets import get_sheet_df
    return get_sheet_df(sheet_url, gid, timeout_seconds, label)


def _has_interactive_tty() -> bool:
    term = os.environ.get("TERM", "").strip().lower()
    return sys.stdin.isatty() and sys.stdout.isatty() and term not in {"", "dumb"}


@dataclass
class ServiceFormData:
    service_key: str = ""
    service_name: str = ""
    frontend_hostname: str = ""
    hostname: str = ""
    protocol: str = ""
    ingress: str = "dstnat"
    exposure: str = "public"
    frontend_ports: str = ""
    backend_ports: str = ""
    backend_ip: str = ""
    source_ip: str = ""
    source_address_list: str = ""
    source_vlan: str = ""
    destination_vlan: str = ""
    destination_address_list: str = ""
    enable_nat: str = "yes"
    enable_filter: str = "yes"
    enable_dhcp: str = "no"
    dhcp_mac: str = ""
    dhcp_address: str = ""
    dhcp_subnet: str = ""
    dhcp_vlan_id: str = ""
    extra_ports: str = ""


@dataclass
class ParsedInput:
    service_key: str
    service_name: str
    frontend_hostname: str
    hostname: str
    ingress: str
    exposure: str
    protocol: str | None
    frontend_ports: list[int]
    backend_ports: list[int]
    extra_ports: list[int]
    backend_ip: str | None
    caddy_ip: str | None
    source_ip: str | None
    source_address_list: str | None
    in_interface: str | None
    in_interface_list: str | None
    out_interface: str | None
    dst_address_list: str | None
    enable_nat: bool
    enable_filter: bool
    enable_dhcp: bool
    use_input_chain: bool
    place_before_filter_comment: str | None
    place_before_input_comment: str | None
    dhcp_mac: str | None
    dhcp_address: str | None
    dhcp_subnet: str | None
    dhcp_server: str | None


@dataclass(frozen=True)
class PublicNatCandidate:
    service_key: str
    service_name: str
    ingress: str
    protocol: str
    external_port: int
    dst_ip: str
    dst_port: int
    wan_ip: str
    frontend_hostname: str
    service_order: int


@dataclass
class ValidationIssue:
    severity: str
    message: str
    service_key: str | None = None


@dataclass
class PublicPipelineResult:
    direct_candidates_by_service: dict[str, list[PublicNatCandidate]] = field(default_factory=dict)
    caddy_candidates: list[PublicNatCandidate] = field(default_factory=list)
    issues: list[ValidationIssue] = field(default_factory=list)


@dataclass(frozen=True)
class HairpinSourceEntry:
    subnet: str
    comment: str


@dataclass(frozen=True)
class HairpinTargetEntry:
    list_name: str
    address: str
    comment: str


def _normalize_vlan_id(value: str | None) -> str | None:
    raw = (value or "").strip().lower()
    if not raw:
        return None
    match = re.search(r"(\d+)", raw)
    if not match:
        return None
    return str(int(match.group(1)))


def _dhcp_server_from_vlan_id(value: str | None) -> str | None:
    vlan_id = _normalize_vlan_id(value)
    if vlan_id is None:
        return None
    return f"dhcp-v{vlan_id}"


def _to_bool(value: str) -> bool:
    return value.strip().lower() in {"1", "y", "yes", "true", "on"}


def _dedupe_preserve_order(values: list[_T]) -> list[_T]:
    deduped: list[_T] = []
    seen: set[_T] = set()
    for value in values:
        if value in seen:
            continue
        seen.add(value)
        deduped.append(value)
    return deduped


def _parse_string_list(value: Any) -> list[str]:
    if isinstance(value, list):
        raw_values = [str(item).strip() for item in value]
    elif isinstance(value, str):
        raw_values = [part.strip() for part in re.split(r"[,;\n]+", value)]
    else:
        raw_values = []
    return [item for item in _dedupe_preserve_order(raw_values) if item]


def _parse_wan_ip_list(config: dict[str, Any]) -> tuple[list[str], list[str]]:
    fw_cfg = get_table(config, "mikrotik") or get_table(config, "firewall")
    valid: list[str] = []
    invalid: list[str] = []
    for raw in _parse_string_list(get_config_value(fw_cfg, "wan_ips", [])):
        normalized = normalize_ip(raw)
        if normalized:
            valid.append(normalized)
        else:
            invalid.append(raw)
    return _dedupe_preserve_order(valid), _dedupe_preserve_order(invalid)


def _normalize_network_cidr(value: Any) -> str | None:
    raw = as_str(value)
    if not raw:
        return None
    try:
        network = ipaddress.ip_network(raw, strict=False)
    except ValueError:
        return None
    return str(network)


def _hairpin_zone_comment(row: Any) -> str:
    explicit = as_str(row.get("address_list"))
    if explicit:
        return explicit

    vlan_name = as_str(row.get("vlan_name"))
    if vlan_name:
        normalized = vlan_name.strip().lower().replace(" ", "-")
        if normalized.endswith("-lan"):
            return normalized
        return f"{normalized}-lan"

    zone_name = as_str(row.get("zone_name")) or as_str(row.get("dns_zone"))
    if zone_name:
        return zone_name.strip().lower().replace(" ", "-")

    return "hairpin-source"


def _load_hairpin_sources_from_zones_sheet(
    *,
    sheet_url: str,
    zones_gid: int,
    timeout_seconds: float,
) -> tuple[list[HairpinSourceEntry], list[ValidationIssue]]:
    if zones_gid < 0:
        return [], []

    df = _load_sheet_df(
        sheet_url=sheet_url,
        gid=int(zones_gid),
        timeout_seconds=timeout_seconds,
        label="Zones",
    )

    entries: list[HairpinSourceEntry] = []
    issues: list[ValidationIssue] = []
    seen: set[tuple[str, str]] = set()

    for row_number, (_, row) in enumerate(df.iterrows(), start=2):
        if not _to_bool(as_str(row.get("hairpin_allowed")) or ""):
            continue

        subnet = _normalize_network_cidr(row.get("network"))
        if not subnet:
            issues.append(
                ValidationIssue(
                    severity="warning",
                    message=(
                        f"Zones row {row_number} is hairpin_allowed but is missing a valid Network value"
                    ),
                )
            )
            continue

        comment = _hairpin_zone_comment(row)
        key = (subnet, comment)
        if key in seen:
            continue
        seen.add(key)
        entries.append(HairpinSourceEntry(subnet=subnet, comment=comment))

    return entries, _dedupe_validation_issues(issues)


def _parse_vlan_map(config: dict[str, Any]) -> dict[str, dict[str, str]]:
    fw_cfg = get_table(config, "mikrotik") or get_table(config, "firewall")

    raw = fw_cfg.get("vlans", {})
    if not isinstance(raw, dict):
        return {}
    return {k.lower(): dict(v) for k, v in raw.items() if isinstance(v, dict)}


def _normalize_ports_lenient(value: Any) -> list[int]:
    if value is None:
        return []

    if isinstance(value, list):
        ports: list[int] = []
        for item in value:
            ports.extend(_normalize_ports_lenient(item))
        return ports

    if isinstance(value, (int, float)):
        try:
            parsed = int(float(value))
        except (TypeError, ValueError):
            return []
        return [parsed] if 1 <= parsed <= 65535 else []

    if isinstance(value, str):
        cleaned = value.strip()
        if not cleaned:
            return []
        parts = re.split(r"[\s,;/]+", cleaned)
        ports: list[int] = []
        for part in parts:
            token = part.strip()
            if not token:
                continue
            try:
                parsed = int(float(token))
            except ValueError:
                continue
            if 1 <= parsed <= 65535:
                ports.append(parsed)
        return ports

    return []


def _ports_to_form_value(value: Any) -> str:
    ports = _normalize_ports_lenient(value)
    return ",".join(str(port) for port in ports)


def _merged_ports_for_display(base_ports: Any, extra_ports: Any) -> str:
    merged: list[int] = []
    seen: set[int] = set()
    for port in [*_normalize_ports_lenient(base_ports), *_normalize_ports_lenient(extra_ports)]:
        if port in seen:
            continue
        seen.add(port)
        merged.append(port)
    return ",".join(str(port) for port in merged)


def _split_backend_ports_for_storage(*, merged_ports_value: str, frontend_ports_value: Any) -> tuple[str, str]:
    ports = _normalize_ports_lenient(merged_ports_value)
    if not ports:
        return "", ""

    frontend_ports = _normalize_ports_lenient(frontend_ports_value)

    if not frontend_ports:
        base_ports = ports
        extra_ports: list[int] = []
    elif len(ports) <= len(frontend_ports):
        base_ports = ports
        extra_ports = []
    else:
        base_count = len(frontend_ports)
        base_ports = ports[:base_count]
        extra_ports = ports[base_count:]

    return (
        ",".join(str(port) for port in base_ports),
        ",".join(str(port) for port in extra_ports),
    )


def _extract_extra_cname_ports(value: Any) -> list[int]:
    raw = as_str(value)
    if not raw:
        return []

    ports: list[int] = []
    for match in re.finditer(r":\s*(\d{1,5})(?=$|[\s,;/])", raw):
        try:
            parsed = int(match.group(1))
        except ValueError:
            continue
        if 1 <= parsed <= 65535:
            ports.append(parsed)

    deduped: list[int] = []
    seen: set[int] = set()
    for port in ports:
        if port in seen:
            continue
        seen.add(port)
        deduped.append(port)
    return deduped


def _load_helpers_values(
    *,
    sheet_url: str,
    helpers_gid: int,
    timeout_seconds: float,
) -> dict[str, list[str]]:
    df = _load_sheet_df(
        sheet_url=sheet_url,
        gid=int(helpers_gid),
        timeout_seconds=timeout_seconds,
        label="Helpers",
    )

    values_by_column: dict[str, list[str]] = {}
    for column in df.columns:
        seen: set[str] = set()
        values: list[str] = []
        for raw in df[column]:
            value = as_str(raw)
            if not value:
                continue
            key = value.casefold()
            if key in seen:
                continue
            seen.add(key)
            values.append(value)
        values_by_column[column] = values

    return values_by_column


def _build_selection_options(
    *,
    helpers_values: dict[str, list[str]],
    vlan_map: dict[str, dict[str, str]],
) -> dict[str, list[str]]:
    helper_protocols = [value.lower() for value in helpers_values.get("protocols", []) if value.strip()]
    if not helper_protocols:
        raise ValueError("Helpers tab is missing required values for the 'Protocols' column.")

    helper_address_lists = [value for value in helpers_values.get("address_lists", []) if value.strip()]
    vlan_options = sorted(vlan_map.keys(), key=str.casefold)

    return {
        "protocol": ["", *helper_protocols],
        "ingress": ["dstnat", "direct", "caddy"],
        "exposure": ["public", "private", "local"],
        "source_vlan": ["", *vlan_options],
        "destination_vlan": ["", *vlan_options],
        "source_address_list": ["", *helper_address_lists],
        "destination_address_list": ["", *helper_address_lists],
        "enable_nat": ["yes", "no"],
        "enable_filter": ["yes", "no"],
        "enable_dhcp": ["yes", "no"],
    }


def _normalized_service_filename(service_name: str) -> str:
    raw = service_name.strip().lower()
    if not raw:
        return "service"
    normalized = re.sub(r"[^a-z0-9._-]+", "-", raw)
    normalized = normalized.strip("-_.")
    safe = sanitize_filename_component(normalized)
    return safe or "service"


def _prefill_from_services_sheet(
    *,
    sheet_url: str,
    services_gid: int,
    timeout_seconds: float,
    service_key: str,
) -> dict[str, str | Any]:
    matches = _prefill_candidates_from_services_sheet(
        sheet_url=sheet_url,
        services_gid=services_gid,
        timeout_seconds=timeout_seconds,
        service_key=service_key,
    )
    return matches[0] if matches else {}


def _prefill_candidates_from_services_sheet(
    *,
    sheet_url: str,
    services_gid: int,
    timeout_seconds: float,
    service_key: str,
) -> list[dict[str, str | Any]]:
    service_key = service_key.strip().lower()
    if not service_key:
        return []

    df = _load_sheet_df(
        sheet_url=sheet_url,
        gid=int(services_gid),
        timeout_seconds=timeout_seconds,
        label="Services",
    )

    matches: list[dict[str, str | Any]] = []
    for _, row in df.iterrows():
        candidates = [
            as_str(row.get("service_name")),
            as_str(row.get("frontend_hostname")),
            as_str(row.get("hostname")),
        ]
        if service_key not in {c.lower() for c in candidates if c}:
            continue

        matches.append(
            {
                "service_name": as_str(row.get("service_name")),
                "frontend_hostname": as_str(row.get("frontend_hostname")),
                "hostname": as_str(row.get("hostname")),
                "protocol": as_str(row.get("protocol")).lower(),
                "ingress": as_str(row.get("ingress")).lower() or "dstnat",
                "exposure": as_str(row.get("exposure")).lower() or "public",
                "frontend_ports": _ports_to_form_value(row.get("frontend_port")),
                "backend_ports": _ports_to_form_value(row.get("backend_port")),
                "backend_ip": as_str(row.get("ip_address")),
                "source_ip": as_str(row.get("source_ip")),
                "source_address_list": as_str(row.get("source_address_list")),
                "source_vlan": as_str(row.get("source_vlan")) or as_str(row.get("source_vlans")),
                "destination_vlan": as_str(row.get("destination_vlan")),
                "destination_address_list": as_str(row.get("destination_address_list")),
                "extra_ports": ",".join(
                    str(port) for port in _extract_extra_cname_ports(row.get("extra_cnames"))
                ),
            }
        )

    return matches


def _prompt_select_service_by_name(
    *,
    service_key: str,
    matches: list[dict[str, str | Any]],
) -> dict[str, str | Any]:
    if not matches:
        return {}
    if len(matches) == 1:
        return matches[0]

    print(
        f"Multiple Services rows found for frontend hostname '{service_key}'.",
        file=sys.stderr,
    )
    print("Select the desired Service Name:", file=sys.stderr)

    for idx, match in enumerate(matches, start=1):
        service_name = str(match.get("service_name") or "").strip() or "(empty Service Name)"
        print(f"  [{idx}] {service_name}", file=sys.stderr)

    while True:
        print(f"Enter choice [1-{len(matches)}]: ", end="", file=sys.stderr, flush=True)
        choice = input().strip()
        if choice.isdigit():
            selected = int(choice)
            if 1 <= selected <= len(matches):
                return matches[selected - 1]
        print("Invalid choice. Try again.", file=sys.stderr)


def _list_services_from_sheet(*, sheet_url: str, services_gid: int, timeout_seconds: float) -> list[str]:
    df = _load_sheet_df(
        sheet_url=sheet_url,
        gid=int(services_gid),
        timeout_seconds=timeout_seconds,
        label="Services",
    )

    seen: set[str] = set()
    services: list[str] = []

    for _, row in df.iterrows():
        candidates = [
            as_str(row.get("service_name")),
            as_str(row.get("frontend_hostname")),
            as_str(row.get("hostname")),
        ]
        chosen = ""
        for candidate in candidates:
            if candidate:
                chosen = candidate
                break
        if not chosen:
            continue

        key = chosen.lower()
        if key in seen:
            continue
        seen.add(key)
        services.append(chosen)

    return sorted(services, key=str.casefold)


def _prefill_from_nodes_sheet(
    *,
    sheet_url: str,
    nodes_gid: int,
    timeout_seconds: float,
    hostname: str,
    lease_type_column: str,
    ip_column: str,
    subnet_column: str,
    mac_column: str,
    vlan_id_column: str,
) -> dict[str, str]:
    target = hostname.strip().lower()
    if not target:
        return {}

    df = _load_sheet_df(
        sheet_url=sheet_url,
        gid=int(nodes_gid),
        timeout_seconds=timeout_seconds,
        label="Nodes",
    )
    for _, row in df.iterrows():
        node_name = as_str(row.get("hostname")).lower()
        dns_name = as_str(row.get("dns_name")).lower()
        if target not in {node_name, dns_name}:
            continue

        lease_type = as_str(row.get(lease_type_column)).strip().lower()
        enable_dhcp = "yes" if lease_type == "dhcp" else "no"

        return {
            "backend_ip": as_str(row.get(ip_column)),
            "dhcp_mac": as_str(row.get(mac_column)),
            "dhcp_address": as_str(row.get(ip_column)),
            "dhcp_subnet": as_str(row.get(subnet_column)),
            "dhcp_vlan_id": as_str(row.get(vlan_id_column)),
            "enable_dhcp": enable_dhcp,
        }

    return {}


def _resolve_hostname_ip_from_nodes(
    *,
    sheet_url: str,
    nodes_gid: int,
    timeout_seconds: float,
    hostname: str,
    ip_column: str,
) -> str | None:
    """Look up a hostname in the Nodes sheet and return its IP address.

    Matches against both the ``hostname`` and ``dns_name`` columns
    (case-insensitive exact match).  Returns ``None`` when not found.
    """
    target = hostname.strip().lower()
    if not target:
        return None

    df = _load_sheet_df(
        sheet_url=sheet_url,
        gid=int(nodes_gid),
        timeout_seconds=timeout_seconds,
        label="Nodes",
    )
    for _, row in df.iterrows():
        node_name = as_str(row.get("hostname")).lower()
        dns_name = as_str(row.get("dns_name")).lower()
        if target not in {node_name, dns_name}:
            continue
        ip = normalize_ip(as_str(row.get(ip_column)))
        if ip:
            return ip
    return None


def _list_node_hostnames_from_nodes_sheet(
    *,
    sheet_url: str,
    nodes_gid: int,
    timeout_seconds: float,
) -> list[str]:
    df = _load_sheet_df(
        sheet_url=sheet_url,
        gid=int(nodes_gid),
        timeout_seconds=timeout_seconds,
        label="Nodes",
    )

    seen: set[str] = set()
    options: list[str] = []
    for _, row in df.iterrows():
        hostname = as_str(row.get("hostname"))
        if not hostname:
            continue
        key = hostname.casefold()
        if key in seen:
            continue
        seen.add(key)
        options.append(hostname)

    return sorted(options, key=str.casefold)


def _run_single_input_prompt(initial_service_key: str) -> str:
    prompt = "Service key (service_name/frontend_hostname/hostname): "

    def _inner(stdscr: Any) -> str:
        curses.curs_set(1)
        stdscr.clear()
        stdscr.addstr(0, 0, "MikroTik single-service generator")
        stdscr.addstr(2, 0, prompt)
        stdscr.addstr(3, 0, "Type service key and press Enter")
        stdscr.refresh()

        buf = list(initial_service_key)
        stdscr.addstr(2, len(prompt), "".join(buf))
        pos = len(buf)
        while True:
            ch = stdscr.getch()
            if ch in {10, 13}:
                return "".join(buf).strip()
            if ch in {curses.KEY_BACKSPACE, 127, 8}:
                if pos > 0:
                    pos -= 1
                    del buf[pos]
            elif 32 <= ch <= 126:
                buf.insert(pos, chr(ch))
                pos += 1
            stdscr.move(2, len(prompt))
            stdscr.clrtoeol()
            stdscr.addstr(2, len(prompt), "".join(buf))
            stdscr.refresh()

    return curses.wrapper(_inner)


def _run_service_selection_menu(*, services: list[str]) -> list[str]:
    options = [*services, "New..."]

    def _inner(stdscr: Any) -> list[str]:
        curses.curs_set(0)
        selected_idx = 0
        scroll = 0
        selected_indices: set[int] = set()

        while True:
            stdscr.clear()
            height, width = stdscr.getmaxyx()
            stdscr.addstr(0, 0, "MikroTik single-service generator")
            stdscr.addstr(1, 0, "Select one or more services from Services sheet")
            stdscr.addstr(2, 0, "Use ↑/↓ navigate, Space toggle, Enter confirm")

            visible_rows = max(1, height - 5)
            if selected_idx < scroll:
                scroll = selected_idx
            if selected_idx >= scroll + visible_rows:
                scroll = selected_idx - visible_rows + 1

            for row_idx in range(visible_rows):
                option_idx = scroll + row_idx
                if option_idx >= len(options):
                    break
                option = options[option_idx]
                cursor = ">" if option_idx == selected_idx else " "
                marker = "[x]" if option_idx in selected_indices else "[ ]"
                if option == "New...":
                    marker = "[+]"
                text = f"{cursor} {marker} {option}"
                stdscr.addstr(4 + row_idx, 0, text[: max(1, width - 1)])

            ch = stdscr.getch()
            if ch == curses.KEY_UP:
                selected_idx = (selected_idx - 1) % len(options)
                continue
            if ch == curses.KEY_DOWN:
                selected_idx = (selected_idx + 1) % len(options)
                continue
            if ch == ord(" "):
                if selected_idx < len(services):
                    if selected_idx in selected_indices:
                        selected_indices.remove(selected_idx)
                    else:
                        selected_indices.add(selected_idx)
                continue
            if ch in {10, 13}:
                if selected_indices:
                    return [services[i] for i in range(len(services)) if i in selected_indices]
                if selected_idx == len(options) - 1:
                    return ["New..."]
                return [options[selected_idx]]

    return curses.wrapper(_inner)


def _run_option_selection(
    stdscr: Any,
    *,
    title: str,
    options: list[str],
    current_value: str,
) -> str:
    if not options:
        return current_value

    choice_options = list(options)
    if current_value not in choice_options:
        choice_options.append(current_value)

    selected_idx = 0
    for i, item in enumerate(choice_options):
        if item == current_value:
            selected_idx = i
            break

    scroll = 0
    while True:
        stdscr.clear()
        height, width = stdscr.getmaxyx()
        stdscr.addstr(0, 0, f"Select value: {title}")
        stdscr.addstr(1, 0, "Use ↑/↓ to navigate, Enter to choose")

        visible_rows = max(1, height - 4)
        if selected_idx < scroll:
            scroll = selected_idx
        if selected_idx >= scroll + visible_rows:
            scroll = selected_idx - visible_rows + 1

        for row_idx in range(visible_rows):
            option_idx = scroll + row_idx
            if option_idx >= len(choice_options):
                break
            option = choice_options[option_idx]
            label = option if option else "(none)"
            prefix = ">" if option_idx == selected_idx else " "
            stdscr.addstr(3 + row_idx, 0, f"{prefix} {label}"[: max(1, width - 1)])

        ch = stdscr.getch()
        if ch == curses.KEY_UP:
            selected_idx = (selected_idx - 1) % len(choice_options)
            continue
        if ch == curses.KEY_DOWN:
            selected_idx = (selected_idx + 1) % len(choice_options)
            continue
        if ch in {10, 13}:
            return choice_options[selected_idx]


def _run_form_ui(
    form_data: ServiceFormData,
    title: str,
    selection_options: dict[str, list[str]],
) -> ServiceFormData:
    fields: list[tuple[str, str]] = [
        ("service_name", "Service name"),
        ("frontend_hostname", "Frontend hostname (public DNS)"),
        ("hostname", "Backend hostname (Nodes tab)"),
        ("protocol", "Protocol (tcp/udp)"),
        ("ingress", "Ingress (dstnat/direct/caddy)"),
        ("exposure", "Exposure (public/private/local)"),
        ("frontend_ports", "Frontend ports (csv)"),
        ("backend_ports", "Backend ports (csv)"),
        ("backend_ip", "Backend IP"),
        ("source_ip", "Source IP (optional)"),
        ("source_address_list", "Source address-list (optional)"),
        ("source_vlan", "Source VLAN (optional)"),
        ("destination_vlan", "Destination VLAN (optional)"),
        ("destination_address_list", "Destination address-list (optional)"),
        ("enable_nat", "Generate NAT? (yes/no)"),
        ("enable_filter", "Generate filter? (yes/no)"),
        ("enable_dhcp", "Generate DHCP lease? (yes/no)"),
        ("dhcp_mac", "DHCP MAC (if enabled)"),
        ("dhcp_address", "DHCP IP address (if enabled)"),
        ("dhcp_subnet", "DHCP subnet (optional)"),
        ("dhcp_vlan_id", "DHCP VLAN ID (if enabled)"),
    ]

    def _inner(stdscr: Any) -> ServiceFormData:
        curses.curs_set(0)
        idx = 0
        while True:
            stdscr.clear()
            stdscr.addstr(0, 0, title)
            stdscr.addstr(1, 0, "Use ↑/↓ to select, Enter to edit, F2 to continue")

            row = 3
            for i, (key, label) in enumerate(fields):
                value = getattr(form_data, key)
                if key == "backend_ports":
                    value = _merged_ports_for_display(form_data.backend_ports, form_data.extra_ports)
                prefix = ">" if i == idx else " "
                stdscr.addstr(row + i, 0, f"{prefix} {label}: {value}")

            ch = stdscr.getch()
            if ch == curses.KEY_UP:
                idx = (idx - 1) % len(fields)
                continue
            if ch == curses.KEY_DOWN:
                idx = (idx + 1) % len(fields)
                continue
            if ch == curses.KEY_F2:
                return form_data
            if ch in {10, 13}:
                key, label = fields[idx]
                current = str(getattr(form_data, key))
                if key == "backend_ports":
                    current = _merged_ports_for_display(form_data.backend_ports, form_data.extra_ports)
                options = selection_options.get(key)
                if options is not None:
                    selected = _run_option_selection(
                        stdscr,
                        title=label,
                        options=options,
                        current_value=current,
                    )
                    setattr(form_data, key, selected.strip())
                    continue

                curses.curs_set(1)
                stdscr.clear()
                stdscr.addstr(0, 0, f"Edit: {label}")
                stdscr.addstr(1, 0, "Enter value and press Enter")
                stdscr.addstr(3, 0, current)
                stdscr.refresh()
                buf = list(current)
                pos = len(buf)
                while True:
                    keypress = stdscr.getch()
                    if keypress in {10, 13}:
                        updated = "".join(buf).strip()
                        if key == "backend_ports":
                            stored_backend_ports, stored_extra_ports = _split_backend_ports_for_storage(
                                merged_ports_value=updated,
                                frontend_ports_value=form_data.frontend_ports,
                            )
                            form_data.backend_ports = stored_backend_ports
                            form_data.extra_ports = stored_extra_ports
                        else:
                            setattr(form_data, key, updated)
                        break
                    if keypress in {curses.KEY_BACKSPACE, 127, 8}:
                        if pos > 0:
                            pos -= 1
                            del buf[pos]
                    elif 32 <= keypress <= 126:
                        buf.insert(pos, chr(keypress))
                        pos += 1
                    stdscr.move(3, 0)
                    stdscr.clrtoeol()
                    stdscr.addstr(3, 0, "".join(buf))
                    stdscr.refresh()
                curses.curs_set(0)

    return curses.wrapper(_inner)


def _run_batch_confirmation_ui(forms: list[ServiceFormData]) -> bool:
    if not forms:
        return False

    def _inner(stdscr: Any) -> bool:
        curses.curs_set(0)
        scroll = 0

        while True:
            stdscr.clear()
            height, width = stdscr.getmaxyx()

            lines = [
                "Review selected services before generation",
                "Press y to generate all, n to cancel",
                "Use ↑/↓ to scroll",
                "",
            ]

            for idx, form in enumerate(forms, start=1):
                service_name = form.service_name.strip() or form.service_key.strip() or "service"
                backend_ports_display = _merged_ports_for_display(form.backend_ports, form.extra_ports)
                hairpin_status = "yes" if _form_will_generate_hairpin(form) else "no"
                summary = (
                    f"[{idx}] service={service_name} "
                    f"host={form.hostname.strip()} ingress={form.ingress.strip() or 'dstnat'} "
                    f"protocol={form.protocol.strip() or 'any'} "
                    f"frontend={form.frontend_ports.strip()} backend={backend_ports_display} "
                    f"hairpin={hairpin_status}"
                )
                lines.append(summary)

            visible_rows = max(1, height - 1)
            max_scroll = max(0, len(lines) - visible_rows)
            if scroll > max_scroll:
                scroll = max_scroll

            for row in range(visible_rows):
                line_idx = scroll + row
                if line_idx >= len(lines):
                    break
                stdscr.addstr(row, 0, lines[line_idx][: max(1, width - 1)])

            ch = stdscr.getch()
            if ch == curses.KEY_UP:
                scroll = max(0, scroll - 1)
                continue
            if ch == curses.KEY_DOWN:
                scroll = min(max_scroll, scroll + 1)
                continue
            if ch in {ord('y'), ord('Y')}:
                return True
            if ch in {ord('n'), ord('N')}:
                return False

    return curses.wrapper(_inner)


def _normalize_form(
    form_data: ServiceFormData,
    vlan_map: dict[str, dict[str, str]],
    *,
    caddy_ip: str,
    input_chain_hosts: list[str] | None = None,
    place_before_filter_comment: str | None = None,
    place_before_input_comment: str | None = None,
) -> ParsedInput:
    source_vlan = form_data.source_vlan.strip().lower()
    destination_vlan = form_data.destination_vlan.strip().lower()

    source_cfg = vlan_map.get(source_vlan, {}) if source_vlan else {}
    destination_cfg = vlan_map.get(destination_vlan, {}) if destination_vlan else {}

    protocol_raw = form_data.protocol.strip().lower()
    if not protocol_raw:
        protocol: str | None = None
    elif protocol_raw in {"tcp", "udp"}:
        protocol = protocol_raw
    else:
        protocol = "tcp"

    ingress = form_data.ingress.strip().lower()
    if ingress not in {"dstnat", "direct", "caddy"}:
        ingress = "dstnat"

    exposure = form_data.exposure.strip().lower().replace("_", "-")
    if exposure not in ALLOWED_EXPOSURES:
        raise ValueError(
            f"unsupported exposure {exposure!r}; use only public/private/local"
        )

    # Auto-disable NAT for non-public services — they should never be
    # reachable from WAN via dstnat.
    is_public = exposure == "public"
    enable_nat = _to_bool(form_data.enable_nat) and is_public

    # For caddy-ingress services, per-service dstnat is never needed;
    # the shared caddy-dstnat.rsc handles WAN:80/443 → Caddy IP.
    if ingress == "caddy":
        enable_nat = False

    backend_ip = normalize_ip(form_data.backend_ip)
    caddy_ip_normalized = normalize_ip(caddy_ip)

    # Determine whether the backend is the router itself (INPUT chain).
    hostname_lower = form_data.hostname.strip().lower()
    use_input_chain = bool(
        input_chain_hosts
        and hostname_lower
        and hostname_lower in {h.strip().lower() for h in input_chain_hosts}
    )

    return ParsedInput(
        service_key=form_data.service_key.strip(),
        service_name=form_data.service_name.strip() or form_data.service_key.strip() or "service",
        frontend_hostname=form_data.frontend_hostname.strip(),
        hostname=form_data.hostname.strip(),
        ingress=ingress,
        exposure=exposure,
        protocol=protocol,
        frontend_ports=_normalize_ports_lenient(form_data.frontend_ports),
        backend_ports=_normalize_ports_lenient(form_data.backend_ports),
        extra_ports=_normalize_ports_lenient(form_data.extra_ports),
        backend_ip=backend_ip,
        caddy_ip=caddy_ip_normalized,
        source_ip=normalize_ip(form_data.source_ip),
        source_address_list=form_data.source_address_list.strip() or None,
        in_interface=source_cfg.get("interface") or None,
        in_interface_list=source_cfg.get("interface_list") or None,
        out_interface=destination_cfg.get("interface") or None,
        dst_address_list=(
            form_data.destination_address_list.strip() or destination_cfg.get("address_list") or None
        ),
        enable_nat=enable_nat,
        enable_filter=_to_bool(form_data.enable_filter),
        enable_dhcp=_to_bool(form_data.enable_dhcp),
        use_input_chain=use_input_chain,
        place_before_filter_comment=place_before_filter_comment or None,
        place_before_input_comment=place_before_input_comment or None,
        dhcp_mac=form_data.dhcp_mac.strip() or None,
        dhcp_address=normalize_ip(form_data.dhcp_address),
        dhcp_subnet=form_data.dhcp_subnet.strip() or None,
        dhcp_server=_dhcp_server_from_vlan_id(form_data.dhcp_vlan_id),
    )


def _form_will_generate_hairpin(form_data: ServiceFormData) -> bool:
    exposure = form_data.exposure.strip().lower().replace("_", "-")
    ingress = form_data.ingress.strip().lower()
    protocol = form_data.protocol.strip().lower()
    frontend_hostname = form_data.frontend_hostname.strip()
    backend_ip = normalize_ip(form_data.backend_ip)
    backend_ports = _normalize_ports_lenient(form_data.backend_ports)
    frontend_ports = _normalize_ports_lenient(form_data.frontend_ports)

    if exposure != "public":
        return False
    if ingress not in {"caddy", "direct"}:
        return False
    if protocol not in {"tcp", "udp"}:
        return False
    if not frontend_hostname or not backend_ip or not backend_ports:
        return False
    if ingress == "caddy":
        return bool(frontend_ports)
    if ingress == "direct":
        return bool(frontend_ports or backend_ports)
    return False


def _port_mappings(frontend_ports: list[int], backend_ports: list[int]) -> list[tuple[int, int]]:
    if not frontend_ports:
        return []
    if not backend_ports:
        return [(p, p) for p in frontend_ports]
    if len(backend_ports) == 1:
        return [(p, backend_ports[0]) for p in frontend_ports]
    if len(backend_ports) == len(frontend_ports):
        return list(zip(frontend_ports, backend_ports))
    return []


def _should_generate_private_local_router_rules(parsed: ParsedInput) -> bool:
    return any(
        [
            parsed.use_input_chain,
            bool(parsed.source_ip),
            bool(parsed.source_address_list),
            bool(parsed.in_interface),
            bool(parsed.in_interface_list),
            bool(parsed.out_interface),
            bool(parsed.dst_address_list),
        ]
    )


def _should_generate_service_filter(parsed: ParsedInput) -> bool:
    if not parsed.enable_filter or not parsed.backend_ip:
        return False
    if parsed.exposure == "public":
        return True
    if parsed.ingress == "caddy":
        return True
    return _should_generate_private_local_router_rules(parsed)


def _service_port_mappings(parsed: ParsedInput) -> list[tuple[int, int]]:
    mappings = _port_mappings(parsed.frontend_ports, parsed.backend_ports)
    for port in parsed.extra_ports:
        pair = (int(port), int(port))
        if pair not in mappings:
            mappings.append(pair)
    return mappings


def _backend_ports_for_service(parsed: ParsedInput, mappings: list[tuple[int, int]] | None = None) -> set[int]:
    effective_mappings = mappings if mappings is not None else _service_port_mappings(parsed)

    backend_ports_for_lists: set[int] = set()
    for _, backend_port in effective_mappings:
        if backend_port > 0:
            backend_ports_for_lists.add(int(backend_port))
    for extra_port in parsed.extra_ports:
        if extra_port > 0:
            backend_ports_for_lists.add(int(extra_port))
    if not backend_ports_for_lists and parsed.backend_ports:
        for backend_port in parsed.backend_ports:
            if backend_port > 0:
                backend_ports_for_lists.add(int(backend_port))
    return backend_ports_for_lists


def _normalize_external_ports(parsed: ParsedInput) -> list[int]:
    if parsed.ingress == "caddy":
        return _dedupe_preserve_order(list(parsed.frontend_ports))
    if parsed.ingress == "direct":
        if parsed.frontend_ports:
            return _dedupe_preserve_order(list(parsed.frontend_ports))
        direct_ports = list(parsed.backend_ports)
        for port in parsed.extra_ports:
            if int(port) not in direct_ports:
                direct_ports.append(int(port))
        return _dedupe_preserve_order(direct_ports)
    return []


def _translated_targets(parsed: ParsedInput) -> list[tuple[int, str, int]]:
    if parsed.ingress == "caddy":
        if not parsed.caddy_ip:
            return []
        return [(external_port, parsed.caddy_ip, external_port) for external_port in _normalize_external_ports(parsed)]

    if parsed.ingress != "direct" or not parsed.backend_ip:
        return []

    if parsed.frontend_ports:
        mappings = _port_mappings(parsed.frontend_ports, parsed.backend_ports)
    else:
        mappings = [(port, port) for port in parsed.backend_ports]

    for port in parsed.extra_ports:
        pair = (int(port), int(port))
        if pair not in mappings:
            mappings.append(pair)

    return [(external_port, parsed.backend_ip, backend_port) for external_port, backend_port in mappings]


def _is_public_nat_eligible(parsed: ParsedInput) -> bool:
    return bool(
        parsed.exposure == "public"
        and not parsed.use_input_chain
        and parsed.frontend_hostname.strip()
        and parsed.backend_ip
        and parsed.backend_ports
        and parsed.protocol in {"tcp", "udp"}
        and parsed.ingress in {"caddy", "direct"}
        and (parsed.caddy_ip if parsed.ingress == "caddy" else True)
    )


def _validation_issue_key(issue: ValidationIssue) -> tuple[str, str | None, str]:
    return (issue.severity.strip().lower(), issue.service_key, issue.message)


def _dedupe_validation_issues(issues: list[ValidationIssue]) -> list[ValidationIssue]:
    deduped: list[ValidationIssue] = []
    seen: set[tuple[str, str | None, str]] = set()
    for issue in issues:
        key = _validation_issue_key(issue)
        if key in seen:
            continue
        seen.add(key)
        deduped.append(issue)
    return deduped


def _build_public_nat_pipeline(
    parsed_services: list[ParsedInput],
    *,
    wan_ips: list[str],
) -> PublicPipelineResult:
    result = PublicPipelineResult()
    candidates_by_group: dict[tuple[str, int, str], list[PublicNatCandidate]] = {}

    if not wan_ips:
        for parsed in parsed_services:
            if parsed.exposure == "public" and parsed.ingress in {"caddy", "direct"} and not parsed.use_input_chain:
                result.issues.append(
                    ValidationIssue(
                        severity="error",
                        service_key=parsed.service_key,
                        message=(
                            "public NAT generation requires [mikrotik].wan_ips to be configured"
                        ),
                    )
                )
        result.issues = _dedupe_validation_issues(result.issues)
        return result

    for service_order, parsed in enumerate(parsed_services):
        if (
            parsed.exposure == "public"
            and parsed.ingress in {"caddy", "direct"}
            and parsed.use_input_chain
        ):
            result.issues.append(
                ValidationIssue(
                    severity="warning",
                    service_key=parsed.service_key,
                    message=(
                        "public router-targeted service bypasses batch public NAT pipeline "
                        "and uses legacy input-chain rendering"
                    ),
                )
            )

        if (
            parsed.exposure == "public"
            and parsed.ingress in {"caddy", "direct"}
            and not _is_public_nat_eligible(parsed)
        ):
            result.issues.append(
                ValidationIssue(
                    severity="warning",
                    service_key=parsed.service_key,
                    message=(
                        "service is not public-NAT-eligible; requires frontend hostname, "
                        "backend IP, backend port, protocol, and supported ingress"
                    ),
                )
            )
            continue

        if not _is_public_nat_eligible(parsed):
            continue

        translated_targets = _translated_targets(parsed)
        if not translated_targets:
            result.issues.append(
                ValidationIssue(
                    severity="warning",
                    service_key=parsed.service_key,
                    message="service is public but produced no translated NAT targets",
                )
            )
            continue

        for external_port, dst_ip, dst_port in translated_targets:
            for wan_ip in wan_ips:
                candidate = PublicNatCandidate(
                    service_key=parsed.service_key,
                    service_name=parsed.service_name,
                    ingress=parsed.ingress,
                    protocol=parsed.protocol or "tcp",
                    external_port=int(external_port),
                    dst_ip=dst_ip,
                    dst_port=int(dst_port),
                    wan_ip=wan_ip,
                    frontend_hostname=parsed.frontend_hostname,
                    service_order=service_order,
                )
                group_key = (candidate.protocol, candidate.external_port, candidate.wan_ip)
                candidates_by_group.setdefault(group_key, []).append(candidate)

    for (protocol, external_port, wan_ip), group in candidates_by_group.items():
        distinct_targets = {
            (candidate.dst_ip, candidate.dst_port)
            for candidate in group
        }
        if len(distinct_targets) > 1:
            services = sorted({candidate.service_key for candidate in group}, key=str.casefold)
            services_display = ", ".join(services)
            for service_key in services:
                result.issues.append(
                    ValidationIssue(
                        severity="error",
                        service_key=service_key,
                        message=(
                            "conflicting public ingress mapping for "
                            f"{protocol}:{external_port} on WAN IP {wan_ip}; conflicting services: {services_display}"
                        ),
                    )
                )
            continue

        exact_candidates = sorted(
            group,
            key=lambda candidate: (
                candidate.service_order,
                candidate.service_name.casefold(),
                candidate.service_key.casefold(),
            ),
        )
        owner = exact_candidates[0]
        if owner.ingress == "caddy":
            result.caddy_candidates.append(owner)
        else:
            result.direct_candidates_by_service.setdefault(owner.service_key, []).append(owner)

    result.caddy_candidates.sort(key=lambda candidate: (candidate.protocol, candidate.external_port, candidate.wan_ip))
    for service_key, service_candidates in result.direct_candidates_by_service.items():
        service_candidates.sort(key=lambda candidate: (candidate.protocol, candidate.external_port, candidate.wan_ip))
        result.direct_candidates_by_service[service_key] = service_candidates

    result.issues = _dedupe_validation_issues(result.issues)
    return result


def _render_public_dnat_command(candidate: PublicNatCandidate) -> str:
    comment = (
        f"{COMMENT_MARKER}; public-dstnat; "
        f"{candidate.wan_ip}:{candidate.external_port}->{candidate.dst_ip}:{candidate.dst_port}"
    )
    return " ".join(
        [
            "/ip firewall nat add chain=dstnat action=dst-nat",
            "in-interface-list=WAN",
            f"dst-address={candidate.wan_ip}",
            f"protocol={candidate.protocol}",
            f"dst-port={candidate.external_port}",
            f"to-addresses={candidate.dst_ip}",
            f"to-ports={candidate.dst_port}",
            f"comment={mikrotik_quote(comment)}",
        ]
    )


def _render_public_forward_filter_command(
    candidate: PublicNatCandidate,
    *,
    place_before_filter_comment: str | None,
) -> str:
    comment = (
        f"{COMMENT_MARKER}; public-forward; "
        f"{candidate.protocol}:{candidate.dst_port}->{candidate.dst_ip}"
    )
    parts = [
        "/ip firewall filter add chain=forward action=accept",
        "in-interface-list=WAN",
        "connection-nat-state=dstnat",
        f"protocol={candidate.protocol}",
        f"dst-address={candidate.dst_ip}",
        f"dst-port={candidate.dst_port}",
        f"comment={mikrotik_quote(comment)}",
    ]
    if place_before_filter_comment:
        parts.append(
            f"place-before=[find comment={mikrotik_quote(place_before_filter_comment)}]"
        )
    return " ".join(parts)


def _render_hairpin_srcnat_commands(
    candidate: PublicNatCandidate,
    *,
    enable_hairpin: bool,
) -> list[str]:
    if not enable_hairpin:
        return []

    dst_address_list = _hairpin_target_list_name(
        protocol=candidate.protocol,
        port=int(candidate.dst_port),
    )

    commands: list[str] = []
    comment = (
        f"{COMMENT_MARKER}; hairpin; "
        f"{ADDRESS_LIST_HAIRPIN_SOURCES}->{dst_address_list}:{candidate.dst_port}/{candidate.protocol}"
    )
    commands.append(
        " ".join(
            [
                "/ip firewall nat add chain=srcnat action=masquerade",
                f"src-address-list={ADDRESS_LIST_HAIRPIN_SOURCES}",
                f"dst-address-list={dst_address_list}",
                f"protocol={candidate.protocol}",
                f"dst-port={candidate.dst_port}",
                f"comment={mikrotik_quote(comment)}",
            ]
        )
    )
    return commands


def _render_public_rule_bundle(
    candidates: list[PublicNatCandidate],
    *,
    enable_hairpin: bool,
    place_before_filter_comment: str | None,
) -> list[str]:
    commands: list[str] = []
    for candidate in candidates:
        commands.append(_render_public_dnat_command(candidate))
        commands.append(
            _render_public_forward_filter_command(
                candidate,
                place_before_filter_comment=place_before_filter_comment,
            )
        )
        commands.extend(
            _render_hairpin_srcnat_commands(
                candidate,
                enable_hairpin=enable_hairpin,
            )
        )
    return commands


def _render_hairpin_sources(entries: list[HairpinSourceEntry]) -> str:
    timestamp = _dt.datetime.now(_dt.UTC).strftime("%Y-%m-%dT%H:%M:%SZ")
    lines = [
        f"# {COMMENT_MARKER}",
        f"# generated_at={timestamp}",
        f"# address_list={ADDRESS_LIST_HAIRPIN_SOURCES}",
        "/ip firewall address-list",
    ]
    for entry in entries:
        lines.append(
            " ".join(
                [
                    "add",
                    f"list={ADDRESS_LIST_HAIRPIN_SOURCES}",
                    f"address={entry.subnet}",
                    f"comment={mikrotik_quote(entry.comment)}",
                ]
            )
        )
    lines.append("")
    return "\n".join(lines)


def _collect_public_candidates_for_hairpin(pipeline: PublicPipelineResult) -> list[PublicNatCandidate]:
    candidates = list(pipeline.caddy_candidates)
    for service_candidates in pipeline.direct_candidates_by_service.values():
        candidates.extend(service_candidates)
    candidates.sort(
        key=lambda candidate: (
            candidate.service_order,
            candidate.protocol,
            candidate.dst_ip,
            candidate.dst_port,
            candidate.external_port,
            candidate.wan_ip,
        )
    )
    return candidates


def _build_hairpin_candidates(candidates: list[PublicNatCandidate]) -> list[PublicNatCandidate]:
    deduped: list[PublicNatCandidate] = []
    seen: set[tuple[str, str, int]] = set()
    for candidate in candidates:
        dst_address_list = _hairpin_target_list_name(
            protocol=candidate.protocol,
            port=int(candidate.dst_port),
        )
        key = (candidate.protocol, dst_address_list, candidate.dst_port)
        if key in seen:
            continue
        seen.add(key)
        deduped.append(candidate)
    return deduped


def _build_hairpin_target_entries(candidates: list[PublicNatCandidate]) -> list[HairpinTargetEntry]:
    # First, collect all services per list_name (protocol/port combination)
    services_by_list_name: dict[str, list[str]] = {}
    for candidate in candidates:
        list_name = _hairpin_target_list_name(
            protocol=candidate.protocol,
            port=int(candidate.dst_port),
        )
        if list_name not in services_by_list_name:
            services_by_list_name[list_name] = []
        services_by_list_name[list_name].append(candidate.service_name)
    
    # Build entries with all services for each list, creating one entry per (list_name, address) pair
    entries: list[HairpinTargetEntry] = []
    seen: set[tuple[str, str]] = set()
    for candidate in candidates:
        list_name = _hairpin_target_list_name(
            protocol=candidate.protocol,
            port=int(candidate.dst_port),
        )
        key = (list_name, candidate.dst_ip)
        if key in seen:
            continue
        seen.add(key)
        
        # Comment includes all services using this address-list
        deduped_services = _dedupe_preserve_order(services_by_list_name[list_name])
        comment = ", ".join(deduped_services)
        entries.append(
            HairpinTargetEntry(
                list_name=list_name,
                address=candidate.dst_ip,
                comment=comment,
            )
        )
    return entries


def _render_hairpin_rules(
    *,
    source_entries: list[HairpinSourceEntry],
    candidates: list[PublicNatCandidate],
) -> str:
    timestamp = _dt.datetime.now(_dt.UTC).strftime("%Y-%m-%dT%H:%M:%SZ")
    lines = [
        f"# {COMMENT_MARKER}",
        f"# generated_at={timestamp}",
        f"# address_list={ADDRESS_LIST_HAIRPIN_SOURCES}",
        "/ip firewall address-list",
    ]
    for entry in source_entries:
        lines.append(
            " ".join(
                [
                    "add",
                    f"list={ADDRESS_LIST_HAIRPIN_SOURCES}",
                    f"address={entry.subnet}",
                    f"comment={mikrotik_quote(entry.comment)}",
                ]
            )
        )

    for entry in _build_hairpin_target_entries(candidates):
        lines.append(
            " ".join(
                [
                    "add",
                    f"list={entry.list_name}",
                    f"address={entry.address}",
                    f"comment={mikrotik_quote(entry.comment)}",
                ]
            )
        )

    lines.append("")
    for candidate in _build_hairpin_candidates(candidates):
        lines.extend(
            _render_hairpin_srcnat_commands(
                candidate,
                enable_hairpin=True,
            )
        )
    lines.append("")
    return "\n".join(lines)


def _render_validation_report(issues: list[ValidationIssue]) -> str:
    timestamp = _dt.datetime.now(_dt.UTC).strftime("%Y-%m-%dT%H:%M:%SZ")
    lines = [
        f"# {COMMENT_MARKER}",
        f"# generated_at={timestamp}",
        "# MikroTik validation report",
        "",
    ]
    if not issues:
        lines.append("No validation issues detected.")
        lines.append("")
        return "\n".join(lines)

    for issue in issues:
        scope = issue.service_key or "global"
        lines.append(f"[{issue.severity.upper()}] {scope}: {issue.message}")
    lines.append("")
    return "\n".join(lines)


def _render_service_commands(
    parsed: ParsedInput,
    *,
    include_public_direct_rules: bool,
) -> list[str]:
    commands: list[str] = []
    is_public = parsed.exposure == "public"
    mappings = _service_port_mappings(parsed)
    backend_ports_for_lists = _backend_ports_for_service(parsed, mappings)

    # --- Address-list entries (always useful for filter rules) ---

    if parsed.backend_ip:
        for backend_port in sorted(backend_ports_for_lists):
            list_name = _backend_group_list_name(parsed.protocol, backend_port)
            comment = (
                f"{COMMENT_MARKER}; backend-group; "
                f"{(parsed.protocol or 'any')}:{backend_port}"
            )
            commands.append(
                "/ip firewall address-list add "
                f"list={list_name} address={parsed.backend_ip} "
                f"comment={mikrotik_quote(comment)}"
            )

    # --- dstnat NAT rules ---
    should_generate_router_direct_nat = (
        parsed.ingress == "direct"
        and is_public
        and parsed.use_input_chain
    )
    should_generate_legacy_public_nat = (
        is_public
        and parsed.ingress == "dstnat"
        and parsed.enable_nat
        and not parsed.use_input_chain
    )

    if (
        (should_generate_router_direct_nat or should_generate_legacy_public_nat)
        or (include_public_direct_rules and parsed.enable_nat and parsed.ingress == "direct")
    ) and parsed.backend_ip and mappings:
        for frontend_port, backend_port in mappings:
            is_router_direct_public = should_generate_router_direct_nat
            is_batch_public_direct = (
                include_public_direct_rules
                and parsed.ingress == "direct"
                and not parsed.use_input_chain
            )
            if is_router_direct_public:
                comment = (
                    f"{COMMENT_MARKER}; router-dstnat; "
                    f"WAN:{frontend_port}->{parsed.backend_ip}:{backend_port}"
                )
            elif is_batch_public_direct:
                continue
            else:
                comment = (
                    f"{COMMENT_MARKER}; dstnat; "
                    f"{(parsed.protocol or 'any')}:{frontend_port}->{backend_port}"
                )

            nat_parts = [
                "/ip firewall nat add chain=dstnat action=dst-nat",
                "in-interface-list=WAN",
            ]
            if parsed.protocol:
                nat_parts.append(f"protocol={parsed.protocol}")
            nat_parts.extend([
                f"dst-port={frontend_port}",
                f"to-addresses={parsed.backend_ip}",
                f"to-ports={backend_port}",
                f"comment={mikrotik_quote(comment)}",
            ])
            commands.append(" ".join(nat_parts))

    # --- Firewall filter rules ---
    should_generate_filter = _should_generate_service_filter(parsed)
    if should_generate_filter:
        # Choose chain: input for router-destined traffic, forward otherwise.
        chain = "input" if parsed.use_input_chain else "forward"

        for _, backend_port in mappings or [(0, parsed.backend_ports[0] if parsed.backend_ports else 0)]:
            if backend_port <= 0:
                continue
            if is_public and chain == "forward" and parsed.ingress == "direct" and include_public_direct_rules:
                continue
            backend_list = _backend_group_list_name(parsed.protocol, int(backend_port))
            parts = [
                f"/ip firewall filter add chain={chain} action=accept",
                f"dst-port={backend_port}",
            ]
            if parsed.protocol:
                parts.insert(1, f"protocol={parsed.protocol}")
            # For input-chain rules the dst is the router itself, so
            # dst-address-list is not meaningful; for forward, reference
            # the backend address-list.
            if not parsed.use_input_chain:
                parts.append(f"dst-address-list={backend_list}")

            # Source constraints
            if parsed.source_ip:
                parts.append(f"src-address={parsed.source_ip}")
            if parsed.source_address_list:
                parts.append(f"src-address-list={parsed.source_address_list}")
            elif parsed.ingress == "caddy":
                parts.append(f"src-address-list={ADDRESS_LIST_CADDY_HOSTS}")

            # Interface constraints
            if parsed.in_interface:
                parts.append(f"in-interface={parsed.in_interface}")
            if parsed.in_interface_list:
                parts.append(f"in-interface-list={parsed.in_interface_list}")

            if parsed.out_interface and not parsed.use_input_chain:
                parts.append(f"out-interface={parsed.out_interface}")
            if parsed.dst_address_list and not parsed.use_input_chain:
                parts.append(f"dst-address-list={parsed.dst_address_list}")

            comment = (
                f"{COMMENT_MARKER}; {chain}; "
                f"{(parsed.protocol or 'any')}:{backend_port}"
            )
            parts.append(f"comment={mikrotik_quote(comment)}")

            # Insert before a known anchor rule so new rules land in the
            # correct position without manual reordering.
            place_comment = (
                parsed.place_before_input_comment
                if parsed.use_input_chain
                else parsed.place_before_filter_comment
            )
            if place_comment:
                parts.append(
                    f"place-before=[find comment={mikrotik_quote(place_comment)}]"
                )

            commands.append(" ".join(parts))

    # --- DHCP lease ---
    if parsed.enable_dhcp and parsed.dhcp_mac and parsed.dhcp_address:
        comment = f"{COMMENT_MARKER}; dhcp-lease; {parsed.dhcp_mac}"
        lease_parts = [
            "/ip dhcp-server lease add",
            f"mac-address={parsed.dhcp_mac}",
            f"address={parsed.dhcp_address}",
        ]
        if parsed.dhcp_server:
            lease_parts.append(f"server={parsed.dhcp_server}")
        lease_parts.append(f"comment={mikrotik_quote(comment)}")
        commands.append(
            " ".join(lease_parts)
        )

    return commands


def _render_caddy_dstnat(
    caddy_ip: str,
    *,
    public_candidates: list[PublicNatCandidate] | None = None,
    enable_hairpin: bool = False,
    place_before_filter_comment: str | None = None,
    wan_ips: list[str] | None = None,
) -> str:
    """Render the shared Caddy dstnat .rsc file content.

    This contains the WAN-facing Caddy public rules shared across all
    caddy-ingress services.
    """
    timestamp = _dt.datetime.now(_dt.UTC).strftime("%Y-%m-%dT%H:%M:%SZ")
    addr_list_comment = f"{COMMENT_MARKER}; caddy-hosts"
    if public_candidates:
        effective_candidates = public_candidates
    else:
        effective_candidates = []
        for wan_ip in wan_ips or []:
            effective_candidates.append(
                PublicNatCandidate(
                    service_key="caddy-dstnat",
                    service_name="caddy-dstnat",
                    ingress="caddy",
                    protocol="tcp",
                    external_port=80,
                    dst_ip=caddy_ip,
                    dst_port=80,
                    wan_ip=wan_ip,
                    frontend_hostname="",
                    service_order=0,
                )
            )
            effective_candidates.append(
                PublicNatCandidate(
                    service_key="caddy-dstnat",
                    service_name="caddy-dstnat",
                    ingress="caddy",
                    protocol="tcp",
                    external_port=443,
                    dst_ip=caddy_ip,
                    dst_port=443,
                    wan_ip=wan_ip,
                    frontend_hostname="",
                    service_order=0,
                )
            )

    lines = [
        f"# {COMMENT_MARKER}",
        f"# generated_at={timestamp}",
        "# Shared Caddy reverse-proxy public rules.",
        "# These forward public WAN traffic to the Caddy instance and add hairpin rules.",
        f"# caddy_ip={caddy_ip}",
        "",
        (
            "/ip firewall address-list add "
            f"list={ADDRESS_LIST_CADDY_HOSTS} address={caddy_ip} "
            f"comment={mikrotik_quote(addr_list_comment)}"
        ),
        "",
    ]
    lines.extend(
        _render_public_rule_bundle(
            effective_candidates,
            enable_hairpin=enable_hairpin,
            place_before_filter_comment=place_before_filter_comment,
        )
    )
    lines.append("")
    return "\n".join(lines)


def _build_parser(argv: list[str] | None = None) -> argparse.Namespace:
    repo_root = Path(__file__).resolve().parents[1]
    default_output_dir = repo_root / "generated" / "mikrotik"
    config_path, config = pre_parse_config(argv)

    globals_cfg = get_table(config, "globals")
    fw_cfg = get_table(config, "mikrotik") or get_table(config, "firewall")

    parser = argparse.ArgumentParser(
        prog="python -m homelab mikrotik",
        description=(
            "Prompt-driven MikroTik generator. Loads defaults from config and Google Sheets, "
            "supports single or batch service processing, opens curses forms, then shows a "
            "confirmation screen before printing/writing RouterOS commands."
        ),
    )
    parser.add_argument("--config", type=Path, default=config_path)
    parser.add_argument(
        "--sheet-url",
        default=str(get_config_value(globals_cfg, "sheet_url", DEFAULT_SHEET_URL)).strip(),
    )
    parser.add_argument(
        "--services-gid",
        type=int,
        default=int(get_config_value(globals_cfg, "services_gid", get_config_value(fw_cfg, "caddy_gid", 0))),
    )
    parser.add_argument(
        "--nodes-gid",
        type=int,
        default=int(get_config_value(globals_cfg, "nodes_gid", 344016240)),
    )
    parser.add_argument(
        "--zones-gid",
        type=int,
        default=int(get_config_value(globals_cfg, "zones_gid", 0)),
        help="GID for Zones sheet (used for hairpin source address-list generation)",
    )
    parser.add_argument(
        "--helpers-gid",
        type=int,
        default=int(get_config_value(globals_cfg, "helpers_gid", 0)),
        help="GID for Helpers sheet (required for selection options)",
    )
    parser.add_argument(
        "--sheet-timeout",
        type=float,
        default=float(get_config_value(globals_cfg, "sheet_timeout_seconds", 10)),
        help="Timeout in seconds for downloading Google Sheet CSV data",
    )
    # Resolve Caddy IP/hostname: prefer mikrotik.caddy_ips[0], fall back to globals.caddy_host.
    # The value may be an IP or a hostname — _resolve_caddy_ip() handles both at runtime.
    caddy_ip_default = ""
    fw_caddy_ips = get_config_value(fw_cfg, "caddy_ips", [])
    if isinstance(fw_caddy_ips, list) and fw_caddy_ips:
        caddy_ip_default = str(fw_caddy_ips[0]).strip()
    if not caddy_ip_default:
        caddy_ip_default = str(get_config_value(globals_cfg, "caddy_host", "")).strip()
    if not caddy_ip_default:
        # Legacy fallback for older configs.
        caddy_ip_default = str(
            get_config_value(globals_cfg, "caddy_ip",
                             get_config_value(globals_cfg, "caddy_hostname", ""))
        ).strip()
    parser.add_argument(
        "--caddy-ip",
        default=caddy_ip_default,
        help="Caddy proxy IP or hostname (resolved from Nodes sheet) used when ingress=caddy",
    )
    parser.add_argument(
        "--service",
        action="append",
        default=[],
        help="Optional service key to process (repeat to process multiple services)",
    )
    parser.add_argument(
        "--no-prompt",
        action="store_true",
        help="Skip interactive UI and generate directly from sheet-derived values (requires --service)",
    )
    parser.add_argument(
        "--caddy-dstnat-only",
        action="store_true",
        help=(
            "Generate only the shared caddy-dstnat.rsc file (WAN:80/443 → Caddy IP) "
            "without generating a per-service .rsc. The Caddy IP is resolved from the "
            "Nodes sheet via --caddy-ip (hostname or IP)."
        ),
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path(
            str(get_config_value(fw_cfg, "output", str(default_output_dir)))
        ),
        help="Directory where per-service .rsc files are written",
    )
    parser.add_argument("--stdout", action="store_true", help="Also print generated commands to stdout")
    parser.add_argument("--_debug", dest="debug", action="store_true", default=False, help=argparse.SUPPRESS)
    parser.add_argument("--_keep", dest="keep", action="store_true", default=False, help=argparse.SUPPRESS)
    return parser.parse_args(argv)


def _resolve_caddy_ip(
    *,
    caddy_ip_raw: str,
    sheet_url: str,
    nodes_gid: int,
    timeout_seconds: float,
    ip_column: str,
) -> str | None:
    """Resolve the Caddy IP from a raw value that may be a hostname or IP.

    If the value is already a valid IP it is returned directly.  Otherwise
    it is treated as a hostname and looked up in the Nodes sheet.
    """
    raw = (caddy_ip_raw or "").strip()
    if not raw:
        return None
    # Try as a literal IP first.
    direct = normalize_ip(raw)
    if direct:
        return direct
    # Fall back to Nodes sheet hostname lookup.
    return _resolve_hostname_ip_from_nodes(
        sheet_url=sheet_url,
        nodes_gid=nodes_gid,
        timeout_seconds=timeout_seconds,
        hostname=raw,
        ip_column=ip_column,
    )


def main(argv: list[str] | None = None) -> int:
    args = _build_parser(argv)
    configure_logging(debug=bool(args.debug))
    configure_sheet_csv_retention(keep=bool(args.keep))

    if not args.no_prompt and not args.caddy_dstnat_only and not _has_interactive_tty():
        print(
            "Error: interactive terminal required for curses UI (stdin/stdout must be a TTY).",
            file=sys.stderr,
        )
        return 2

    config = load_toml_or_exit(Path(args.config).expanduser().resolve())
    vlan_map = _parse_vlan_map(config)
    wan_ips, invalid_wan_ips = _parse_wan_ip_list(config)
    hairpin_source_entries, hairpin_source_issues = _load_hairpin_sources_from_zones_sheet(
        sheet_url=str(args.sheet_url),
        zones_gid=int(args.zones_gid),
        timeout_seconds=float(args.sheet_timeout),
    )
    hairpin_enabled = bool(hairpin_source_entries)

    lease_cfg = get_table(config, "mikrotik") or get_table(config, "dhcp_leases")

    lease_type_column = normalize_column_name(str(get_config_value(lease_cfg, "lease_type_column", "Static/DHCP")))
    ip_column = normalize_column_name(str(get_config_value(lease_cfg, "ip_column", "IP Address")))
    subnet_column = normalize_column_name(str(get_config_value(lease_cfg, "subnet_column", "Subnet")))
    mac_column = normalize_column_name(str(get_config_value(lease_cfg, "mac_column", "MAC Address")))
    vlan_id_column = normalize_column_name(str(get_config_value(lease_cfg, "vlan_id_column", "VLAN ID")))

    # ---- Resolve the Caddy IP (hostname or literal) via Nodes sheet ----
    caddy_ip_resolved = _resolve_caddy_ip(
        caddy_ip_raw=str(args.caddy_ip),
        sheet_url=str(args.sheet_url),
        nodes_gid=int(args.nodes_gid),
        timeout_seconds=float(args.sheet_timeout),
        ip_column=ip_column,
    )

    # ---- Standalone caddy-dstnat generation ----
    if args.caddy_dstnat_only:
        if not caddy_ip_resolved:
            print(
                f"Error: unable to resolve Caddy IP from '{args.caddy_ip}'. "
                "Provide a valid IP or a hostname present in the Nodes sheet.",
                file=sys.stderr,
            )
            return 1
        output_base = resolve_path_relative_to_config(
            Path(args.config).expanduser().resolve(),
            Path(args.output),
        )
        output_dir = output_base.parent if output_base.suffix else output_base
        caddy_dstnat_content = _render_caddy_dstnat(
            caddy_ip_resolved,
            enable_hairpin=False,
            wan_ips=wan_ips,
        )
        caddy_dstnat_path = output_dir / "caddy-dstnat.rsc"
        caddy_dstnat_path.parent.mkdir(parents=True, exist_ok=True)
        caddy_dstnat_path.write_text(caddy_dstnat_content, encoding="utf-8")
        print(f"Wrote {caddy_dstnat_path}")
        if hairpin_source_entries:
            hairpin_rules_path = output_dir / "hairpin-rules.rsc"
            hairpin_rules_path.write_text(
                _render_hairpin_rules(
                    source_entries=hairpin_source_entries,
                    candidates=[],
                ),
                encoding="utf-8",
            )
            print(f"Wrote {hairpin_rules_path}")
        if args.stdout:
            print(caddy_dstnat_content)
        return 0

    selection_options: dict[str, list[str]] = {}
    if not args.no_prompt:
        if int(args.helpers_gid) <= 0:
            print("Error: --helpers-gid is required and must be > 0.", file=sys.stderr)
            return 2

        try:
            helpers_values = _load_helpers_values(
                sheet_url=str(args.sheet_url),
                helpers_gid=int(args.helpers_gid),
                timeout_seconds=float(args.sheet_timeout),
            )
            selection_options = _build_selection_options(
                helpers_values=helpers_values,
                vlan_map=vlan_map,
            )
        except Exception as exc:
            print(f"Error: unable to load Helpers sheet values: {exc}", file=sys.stderr)
            return 1

        try:
            node_hostname_options = _list_node_hostnames_from_nodes_sheet(
                sheet_url=str(args.sheet_url),
                nodes_gid=int(args.nodes_gid),
                timeout_seconds=float(args.sheet_timeout),
            )
            if node_hostname_options:
                selection_options["hostname"] = node_hostname_options
        except Exception as exc:
            logger.warning("Unable to load Nodes sheet hostname options: %s", exc)

    service_values = [str(value).strip() for value in list(args.service or []) if str(value).strip()]
    selected_services: list[tuple[str, str]] = []
    seen_service_keys: set[str] = set()

    def _add_selected_service(service_key: str, source: str) -> None:
        normalized = service_key.strip()
        if not normalized:
            return
        dedupe_key = normalized.casefold()
        if dedupe_key in seen_service_keys:
            return
        seen_service_keys.add(dedupe_key)
        selected_services.append((normalized, source))

    if service_values:
        for service_value in service_values:
            _add_selected_service(service_value, "--service")

    if args.no_prompt and not selected_services:
        print("Error: --no-prompt requires at least one --service.", file=sys.stderr)
        return 2

    if not selected_services:
        service_options: list[str] = []
        try:
            service_options = _list_services_from_sheet(
                sheet_url=str(args.sheet_url),
                services_gid=int(args.services_gid),
                timeout_seconds=float(args.sheet_timeout),
            )
        except Exception as exc:
            logger.warning("Unable to load Services sheet for menu: %s", exc)

        if service_options:
            selections = _run_service_selection_menu(services=service_options)
            if selections == ["New..."]:
                manual_service_key = _run_single_input_prompt("")
                _add_selected_service(manual_service_key, "new")
            else:
                for service in selections:
                    _add_selected_service(service, "sheet")
        else:
            manual_service_key = _run_single_input_prompt("")
            _add_selected_service(manual_service_key, "new")

    if not selected_services:
        print("Error: at least one service key is required", file=sys.stderr)
        return 2

    # Read input_chain_hosts from config — hostnames whose services use
    # the INPUT chain (router/switch management UIs) instead of FORWARD.
    fw_cfg = get_table(config, "mikrotik") or get_table(config, "firewall")
    input_chain_hosts: list[str] = []
    raw_hosts = get_config_value(fw_cfg, "input_chain_hosts", [])
    if isinstance(raw_hosts, list):
        input_chain_hosts = [str(h).strip() for h in raw_hosts if str(h).strip()]

    place_before_filter_comment = str(
        get_config_value(fw_cfg, "place_before_filter_rule_comment", "")
    ).strip() or None
    place_before_input_comment = str(
        get_config_value(fw_cfg, "place_before_input_rule_comment", "")
    ).strip() or None

    output_base = resolve_path_relative_to_config(
        Path(args.config).expanduser().resolve(),
        Path(args.output),
    )
    output_dir = output_base.parent if output_base.suffix else output_base

    successes: list[Path] = []
    failures: list[tuple[str, str]] = []
    validation_issues: list[ValidationIssue] = []
    generated_filenames: set[str] = set()
    prepared_services: list[tuple[str, ServiceFormData]] = []

    for invalid_wan_ip in invalid_wan_ips:
        validation_issues.append(
            ValidationIssue(
                severity="error",
                message=f"invalid WAN IP configured in [mikrotik].wan_ips: {invalid_wan_ip}",
            )
        )
    validation_issues.extend(hairpin_source_issues)

    total_services = len(selected_services)
    for service_index, (service_key, selection_source) in enumerate(selected_services, start=1):
        prefill: dict[str, str | Any] = {}
        try:
            service_matches = _prefill_candidates_from_services_sheet(
                sheet_url=str(args.sheet_url),
                services_gid=int(args.services_gid),
                timeout_seconds=float(args.sheet_timeout),
                service_key=service_key,
            )

            if args.no_prompt:
                target = service_key.strip().lower()
                frontend_matches = [
                    match
                    for match in service_matches
                    if str(match.get("frontend_hostname") or "").strip().lower() == target
                ]
                if len(frontend_matches) > 1:
                    if not sys.stdin.isatty():
                        failures.append(
                            (
                                service_key,
                                (
                                    f"multiple services found for frontend hostname '{service_key}' "
                                    "and stdin is not interactive to select one"
                                ),
                            )
                        )
                        continue
                    prefill = _prompt_select_service_by_name(
                        service_key=service_key,
                        matches=frontend_matches,
                    )
                elif len(frontend_matches) == 1:
                    prefill = frontend_matches[0]
                elif service_matches:
                    prefill = service_matches[0]
            elif service_matches:
                prefill = service_matches[0]
        except Exception as exc:
            logger.warning("Unable to load services sheet prefill for %s: %s", service_key, exc)

        if args.no_prompt and not prefill:
            failures.append(
                (
                    service_key,
                    "service not found in Services sheet (required for --no-prompt)",
                )
            )
            continue

        form = ServiceFormData(service_key=service_key)

        for key, value in prefill.items():
            if hasattr(form, key) and value:
                setattr(form, key, value)

        try:
            nodes_prefill = _prefill_from_nodes_sheet(
                sheet_url=str(args.sheet_url),
                nodes_gid=int(args.nodes_gid),
                timeout_seconds=float(args.sheet_timeout),
                hostname=form.hostname,
                lease_type_column=lease_type_column,
                ip_column=ip_column,
                subnet_column=subnet_column,
                mac_column=mac_column,
                vlan_id_column=vlan_id_column,
            )
            for key, value in nodes_prefill.items():
                if hasattr(form, key) and value:
                    setattr(form, key, value)
        except Exception as exc:
            logger.warning("Unable to load nodes sheet prefill for %s: %s", service_key, exc)

        if not args.no_prompt:
            form = _run_form_ui(
                form,
                title=(
                    f"MikroTik service form ({service_index}/{total_services}) "
                    f"{service_key} [source: {selection_source}]"
                ),
                selection_options=selection_options,
            )
        prepared_services.append((service_key, form))

    if not prepared_services:
        for service_key, reason in failures:
            print(f"Failed service '{service_key}': {reason}", file=sys.stderr)
        print(
            f"Processed {len(selected_services)} service(s): "
            f"{len(successes)} succeeded, {len(failures)} failed"
        )
        return 1

    if not args.no_prompt:
        confirmed = _run_batch_confirmation_ui([form for _, form in prepared_services])
        if not confirmed:
            print("Aborted")
            return 130

    parsed_services: list[ParsedInput] = []
    for service_key, form in prepared_services:
        try:
            parsed = _normalize_form(
                form,
                vlan_map,
                caddy_ip=caddy_ip_resolved or "",
                input_chain_hosts=input_chain_hosts,
                place_before_filter_comment=place_before_filter_comment,
                place_before_input_comment=place_before_input_comment,
            )
        except ValueError as exc:
            failures.append((service_key, str(exc)))
            continue

        if parsed.enable_dhcp and not parsed.dhcp_server:
            if args.no_prompt:
                failures.append(
                    (
                        service_key,
                        (
                            "unable to determine DHCP server; missing VLAN ID for "
                            f"column '{vlan_id_column}' (expected server format dhcp-v<vlan-id>)"
                        ),
                    )
                )
                continue

            while True:
                print(
                    (
                        f"Enter DHCP VLAN ID for '{service_key}' "
                        "(server will be dhcp-v<vlan-id>): "
                    ),
                    end="",
                    flush=True,
                )
                entered_vlan_id = input().strip()
                parsed.dhcp_server = _dhcp_server_from_vlan_id(entered_vlan_id)
                if parsed.dhcp_server:
                    break
                print("Invalid VLAN ID. Enter a numeric VLAN ID (for example: 20).", file=sys.stderr)

        if parsed.enable_dhcp and parsed.dhcp_address and not parsed.dhcp_mac:
            parsed.dhcp_mac = _generate_random_mac()
            print(
                f"DHCP MAC not provided for '{service_key}'; generated random MAC {parsed.dhcp_mac}",
                file=sys.stderr,
            )

        parsed_services.append(parsed)

    public_pipeline = _build_public_nat_pipeline(
        parsed_services,
        wan_ips=wan_ips,
    )
    hairpin_candidates = _collect_public_candidates_for_hairpin(public_pipeline)
    validation_issues.extend(public_pipeline.issues)

    if not hairpin_enabled:
        has_public_targets = bool(public_pipeline.direct_candidates_by_service or public_pipeline.caddy_candidates)
        if has_public_targets:
            validation_issues.append(
                ValidationIssue(
                    severity="warning",
                    message=(
                        "no Zones rows with hairpin_allowed and valid Network values were found; "
                        "hairpin srcnat rules were skipped"
                    ),
                )
            )

    if not parsed_services:
        for service_key, reason in failures:
            print(f"Failed service '{service_key}': {reason}", file=sys.stderr)
        print(
            f"Processed {len(selected_services)} service(s): "
            f"{len(successes)} succeeded, {len(failures)} failed"
        )
        return 1

    for parsed in parsed_services:
        suppress_public_direct_rules = bool(
            parsed.exposure == "public"
            and parsed.ingress == "direct"
            and not parsed.use_input_chain
        )

        commands = _render_service_commands(
            parsed,
            include_public_direct_rules=suppress_public_direct_rules,
        )

        owned_public_candidates = public_pipeline.direct_candidates_by_service.get(parsed.service_key, [])
        if owned_public_candidates:
            commands.extend(
                _render_public_rule_bundle(
                    owned_public_candidates,
                    enable_hairpin=False,
                    place_before_filter_comment=place_before_filter_comment,
                )
            )

        if not commands:
            failures.append(
                (
                    parsed.service_key or parsed.service_name,
                    "no commands generated (check enabled sections and required fields)",
                )
            )
            continue

        timestamp = _dt.datetime.now(_dt.UTC).strftime("%Y-%m-%dT%H:%M:%SZ")
        lines = [
            f"# {COMMENT_MARKER}",
            f"# generated_at={timestamp}",
            f"# service={parsed.service_name}",
            f"# frontend_hostname={parsed.frontend_hostname or '(none)'}",
            "# address-list convention:",
            f"#   caddy hosts: {ADDRESS_LIST_CADDY_HOSTS}",
            f"#   backend groups: {ADDRESS_LIST_BACKEND_PREFIX}-<protocol>-<backend_port>",
            "# onboarding guidance:",
            "#   add/maintain caddy nodes:",
            (
                f"#     /ip firewall address-list add list={ADDRESS_LIST_CADDY_HOSTS} "
                'address=<CADDY_IP> comment="manual caddy node"'
            ),
            "#   add/maintain backend services:",
            (
                f"#     /ip firewall address-list add "
                f"list={ADDRESS_LIST_BACKEND_PREFIX}-<protocol>-<backend_port> "
                'address=<SERVICE_IP> comment="manual backend service"'
            ),
            "",
            *commands,
            "",
        ]
        content = "\n".join(lines)

        output_filename = f"{_normalized_service_filename(parsed.service_name)}.rsc"
        if output_filename.casefold() in generated_filenames:
            failures.append(
                (
                    parsed.service_key or parsed.service_name,
                    f"output filename collision for '{output_filename}' in current batch",
                )
            )
            continue
        generated_filenames.add(output_filename.casefold())

        output_path = output_dir / output_filename
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(content, encoding="utf-8")
        print(f"Wrote {output_path}")
        successes.append(output_path)

        if args.stdout:
            print(content)

    if successes and caddy_ip_resolved and public_pipeline.caddy_candidates:
        caddy_dstnat_content = _render_caddy_dstnat(
            caddy_ip_resolved,
            public_candidates=public_pipeline.caddy_candidates,
            enable_hairpin=False,
            place_before_filter_comment=place_before_filter_comment,
        )
        caddy_dstnat_path = output_dir / "caddy-dstnat.rsc"
        caddy_dstnat_path.parent.mkdir(parents=True, exist_ok=True)
        caddy_dstnat_path.write_text(caddy_dstnat_content, encoding="utf-8")
        print(f"Wrote {caddy_dstnat_path}")

    if successes and hairpin_source_entries:
        hairpin_rules_path = output_dir / "hairpin-rules.rsc"
        hairpin_rules_path.parent.mkdir(parents=True, exist_ok=True)
        hairpin_rules_path.write_text(
            _render_hairpin_rules(
                source_entries=hairpin_source_entries,
                candidates=hairpin_candidates,
            ),
            encoding="utf-8",
        )
        print(f"Wrote {hairpin_rules_path}")

    validation_issues = _dedupe_validation_issues(validation_issues)
    if validation_issues:
        validation_report_path = output_dir / "validation-report.txt"
        validation_report_path.parent.mkdir(parents=True, exist_ok=True)
        validation_report_path.write_text(
            _render_validation_report(validation_issues),
            encoding="utf-8",
        )
        print(f"Wrote {validation_report_path}")

    for service_key, reason in failures:
        print(f"Failed service '{service_key}': {reason}", file=sys.stderr)

    for issue in validation_issues:
        if issue.severity.strip().lower() == "error":
            scope = issue.service_key or "global"
            print(f"Validation error [{scope}]: {issue.message}", file=sys.stderr)

    print(
        f"Processed {len(selected_services)} service(s): "
        f"{len(successes)} succeeded, {len(failures)} failed"
    )

    if failures:
        return 1
    if any(issue.severity.strip().lower() == "error" for issue in validation_issues):
        return 1
    if not successes:
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
