#!/usr/bin/env python3

import argparse
import datetime as _dt
import hashlib
import ipaddress
import os
import shlex
import shutil
import subprocess
import sys
import tempfile
from dataclasses import dataclass
from pathlib import Path

import pandas as pd

from .config import load_toml_or_exit, resolve_path_relative_to_config

COMMENT_MARKER = "generated by python -m homelab mikrotik-dhcp"


def _get_config_value(config: dict, key: str, default):
    value = config.get(key, default)
    return default if value is None else value


def _parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    tool_dir = Path(__file__).resolve().parent / "mikrotik"
    default_config = Path(__file__).resolve().parent / "config.toml"

    pre_parser = argparse.ArgumentParser(add_help=False)
    pre_parser.add_argument(
        "--config",
        type=Path,
        default=default_config,
        help="Path to TOML config file containing default parameters",
    )
    pre_args, _ = pre_parser.parse_known_args(argv)
    config_path = pre_args.config.expanduser().resolve()
    config = load_toml_or_exit(config_path)

    globals_cfg = config.get("globals", {}) if isinstance(config.get("globals", {}), dict) else {}

    # New unified config layout prefers dedicated sections.
    section_leases = config.get("mikrotik_dhcp_leases", {})
    section_defaults = config.get("mikrotik_defaults", {})
    if isinstance(section_leases, dict) or isinstance(section_defaults, dict):
        lease_cfg = section_leases if isinstance(section_leases, dict) else {}
        defaults_cfg = section_defaults if isinstance(section_defaults, dict) else {}
    else:
        # Legacy mikrotik-config.toml layout.
        lease_cfg = config.get("dhcp_leases", {}) if isinstance(config.get("dhcp_leases", {}), dict) else {}
        defaults_cfg = config.get("defaults", {}) if isinstance(config.get("defaults", {}), dict) else {}

    parser = argparse.ArgumentParser(
        description=(
            "Generate MikroTik RouterOS CLI commands to reconcile DHCP static leases "
            "based on the Nodes tab in a Google Sheet. The script downloads the current "
            "lease configuration from the router, compares it to the sheet, and prints "
            "the required /ip dhcp-server lease add/set commands."
        )
    )

    parser.add_argument(
        "--config",
        type=Path,
        default=config_path,
        help="Path to TOML config file containing default parameters",
    )

    parser.add_argument(
        "--sheet-url",
        default=_get_config_value(
            lease_cfg,
            "sheet_url",
            _get_config_value(
                globals_cfg,
                "sheet_url",
                (
                    "https://docs.google.com/spreadsheets/d/"
                    "1f4emn4uIPscEgOHtgmETODlTvz1eh2xZlnpBBNGQlWA/"
                    "export?format=csv&gid=0"
                ),
            ),
        ),
        help="Google Sheets CSV export URL containing 'gid=0' that will be replaced with the Nodes GID.",
    )
    parser.add_argument(
        "--nodes-gid",
        type=int,
        default=int(_get_config_value(lease_cfg, "nodes_gid", _get_config_value(globals_cfg, "nodes_gid", 344016240))),
        help="GID for Nodes sheet",
    )

    parser.add_argument(
        "--mikrotik-host",
        default=_get_config_value(
            lease_cfg,
            "mikrotik_host",
            _get_config_value(globals_cfg, "mikrotik_host", _get_config_value(config, "mikrotik_host", None)),
        ),
        help="MikroTik RouterOS hostname/IP (required)",
    )
    parser.add_argument(
        "--mikrotik-user",
        default=_get_config_value(
            lease_cfg,
            "mikrotik_user",
            _get_config_value(globals_cfg, "mikrotik_user", _get_config_value(config, "mikrotik_user", None)),
        ),
        help="MikroTik RouterOS username (required)",
    )
    parser.add_argument(
        "--ssh-port",
        type=int,
        default=int(
            _get_config_value(
                lease_cfg,
                "mikrotik_ssh_port",
                _get_config_value(
                    lease_cfg,
                    "ssh_port",
                    _get_config_value(
                        globals_cfg,
                        "mikrotik_ssh_port",
                        _get_config_value(
                            globals_cfg,
                            "ssh_port",
                            _get_config_value(
                                config,
                                "mikrotik_ssh_port",
                                _get_config_value(config, "ssh_port", _get_config_value(defaults_cfg, "ssh_port", 22)),
                            ),
                        ),
                    ),
                ),
            )
        ),
        help="SSH port for RouterOS (default: 22)",
    )

    identity_value = _get_config_value(
        lease_cfg,
        "mikrotik_ssh_identity_file",
        _get_config_value(
            lease_cfg,
            "ssh_identity_file",
            _get_config_value(
                globals_cfg,
                "mikrotik_ssh_identity_file",
                _get_config_value(
                    globals_cfg,
                    "ssh_identity_file",
                    _get_config_value(
                        config,
                        "mikrotik_ssh_identity_file",
                        _get_config_value(
                            config,
                            "ssh_identity_file",
                            _get_config_value(defaults_cfg, "ssh_identity_file", ""),
                        ),
                    ),
                ),
            ),
        ),
    )
    identity_str = str(identity_value or "").strip()
    parser.add_argument(
        "--ssh-identity-file",
        type=Path,
        default=Path(identity_str).expanduser() if identity_str else None,
        help="Optional SSH private key path (passed as -i)",
    )

    parser.add_argument(
        "--mikrotik-password-env",
        default=_get_config_value(
            lease_cfg,
            "mikrotik_password_env",
            _get_config_value(
                lease_cfg,
                "password_env",
                _get_config_value(
                    globals_cfg,
                    "mikrotik_password_env",
                    _get_config_value(
                        globals_cfg,
                        "password_env",
                        _get_config_value(
                            config,
                            "mikrotik_password_env",
                            _get_config_value(
                                config,
                                "password_env",
                                _get_config_value(defaults_cfg, "password_env", ""),
                            ),
                        ),
                    ),
                ),
            ),
        ),
        help=(
            "Environment variable containing the SSH password (used via sshpass). "
            "If set, sshpass is required. Example: MIKROTIK_PASSWORD"
        ),
    )

    parser.add_argument(
        "--lease-type-column",
        default=_get_config_value(
            lease_cfg,
            "lease_type_column",
            _get_config_value(config, "lease_type_column", "Static/DHCP"),
        ),
        help="Nodes sheet column containing 'Static' or 'DHCP'",
    )
    parser.add_argument(
        "--ip-column",
        default=_get_config_value(
            lease_cfg,
            "ip_column",
            _get_config_value(config, "ip_column", "IP Address"),
        ),
        help="Nodes sheet column containing an IP address",
    )
    parser.add_argument(
        "--subnet-column",
        default=_get_config_value(
            lease_cfg,
            "subnet_column",
            _get_config_value(config, "subnet_column", "Subnet"),
        ),
        help="Nodes sheet column containing a subnet (e.g. 192.168.10.0/24)",
    )
    parser.add_argument(
        "--mac-column",
        default=_get_config_value(
            lease_cfg,
            "mac_column",
            _get_config_value(config, "mac_column", "MAC Address"),
        ),
        help="Nodes sheet column containing a MAC address",
    )

    parser.add_argument(
        "--output",
        type=Path,
        default=Path(
            _get_config_value(
                lease_cfg,
                "output",
                _get_config_value(config, "output", str(tool_dir / "mikrotik-dhcp-leases.rsc")),
            )
        ),
        help="Path to write generated RouterOS CLI commands",
    )

    parser.add_argument(
        "--backup-dir",
        type=Path,
        default=Path(
            _get_config_value(
                lease_cfg,
                "backup_dir",
                _get_config_value(
                    globals_cfg,
                    "backup_dir",
                    _get_config_value(
                        config,
                        "backup_dir",
                        _get_config_value(defaults_cfg, "backup_dir", str(tool_dir / "backups")),
                    ),
                ),
            )
        ),
        help="Directory to write RouterOS /export backups into (used after --apply)",
    )

    parser.add_argument(
        "--stdout",
        action="store_true",
        help="Print commands to stdout instead of writing --output",
    )

    parser.add_argument(
        "--apply",
        action="store_true",
        help=(
            "If set, apply the required changes to the router over SSH. "
            "Without --apply, the script only generates the commands file."
        ),
    )

    parser.add_argument(
        "--yes",
        action="store_true",
        help="Skip the interactive confirmation prompt when used with --apply.",
    )

    parser.add_argument(
        "--debug",
        action="store_true",
        default=bool(_get_config_value(lease_cfg, "debug", _get_config_value(config, "debug", False))),
        help="Print debug output (including why Static rows were skipped).",
    )

    parser.add_argument(
        "--debug-row",
        action="append",
        type=int,
        default=[],
        help=(
            "Print detailed debug info for a specific Nodes sheet row number (1-based, as shown in Sheets). "
            "May be provided multiple times."
        ),
    )

    return parser.parse_args(argv)


def _normalize_string(value) -> str:
    if value is None or pd.isna(value):
        return ""
    return str(value).strip()


def _normalize_mac(mac: str) -> str:
    mac = mac.strip().upper().replace("-", ":")
    mac = ":".join([part.zfill(2) for part in mac.split(":") if part != ""])  # tolerate 1-digit parts
    return mac


def _mikrotik_quote(value: str) -> str:
    # RouterOS uses double quotes. Escape backslashes and quotes.
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


@dataclass(frozen=True)
class DesiredLease:
    mac: str
    address: str
    subnet: str


def _load_desired_leases_from_sheet(
    *,
    sheet_url: str,
    nodes_gid: int,
    lease_type_column: str,
    ip_column: str,
    subnet_column: str,
    mac_column: str,
    debug: bool,
    debug_rows: set[int],
) -> list[DesiredLease]:
    nodes_url = sheet_url.replace("gid=0", f"gid={nodes_gid}")

    try:
        nodes_df = pd.read_csv(nodes_url)
    except Exception as exc:
        print(f"Error loading Nodes sheet CSV: {exc}", file=sys.stderr)
        print("Ensure the sheet is public (CSV export) or switch to an authenticated method.", file=sys.stderr)
        sys.exit(1)

    leases: list[DesiredLease] = []
    seen_macs: set[str] = set()
    seen_ips: set[str] = set()

    dhcp_rows = 0
    dhcp_rows_kept = 0
    dhcp_rows_skipped = 0

    # enumerate() gives us a predictable 1-based-ish row number for messages.
    # start=2 because row 1 is the header in the sheet.
    for row_number, (_, row) in enumerate(nodes_df.iterrows(), start=2):
        ip_raw = _normalize_string(row.get(ip_column, ""))
        subnet_raw = _normalize_string(row.get(subnet_column, ""))
        mac_raw = _normalize_string(row.get(mac_column, ""))

        lease_type_raw = _normalize_string(row.get(lease_type_column, ""))
        lease_type = lease_type_raw.lower()

        if row_number in debug_rows:
            print(
                "DebugRow: "
                + f"row={row_number} lease_type={lease_type_raw!r} ip={ip_raw!r} subnet={subnet_raw!r} mac={mac_raw!r}",
                file=sys.stderr,
            )
        # We manage DHCP reservations for nodes that are configured to use DHCP.
        # Rows marked Static are intentionally ignored (no warnings).
        if lease_type != "dhcp":
            continue

        dhcp_rows += 1

        def warn_missing_fields() -> None:
            missing_fields: list[str] = []
            if not ip_raw:
                missing_fields.append(ip_column)
            if not subnet_raw:
                missing_fields.append(subnet_column)
            if not mac_raw:
                missing_fields.append(mac_column)
            if missing_fields:
                print(
                    f"Warning: row {row_number} marked DHCP but missing field(s): {', '.join(missing_fields)}",
                    file=sys.stderr,
                )

        def debug_skip(reason: str) -> None:
            nonlocal dhcp_rows_skipped
            dhcp_rows_skipped += 1
            if not debug and row_number not in debug_rows:
                return
            details = f"ip={ip_raw!r} mac={mac_raw!r} subnet={subnet_raw!r}"
            print(
                f"Debug: skipping DHCP row {row_number}: {reason} ({details})",
                file=sys.stderr,
            )
            if row_number in debug_rows:
                print(f"DebugRow: decision=SKIP reason={reason}", file=sys.stderr)

        if not ip_raw or not mac_raw or not subnet_raw:
            warn_missing_fields()
            debug_skip("missing required field")
            continue

        try:
            ipaddress.ip_address(ip_raw)
        except ValueError:
            debug_skip("invalid IP")
            continue

        subnet = subnet_raw
        try:
            network = ipaddress.ip_network(subnet, strict=False)
        except ValueError:
            debug_skip("invalid Subnet CIDR")
            continue

        if ipaddress.ip_address(ip_raw) not in network:
            debug_skip("IP not in subnet")
            continue

        try:
            mac = _normalize_mac(mac_raw)
        except Exception:
            debug_skip("invalid MAC")
            continue

        if mac in seen_macs:
            debug_skip("duplicate MAC in sheet")
            continue
        if ip_raw in seen_ips:
            debug_skip("duplicate IP in sheet")
            continue

        seen_macs.add(mac)
        seen_ips.add(ip_raw)
        leases.append(DesiredLease(mac=mac, address=ip_raw, subnet=subnet))
        dhcp_rows_kept += 1

        if row_number in debug_rows:
            print("DebugRow: decision=KEEP", file=sys.stderr)

    if debug:
        summary = (
            f"Debug: Nodes sheet parsed. "
            f"dhcp_rows={dhcp_rows} kept={dhcp_rows_kept} skipped={dhcp_rows_skipped}"
        )
        print(summary, file=sys.stderr)

    return leases


def _require_command(name: str) -> None:
    if shutil.which(name) is None:
        print(f"Error: required command not found in PATH: {name}", file=sys.stderr)
        sys.exit(1)


def _prefix_sshpass(*, argv: list[str], enabled: bool) -> list[str]:
    return (["sshpass", "-e", *argv] if enabled else list(argv))


def _sshpass_env_from_password_env(*, password_env: str | None) -> dict[str, str] | None:
    if not password_env:
        return None
    env_value = os.environ.get(password_env)
    if not env_value:
        raise SystemExit(f"Error: password environment variable is not set: {password_env}")
    env = dict(os.environ)
    env["SSHPASS"] = env_value
    return env


def _ssh_control_path(username: str, host: str, port: int) -> Path:
    key = f"{username}@{host}:{port}".encode("utf-8")
    digest = hashlib.sha1(key).hexdigest()[:12]
    return Path(tempfile.gettempdir()) / f"mikrotik-ssh-{digest}.sock"


def _ssh_mux_options(control_path: Path) -> list[str]:
    return [
        "-o",
        "ControlMaster=auto",
        "-o",
        "ControlPersist=60s",
        "-o",
        f"ControlPath={control_path}",
    ]


def _ssh_base_args(*, control_path: Path, port: int, identity_file: Path | None) -> list[str]:
    args: list[str] = ["ssh", *(_ssh_mux_options(control_path)), "-p", str(port)]
    if identity_file is not None:
        args.extend(["-i", str(identity_file)])
    return args


def _scp_base_args(*, control_path: Path, port: int, identity_file: Path | None) -> list[str]:
    args: list[str] = ["scp", *(_ssh_mux_options(control_path)), "-P", str(port)]
    if identity_file is not None:
        args.extend(["-i", str(identity_file)])
    return args


def _ssh_start_master(*, ssh_args: list[str], target: str, env: dict[str, str] | None) -> None:
    # Start (or reuse) a master connection so subsequent commands share auth.
    subprocess.run([*ssh_args, "-Nf", target], check=True, env=env)


def _ssh_stop_master(*, ssh_args: list[str], target: str, env: dict[str, str] | None) -> None:
    subprocess.run([*ssh_args, "-O", "exit", target], check=False, env=env)


def _ssh_run(
    *,
    ssh_args: list[str],
    target: str,
    command: str,
    check: bool = True,
    env: dict[str, str] | None,
) -> subprocess.CompletedProcess:
    return subprocess.run(
        [*ssh_args, target, command],
        check=check,
        text=True,
        capture_output=True,
        env=env,
    )


def _parse_routeros_terse(text: str) -> list[dict]:
    rows: list[dict] = []
    for raw_line in text.splitlines():
        line = raw_line.strip()
        if not line:
            continue

        try:
            tokens = shlex.split(line, posix=True)
        except ValueError:
            tokens = line.split()

        row: dict[str, str] = {}
        for token in tokens:
            if "=" not in token:
                continue
            key, value = token.split("=", 1)
            row[key] = value

        if row:
            rows.append(row)

    return rows


def _fetch_static_leases_from_router(
    *,
    ssh_args: list[str],
    target: str,
    env: dict[str, str] | None,
) -> list[dict]:
    # Terse output is easiest to parse.
    cmd = "/ip dhcp-server lease print terse without-paging"
    result = _ssh_run(ssh_args=ssh_args, target=target, command=cmd, env=env)
    rows = _parse_routeros_terse(result.stdout)

    static_leases: list[dict] = []
    for lease in rows:
        dynamic_raw = str(lease.get("dynamic", "no")).lower()
        is_dynamic = dynamic_raw in {"yes", "true", "1"}
        if is_dynamic:
            continue
        static_leases.append(lease)
    return static_leases


def _fetch_dhcp_server_by_subnet_from_router(
    *,
    ssh_args: list[str],
    target: str,
    env: dict[str, str] | None,
) -> dict[str, str]:
    cmd = "/ip dhcp-server network print terse without-paging"
    result = _ssh_run(ssh_args=ssh_args, target=target, command=cmd, env=env)
    rows = _parse_routeros_terse(result.stdout)

    mapping: dict[str, str] = {}
    for row in rows:
        cidr = _normalize_string(row.get("address", ""))
        server = _normalize_string(row.get("dhcp-server", ""))
        if cidr and server:
            mapping[cidr] = server
    return mapping


def _index_leases(static_leases: list[dict]):
    by_mac: dict[str, dict] = {}
    by_ip: dict[str, dict] = {}

    for lease in static_leases:
        mac = _normalize_string(lease.get("mac-address", ""))
        addr = _normalize_string(lease.get("address", ""))
        if mac:
            try:
                by_mac[_normalize_mac(mac)] = lease
            except Exception:
                pass
        if addr:
            by_ip[addr] = lease

    return by_mac, by_ip


def _build_comment(*, subnet: str) -> str:
    if subnet:
        return f"{COMMENT_MARKER}; subnet={subnet}"
    return COMMENT_MARKER


@dataclass(frozen=True)
class LeaseOperation:
    kind: str  # 'add' | 'set'
    command: str


def _plan_operations(
    *,
    desired: list[DesiredLease],
    existing_static: list[dict],
    dhcp_server_by_subnet: dict[str, str],
    debug: bool,
) -> list[LeaseOperation]:
    by_mac, by_ip = _index_leases(existing_static)

    ops: list[LeaseOperation] = []

    for lease in desired:
        comment = _build_comment(subnet=lease.subnet)
        server = ""
        if lease.subnet and lease.subnet in dhcp_server_by_subnet:
            server = dhcp_server_by_subnet[lease.subnet]

        def build_set_command(*, selector: str) -> str:
            parts = [
                "/ip dhcp-server lease set",
                selector,
                f"address={lease.address}",
                f"mac-address={_mikrotik_quote(lease.mac)}",
                f"comment={_mikrotik_quote(comment)}",
                "disabled=no",
            ]
            if server:
                parts.append(f"server={_mikrotik_quote(server)}")
            return " ".join(parts)

        def build_add_command() -> str:
            parts = [
                "/ip dhcp-server lease add",
                f"address={lease.address}",
                f"mac-address={_mikrotik_quote(lease.mac)}",
                f"comment={_mikrotik_quote(comment)}",
                "disabled=no",
            ]
            if server:
                parts.append(f"server={_mikrotik_quote(server)}")
            return " ".join(parts)

        existing = by_mac.get(lease.mac)
        if existing is not None:
            existing_addr = _normalize_string(existing.get("address", ""))
            existing_comment = _normalize_string(existing.get("comment", ""))
            existing_disabled = str(existing.get("disabled", "false")).lower() == "true"

            if existing_addr == lease.address and (not existing_disabled) and debug:
                print(
                    "Debug: desired lease already exists (MAC+IP match): "
                    + f"mac={lease.mac} ip={lease.address}",
                    file=sys.stderr,
                )

            if existing_addr == lease.address and (not existing_disabled) and (COMMENT_MARKER in existing_comment):
                continue

            selector = f"[find where mac-address={_mikrotik_quote(lease.mac)}]"
            ops.append(LeaseOperation(kind="set", command=build_set_command(selector=selector)))
            continue

        existing = by_ip.get(lease.address)
        if existing is not None:
            existing_mac = _normalize_string(existing.get("mac-address", ""))
            if existing_mac:
                try:
                    existing_mac = _normalize_mac(existing_mac)
                except Exception:
                    pass

            if (existing_mac == lease.mac) and debug:
                print(
                    "Debug: desired lease already exists (IP+MAC match): "
                    + f"mac={lease.mac} ip={lease.address}",
                    file=sys.stderr,
                )

            # Lease exists for this IP but may be the wrong MAC/comment/server.
            selector = f"[find where address={lease.address}]"
            ops.append(LeaseOperation(kind="set", command=build_set_command(selector=selector)))
            continue

        ops.append(LeaseOperation(kind="add", command=build_add_command()))

    return ops


def _generate_commands(
    *,
    desired: list[DesiredLease],
    existing_static: list[dict],
    dhcp_server_by_subnet: dict[str, str],
):
    ops = _plan_operations(
        desired=desired,
        existing_static=existing_static,
        dhcp_server_by_subnet=dhcp_server_by_subnet,
        debug=False,
    )

    now = _dt.datetime.now(tz=_dt.timezone.utc).isoformat()
    commands: list[str] = [
        f"# {COMMENT_MARKER}",
        f"# generated-at={now}",
        "#",
        "# Apply with: /import file-name=mikrotik-dhcp-leases.rsc",
        "",
    ]

    for op in ops:
        commands.append(op.command)

    if not ops:
        commands.append("# No changes required")

    return commands


def _apply_operations_to_router(
    *,
    ssh_args: list[str],
    target: str,
    ops: list[LeaseOperation],
    env: dict[str, str] | None,
) -> None:
    if not ops:
        print("No changes to apply")
        return

    adds = sum(1 for op in ops if op.kind == "add")
    sets = sum(1 for op in ops if op.kind == "set")

    # Run in one SSH invocation to reduce overhead and auth prompts.
    joined = "; ".join(op.command for op in ops)
    _ssh_run(ssh_args=ssh_args, target=target, command=joined, env=env)
    print(f"Applied changes to router: {adds} adds, {sets} updates")


def _export_router_config_via_ssh_to_file(
    *,
    ssh_args: list[str],
    target: str,
    export_base_name: str,
    env: dict[str, str] | None,
) -> str:
    """Export router config to a remote file and return the remote filename.

    We prefer to hide sensitive values/passwords.
    """

    # RouterOS writes <name>.rsc
    remote_file = f"{export_base_name}.rsc"

    # Try common flags across RouterOS versions.
    export_cmds = [
        f"/export file={export_base_name} hide-sensitive=yes",
        f"/export file={export_base_name} show-sensitive=no",
        f"/export file={export_base_name}",
    ]

    last_error: str | None = None
    for cmd in export_cmds:
        try:
            _ssh_run(ssh_args=ssh_args, target=target, command=cmd, check=True, env=env)
            return remote_file
        except subprocess.CalledProcessError as exc:
            last_error = (exc.stderr or exc.stdout or str(exc)).strip()
            continue

    raise RuntimeError(f"Failed to export router configuration via SSH: {last_error}")


def _download_remote_file_via_scp(
    *,
    scp_args: list[str],
    target: str,
    remote_filename: str,
    local_path: Path,
    env: dict[str, str] | None,
) -> None:
    local_path.parent.mkdir(parents=True, exist_ok=True)
    subprocess.run(
        [
            *scp_args,
            f"{target}:{remote_filename}",
            str(local_path),
        ],
        check=True,
        env=env,
    )


def _remove_remote_file(
    *,
    ssh_args: list[str],
    target: str,
    remote_filename: str,
    env: dict[str, str] | None,
) -> None:
    # Best effort cleanup.
    _ssh_run(
        ssh_args=ssh_args,
        target=target,
        command=f"/file remove {remote_filename}",
        check=False,
        env=env,
    )


def _command_lines_only(commands: list[str]) -> list[str]:
    return [line for line in commands if line.strip().startswith("/ip ")]


def _confirm_apply(*, commands: list[str], op_count: int) -> None:
    command_lines = _command_lines_only(commands)

    print("Planned RouterOS commands:", file=sys.stderr)
    if command_lines:
        for line in command_lines:
            print(line, file=sys.stderr)
    else:
        print("(No command lines; nothing to apply)", file=sys.stderr)

    print("", file=sys.stderr)
    print(f"Summary: {op_count} change(s)", file=sys.stderr)
    print("Type 'apply' to continue, or anything else to abort:", file=sys.stderr)

    try:
        response = input("> ").strip().lower()
    except EOFError:
        response = ""

    if response != "apply":
        raise SystemExit("Aborted")


def main(argv: list[str] | None = None) -> int:
    args = _parse_args(argv)

    config_path = args.config.expanduser().resolve()

    missing: list[str] = []
    if not args.mikrotik_host:
        missing.append("mikrotik_host")
    if not args.mikrotik_user:
        missing.append("mikrotik_user")

    if missing:
        print(
            "Error: missing router credential(s): " + ", ".join(missing),
            file=sys.stderr,
        )
        print(f"Config file used: {config_path}", file=sys.stderr)
        if "mikrotik_host" in missing or "mikrotik_user" in missing:
            print(
                "Host/user sources checked: --mikrotik-host/--mikrotik-user and mikrotik_host/mikrotik_user in config",
                file=sys.stderr,
            )
        return 2

    # Type narrowing for static analyzers (and to guard against non-string TOML values).
    mikrotik_host: str = str(args.mikrotik_host)
    mikrotik_user: str = str(args.mikrotik_user)

    _require_command("ssh")
    if args.apply:
        _require_command("scp")

    password_env_raw = str(args.mikrotik_password_env or "").strip()
    password_env = password_env_raw or None
    run_env = _sshpass_env_from_password_env(password_env=password_env)
    use_sshpass = run_env is not None
    if use_sshpass:
        _require_command("sshpass")

    ssh_port: int = int(args.ssh_port)
    identity_file: Path | None = (
        resolve_path_relative_to_config(config_path, args.ssh_identity_file)
        if args.ssh_identity_file is not None
        else None
    )
    if identity_file is not None and not identity_file.exists():
        print(f"Error: SSH identity file not found: {identity_file}", file=sys.stderr)
        return 2

    target = f"{mikrotik_user}@{mikrotik_host}"
    control_path = _ssh_control_path(mikrotik_user, mikrotik_host, ssh_port)
    ssh_args = _prefix_sshpass(
        argv=_ssh_base_args(control_path=control_path, port=ssh_port, identity_file=identity_file),
        enabled=use_sshpass,
    )
    scp_args = _prefix_sshpass(
        argv=_scp_base_args(control_path=control_path, port=ssh_port, identity_file=identity_file),
        enabled=use_sshpass,
    )

    config = load_toml_or_exit(config_path)
    section_leases = config.get("mikrotik_dhcp_leases", {})
    section_defaults = config.get("mikrotik_defaults", {})
    if isinstance(section_leases, dict) or isinstance(section_defaults, dict):
        lease_cfg = section_leases if isinstance(section_leases, dict) else {}
    else:
        lease_cfg = config.get("dhcp_leases", {}) if isinstance(config.get("dhcp_leases", {}), dict) else {}

    dhcp_server_by_subnet_override = _get_config_value(
        lease_cfg,
        "dhcp_server_by_subnet",
        {},
    )
    if dhcp_server_by_subnet_override is None:
        dhcp_server_by_subnet_override = {}

    desired_leases = _load_desired_leases_from_sheet(
        sheet_url=args.sheet_url,
        nodes_gid=args.nodes_gid,
        lease_type_column=args.lease_type_column,
        ip_column=args.ip_column,
        subnet_column=args.subnet_column,
        mac_column=args.mac_column,
        debug=bool(args.debug),
        debug_rows=set(int(x) for x in (args.debug_row or []) if x is not None),
    )

    try:
        _ssh_start_master(ssh_args=ssh_args, target=target, env=run_env)

        existing_static = _fetch_static_leases_from_router(
            ssh_args=ssh_args,
            target=target,
            env=run_env,
        )

        dhcp_server_by_subnet = _fetch_dhcp_server_by_subnet_from_router(
            ssh_args=ssh_args,
            target=target,
            env=run_env,
        )

        # User config overrides router-discovered mapping.
        dhcp_server_by_subnet.update(dict(dhcp_server_by_subnet_override))

        commands = _generate_commands(
            desired=desired_leases,
            existing_static=existing_static,
            dhcp_server_by_subnet=dict(dhcp_server_by_subnet),
        )

        ops = _plan_operations(
            desired=desired_leases,
            existing_static=existing_static,
            dhcp_server_by_subnet=dict(dhcp_server_by_subnet),
            debug=bool(args.debug),
        )

        if args.apply:
            if not ops:
                print("No changes to apply")
                return 0
            if not args.yes:
                _confirm_apply(commands=commands, op_count=len(ops))

            _apply_operations_to_router(
                ssh_args=ssh_args,
                target=target,
                ops=ops,
                env=run_env,
            )

            safe_host = "".join([c if (c.isalnum() or c in "-_.") else "_" for c in mikrotik_host])
            timestamp = _dt.datetime.now(tz=_dt.timezone.utc).strftime("%Y%m%dT%H%M%SZ")
            export_base = f"router-export-{safe_host}-{timestamp}"

            remote_filename = _export_router_config_via_ssh_to_file(
                ssh_args=ssh_args,
                target=target,
                export_base_name=export_base,
                env=run_env,
            )
            backup_dir = resolve_path_relative_to_config(config_path, args.backup_dir)
            backup_path = backup_dir / remote_filename
            _download_remote_file_via_scp(
                scp_args=scp_args,
                target=target,
                remote_filename=remote_filename,
                local_path=backup_path,
                env=run_env,
            )
            _remove_remote_file(
                ssh_args=ssh_args,
                target=target,
                remote_filename=remote_filename,
                env=run_env,
            )
            print(f"Wrote router export backup: {backup_path}")
    finally:
        _ssh_stop_master(ssh_args=ssh_args, target=target, env=run_env)

    output_path = resolve_path_relative_to_config(config_path, args.output)
    if args.stdout:
        print("\n".join(commands))
    else:
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text("\n".join(commands) + "\n", encoding="utf-8")
        print(f"Wrote {len(commands)} lines to {output_path}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
