from __future__ import annotations

import argparse
import curses
import datetime as _dt
import io
import logging
import os
import re
import secrets
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import pandas as pd
import requests

from .config import (
    DEFAULT_SHEET_URL,
    get_config_value,
    get_table,
    load_toml_or_exit,
    pre_parse_config,
    resolve_path_relative_to_config,
)
from .logging_utils import configure_logging
from .mikrotik_utils import mikrotik_quote, sanitize_filename_component
from .sheets import (
    as_str,
    build_sheet_url,
    df_with_normalized_columns,
    normalize_column_name,
    normalize_ip,
)

logger = logging.getLogger(__name__)

COMMENT_MARKER = "generated by python -m homelab mikrotik"
ADDRESS_LIST_CADDY_HOSTS = "hlb-caddy-hosts"
ADDRESS_LIST_BACKEND_PREFIX = "hlb-backend"
DHCP_MAC_PREFIX = "BC:24:11"


def _backend_group_list_name(protocol: str, backend_port: int) -> str:
    return f"{ADDRESS_LIST_BACKEND_PREFIX}-{protocol}-{backend_port}"


def _generate_random_mac(prefix: str = DHCP_MAC_PREFIX) -> str:
    prefix_upper = prefix.strip().upper()
    random_hex = secrets.token_hex(3).upper()
    suffix = ":".join(random_hex[i:i + 2] for i in range(0, 6, 2))
    return f"{prefix_upper}:{suffix}"


def _load_sheet_df(
    *,
    sheet_url: str,
    gid: int,
    timeout_seconds: float,
    label: str,
) -> pd.DataFrame:
    url = build_sheet_url(sheet_url, int(gid))
    print(f"Loading {label} sheet data...", file=sys.stderr, flush=True)

    response = requests.get(url, timeout=timeout_seconds)
    response.raise_for_status()
    return df_with_normalized_columns(pd.read_csv(io.StringIO(response.text)))


def _has_interactive_tty() -> bool:
    term = os.environ.get("TERM", "").strip().lower()
    return sys.stdin.isatty() and sys.stdout.isatty() and term not in {"", "dumb"}


@dataclass
class ServiceFormData:
    service_key: str = ""
    service_name: str = ""
    hostname: str = ""
    protocol: str = "tcp"
    ingress: str = "dstnat"
    exposure: str = "public"
    frontend_ports: str = ""
    backend_ports: str = ""
    backend_ip: str = ""
    source_ip: str = ""
    source_address_list: str = ""
    source_vlan: str = ""
    destination_vlan: str = ""
    destination_address_list: str = ""
    enable_nat: str = "yes"
    enable_filter: str = "yes"
    enable_dhcp: str = "no"
    dhcp_mac: str = ""
    dhcp_address: str = ""
    dhcp_subnet: str = ""


@dataclass
class ParsedInput:
    service_name: str
    hostname: str
    ingress: str
    protocol: str
    frontend_ports: list[int]
    backend_ports: list[int]
    backend_ip: str | None
    caddy_ip: str | None
    source_ip: str | None
    source_address_list: str | None
    in_interface: str | None
    in_interface_list: str | None
    out_interface: str | None
    dst_address_list: str | None
    enable_nat: bool
    enable_filter: bool
    enable_dhcp: bool
    dhcp_mac: str | None
    dhcp_address: str | None
    dhcp_subnet: str | None


def _to_bool(value: str) -> bool:
    return value.strip().lower() in {"1", "y", "yes", "true", "on"}


def _parse_vlan_map(config: dict[str, Any]) -> dict[str, dict[str, str]]:
    fw_cfg = get_table(config, "mikrotik") or get_table(config, "firewall")

    raw = fw_cfg.get("vlans", {})
    if not isinstance(raw, dict):
        return {}
    return {k.lower(): dict(v) for k, v in raw.items() if isinstance(v, dict)}


def _normalize_ports_lenient(value: Any) -> list[int]:
    if value is None:
        return []

    if isinstance(value, list):
        ports: list[int] = []
        for item in value:
            ports.extend(_normalize_ports_lenient(item))
        return ports

    if isinstance(value, (int, float)):
        try:
            parsed = int(float(value))
        except (TypeError, ValueError):
            return []
        return [parsed] if 1 <= parsed <= 65535 else []

    if isinstance(value, str):
        cleaned = value.strip()
        if not cleaned:
            return []
        parts = re.split(r"[\s,;/]+", cleaned)
        ports: list[int] = []
        for part in parts:
            token = part.strip()
            if not token:
                continue
            try:
                parsed = int(float(token))
            except ValueError:
                continue
            if 1 <= parsed <= 65535:
                ports.append(parsed)
        return ports

    return []


def _ports_to_form_value(value: Any) -> str:
    ports = _normalize_ports_lenient(value)
    return ",".join(str(port) for port in ports)


def _load_helpers_values(
    *,
    sheet_url: str,
    helpers_gid: int,
    timeout_seconds: float,
) -> dict[str, list[str]]:
    df = _load_sheet_df(
        sheet_url=sheet_url,
        gid=int(helpers_gid),
        timeout_seconds=timeout_seconds,
        label="Helpers",
    )

    values_by_column: dict[str, list[str]] = {}
    for column in df.columns:
        seen: set[str] = set()
        values: list[str] = []
        for raw in df[column]:
            value = as_str(raw)
            if not value:
                continue
            key = value.casefold()
            if key in seen:
                continue
            seen.add(key)
            values.append(value)
        values_by_column[column] = values

    return values_by_column


def _build_selection_options(
    *,
    helpers_values: dict[str, list[str]],
    vlan_map: dict[str, dict[str, str]],
) -> dict[str, list[str]]:
    helper_protocols = [value.lower() for value in helpers_values.get("protocols", []) if value.strip()]
    if not helper_protocols:
        raise ValueError("Helpers tab is missing required values for the 'Protocols' column.")

    helper_address_lists = [value for value in helpers_values.get("address_lists", []) if value.strip()]
    vlan_options = sorted(vlan_map.keys(), key=str.casefold)

    return {
        "protocol": helper_protocols,
        "ingress": ["dstnat", "direct", "caddy"],
        "exposure": ["public", "non-public"],
        "source_vlan": ["", *vlan_options],
        "destination_vlan": ["", *vlan_options],
        "source_address_list": ["", *helper_address_lists],
        "destination_address_list": ["", *helper_address_lists],
        "enable_nat": ["yes", "no"],
        "enable_filter": ["yes", "no"],
        "enable_dhcp": ["yes", "no"],
    }


def _normalized_service_filename(service_name: str) -> str:
    raw = service_name.strip().lower()
    if not raw:
        return "service"
    normalized = re.sub(r"[^a-z0-9._-]+", "-", raw)
    normalized = normalized.strip("-_.")
    safe = sanitize_filename_component(normalized)
    return safe or "service"


def _prefill_from_services_sheet(
    *,
    sheet_url: str,
    services_gid: int,
    timeout_seconds: float,
    service_key: str,
) -> dict[str, str | Any]:
    matches = _prefill_candidates_from_services_sheet(
        sheet_url=sheet_url,
        services_gid=services_gid,
        timeout_seconds=timeout_seconds,
        service_key=service_key,
    )
    return matches[0] if matches else {}


def _prefill_candidates_from_services_sheet(
    *,
    sheet_url: str,
    services_gid: int,
    timeout_seconds: float,
    service_key: str,
) -> list[dict[str, str | Any]]:
    service_key = service_key.strip().lower()
    if not service_key:
        return []

    df = _load_sheet_df(
        sheet_url=sheet_url,
        gid=int(services_gid),
        timeout_seconds=timeout_seconds,
        label="Services",
    )

    matches: list[dict[str, str | Any]] = []
    for _, row in df.iterrows():
        candidates = [
            as_str(row.get("service_name")),
            as_str(row.get("frontend_hostname")),
            as_str(row.get("hostname")),
        ]
        if service_key not in {c.lower() for c in candidates if c}:
            continue

        matches.append(
            {
                "service_name": as_str(row.get("service_name")),
                "frontend_hostname": as_str(row.get("frontend_hostname")),
                "hostname": as_str(row.get("hostname")),
                "protocol": as_str(row.get("protocol")).lower() or "tcp",
                "ingress": as_str(row.get("ingress")).lower() or "dstnat",
                "exposure": as_str(row.get("exposure")).lower() or "public",
                "frontend_ports": _ports_to_form_value(row.get("frontend_port")),
                "backend_ports": _ports_to_form_value(row.get("backend_port")),
                "backend_ip": as_str(row.get("ip_address")),
                "source_ip": as_str(row.get("source_ip")),
                "source_address_list": as_str(row.get("source_address_list")),
                "source_vlan": as_str(row.get("source_vlan")) or as_str(row.get("source_vlans")),
                "destination_vlan": as_str(row.get("destination_vlan")),
                "destination_address_list": as_str(row.get("destination_address_list")),
            }
        )

    return matches


def _prompt_select_service_by_name(
    *,
    service_key: str,
    matches: list[dict[str, str | Any]],
) -> dict[str, str | Any]:
    if not matches:
        return {}
    if len(matches) == 1:
        return matches[0]

    print(
        f"Multiple Services rows found for frontend hostname '{service_key}'.",
        file=sys.stderr,
    )
    print("Select the desired Service Name:", file=sys.stderr)

    for idx, match in enumerate(matches, start=1):
        service_name = str(match.get("service_name") or "").strip() or "(empty Service Name)"
        print(f"  [{idx}] {service_name}", file=sys.stderr)

    while True:
        print(f"Enter choice [1-{len(matches)}]: ", end="", file=sys.stderr, flush=True)
        choice = input().strip()
        if choice.isdigit():
            selected = int(choice)
            if 1 <= selected <= len(matches):
                return matches[selected - 1]
        print("Invalid choice. Try again.", file=sys.stderr)


def _list_services_from_sheet(*, sheet_url: str, services_gid: int, timeout_seconds: float) -> list[str]:
    df = _load_sheet_df(
        sheet_url=sheet_url,
        gid=int(services_gid),
        timeout_seconds=timeout_seconds,
        label="Services",
    )

    seen: set[str] = set()
    services: list[str] = []

    for _, row in df.iterrows():
        candidates = [
            as_str(row.get("service_name")),
            as_str(row.get("frontend_hostname")),
            as_str(row.get("hostname")),
        ]
        chosen = ""
        for candidate in candidates:
            if candidate:
                chosen = candidate
                break
        if not chosen:
            continue

        key = chosen.lower()
        if key in seen:
            continue
        seen.add(key)
        services.append(chosen)

    return sorted(services, key=str.casefold)


def _prefill_from_nodes_sheet(
    *,
    sheet_url: str,
    nodes_gid: int,
    timeout_seconds: float,
    hostname: str,
    lease_type_column: str,
    ip_column: str,
    subnet_column: str,
    mac_column: str,
) -> dict[str, str]:
    target = hostname.strip().lower()
    if not target:
        return {}

    df = _load_sheet_df(
        sheet_url=sheet_url,
        gid=int(nodes_gid),
        timeout_seconds=timeout_seconds,
        label="Nodes",
    )
    for _, row in df.iterrows():
        node_name = as_str(row.get("hostname")).lower()
        dns_name = as_str(row.get("dns_name")).lower()
        if target not in {node_name, dns_name}:
            continue

        lease_type = as_str(row.get(lease_type_column)).strip().lower()
        enable_dhcp = "yes" if lease_type == "dhcp" else "no"

        return {
            "backend_ip": as_str(row.get(ip_column)),
            "dhcp_mac": as_str(row.get(mac_column)),
            "dhcp_address": as_str(row.get(ip_column)),
            "dhcp_subnet": as_str(row.get(subnet_column)),
            "enable_dhcp": enable_dhcp,
        }

    return {}


def _list_node_hostnames_from_nodes_sheet(
    *,
    sheet_url: str,
    nodes_gid: int,
    timeout_seconds: float,
) -> list[str]:
    df = _load_sheet_df(
        sheet_url=sheet_url,
        gid=int(nodes_gid),
        timeout_seconds=timeout_seconds,
        label="Nodes",
    )

    seen: set[str] = set()
    options: list[str] = []
    for _, row in df.iterrows():
        hostname = as_str(row.get("hostname"))
        if not hostname:
            continue
        key = hostname.casefold()
        if key in seen:
            continue
        seen.add(key)
        options.append(hostname)

    return sorted(options, key=str.casefold)


def _run_single_input_prompt(initial_service_key: str) -> str:
    prompt = "Service key (service_name/frontend_hostname/hostname): "

    def _inner(stdscr: Any) -> str:
        curses.curs_set(1)
        stdscr.clear()
        stdscr.addstr(0, 0, "MikroTik single-service generator")
        stdscr.addstr(2, 0, prompt)
        stdscr.addstr(3, 0, "Type service key and press Enter")
        stdscr.refresh()

        buf = list(initial_service_key)
        stdscr.addstr(2, len(prompt), "".join(buf))
        pos = len(buf)
        while True:
            ch = stdscr.getch()
            if ch in {10, 13}:
                return "".join(buf).strip()
            if ch in {curses.KEY_BACKSPACE, 127, 8}:
                if pos > 0:
                    pos -= 1
                    del buf[pos]
            elif 32 <= ch <= 126:
                buf.insert(pos, chr(ch))
                pos += 1
            stdscr.move(2, len(prompt))
            stdscr.clrtoeol()
            stdscr.addstr(2, len(prompt), "".join(buf))
            stdscr.refresh()

    return curses.wrapper(_inner)


def _run_service_selection_menu(*, services: list[str]) -> str:
    options = [*services, "New..."]

    def _inner(stdscr: Any) -> str:
        curses.curs_set(0)
        selected_idx = 0
        scroll = 0

        while True:
            stdscr.clear()
            height, width = stdscr.getmaxyx()
            stdscr.addstr(0, 0, "MikroTik single-service generator")
            stdscr.addstr(1, 0, "Select service from Services sheet (Enter)")
            stdscr.addstr(2, 0, "Use ↑/↓ to navigate")

            visible_rows = max(1, height - 5)
            if selected_idx < scroll:
                scroll = selected_idx
            if selected_idx >= scroll + visible_rows:
                scroll = selected_idx - visible_rows + 1

            for row_idx in range(visible_rows):
                option_idx = scroll + row_idx
                if option_idx >= len(options):
                    break
                option = options[option_idx]
                prefix = ">" if option_idx == selected_idx else " "
                text = f"{prefix} {option}"
                stdscr.addstr(4 + row_idx, 0, text[: max(1, width - 1)])

            ch = stdscr.getch()
            if ch == curses.KEY_UP:
                selected_idx = (selected_idx - 1) % len(options)
                continue
            if ch == curses.KEY_DOWN:
                selected_idx = (selected_idx + 1) % len(options)
                continue
            if ch in {10, 13}:
                return options[selected_idx]

    return curses.wrapper(_inner)


def _run_option_selection(
    stdscr: Any,
    *,
    title: str,
    options: list[str],
    current_value: str,
) -> str:
    if not options:
        return current_value

    choice_options = list(options)
    if current_value not in choice_options:
        choice_options.append(current_value)

    selected_idx = 0
    for i, item in enumerate(choice_options):
        if item == current_value:
            selected_idx = i
            break

    scroll = 0
    while True:
        stdscr.clear()
        height, width = stdscr.getmaxyx()
        stdscr.addstr(0, 0, f"Select value: {title}")
        stdscr.addstr(1, 0, "Use ↑/↓ to navigate, Enter to choose")

        visible_rows = max(1, height - 4)
        if selected_idx < scroll:
            scroll = selected_idx
        if selected_idx >= scroll + visible_rows:
            scroll = selected_idx - visible_rows + 1

        for row_idx in range(visible_rows):
            option_idx = scroll + row_idx
            if option_idx >= len(choice_options):
                break
            option = choice_options[option_idx]
            label = option if option else "(none)"
            prefix = ">" if option_idx == selected_idx else " "
            stdscr.addstr(3 + row_idx, 0, f"{prefix} {label}"[: max(1, width - 1)])

        ch = stdscr.getch()
        if ch == curses.KEY_UP:
            selected_idx = (selected_idx - 1) % len(choice_options)
            continue
        if ch == curses.KEY_DOWN:
            selected_idx = (selected_idx + 1) % len(choice_options)
            continue
        if ch in {10, 13}:
            return choice_options[selected_idx]


def _run_form_ui(
    form_data: ServiceFormData,
    title: str,
    selection_options: dict[str, list[str]],
) -> ServiceFormData:
    fields: list[tuple[str, str]] = [
        ("service_name", "Service name"),
        ("hostname", "Backend hostname (Nodes tab)"),
        ("protocol", "Protocol (tcp/udp)"),
        ("ingress", "Ingress (dstnat/direct/caddy)"),
        ("exposure", "Exposure (public/non-public)"),
        ("frontend_ports", "Frontend ports (csv)"),
        ("backend_ports", "Backend ports (csv)"),
        ("backend_ip", "Backend IP"),
        ("source_ip", "Source IP (optional)"),
        ("source_address_list", "Source address-list (optional)"),
        ("source_vlan", "Source VLAN (optional)"),
        ("destination_vlan", "Destination VLAN (optional)"),
        ("destination_address_list", "Destination address-list (optional)"),
        ("enable_nat", "Generate NAT? (yes/no)"),
        ("enable_filter", "Generate filter? (yes/no)"),
        ("enable_dhcp", "Generate DHCP lease? (yes/no)"),
        ("dhcp_mac", "DHCP MAC (if enabled)"),
        ("dhcp_address", "DHCP IP address (if enabled)"),
        ("dhcp_subnet", "DHCP subnet (optional)"),
    ]

    def _inner(stdscr: Any) -> ServiceFormData:
        curses.curs_set(0)
        idx = 0
        while True:
            stdscr.clear()
            stdscr.addstr(0, 0, title)
            stdscr.addstr(1, 0, "Use ↑/↓ to select, Enter to edit, F2 to continue")

            row = 3
            for i, (key, label) in enumerate(fields):
                value = getattr(form_data, key)
                prefix = ">" if i == idx else " "
                stdscr.addstr(row + i, 0, f"{prefix} {label}: {value}")

            ch = stdscr.getch()
            if ch == curses.KEY_UP:
                idx = (idx - 1) % len(fields)
                continue
            if ch == curses.KEY_DOWN:
                idx = (idx + 1) % len(fields)
                continue
            if ch == curses.KEY_F2:
                return form_data
            if ch in {10, 13}:
                key, label = fields[idx]
                current = str(getattr(form_data, key))
                options = selection_options.get(key)
                if options is not None:
                    selected = _run_option_selection(
                        stdscr,
                        title=label,
                        options=options,
                        current_value=current,
                    )
                    setattr(form_data, key, selected.strip())
                    continue

                curses.curs_set(1)
                stdscr.clear()
                stdscr.addstr(0, 0, f"Edit: {label}")
                stdscr.addstr(1, 0, "Enter value and press Enter")
                stdscr.addstr(3, 0, current)
                stdscr.refresh()
                buf = list(current)
                pos = len(buf)
                while True:
                    keypress = stdscr.getch()
                    if keypress in {10, 13}:
                        setattr(form_data, key, "".join(buf).strip())
                        break
                    if keypress in {curses.KEY_BACKSPACE, 127, 8}:
                        if pos > 0:
                            pos -= 1
                            del buf[pos]
                    elif 32 <= keypress <= 126:
                        buf.insert(pos, chr(keypress))
                        pos += 1
                    stdscr.move(3, 0)
                    stdscr.clrtoeol()
                    stdscr.addstr(3, 0, "".join(buf))
                    stdscr.refresh()
                curses.curs_set(0)

    return curses.wrapper(_inner)


def _run_confirmation_ui(form_data: ServiceFormData) -> bool:
    lines = [
        "Review configuration before generation",
        "Press y to confirm, n to cancel",
        "",
    ]

    for key in [
        "service_name",
        "hostname",
        "protocol",
        "ingress",
        "exposure",
        "frontend_ports",
        "backend_ports",
        "backend_ip",
        "source_ip",
        "source_address_list",
        "source_vlan",
        "destination_vlan",
        "destination_address_list",
        "enable_nat",
        "enable_filter",
        "enable_dhcp",
        "dhcp_mac",
        "dhcp_address",
        "dhcp_subnet",
    ]:
        lines.append(f"- {key}: {getattr(form_data, key)}")

    def _inner(stdscr: Any) -> bool:
        curses.curs_set(0)
        while True:
            stdscr.clear()
            for i, line in enumerate(lines):
                stdscr.addstr(i, 0, line)
            ch = stdscr.getch()
            if ch in {ord('y'), ord('Y')}:
                return True
            if ch in {ord('n'), ord('N')}:
                return False

    return curses.wrapper(_inner)


def _normalize_form(
    form_data: ServiceFormData,
    vlan_map: dict[str, dict[str, str]],
    *,
    caddy_ip: str,
) -> ParsedInput:
    source_vlan = form_data.source_vlan.strip().lower()
    destination_vlan = form_data.destination_vlan.strip().lower()

    source_cfg = vlan_map.get(source_vlan, {}) if source_vlan else {}
    destination_cfg = vlan_map.get(destination_vlan, {}) if destination_vlan else {}

    protocol = form_data.protocol.strip().lower()
    if protocol not in {"tcp", "udp"}:
        protocol = "tcp"

    ingress = form_data.ingress.strip().lower()
    if ingress not in {"dstnat", "direct", "caddy"}:
        ingress = "dstnat"

    backend_ip = normalize_ip(form_data.backend_ip)
    caddy_ip_normalized = normalize_ip(caddy_ip)

    return ParsedInput(
        service_name=form_data.service_name.strip() or form_data.service_key.strip() or "service",
        hostname=form_data.hostname.strip(),
        ingress=ingress,
        protocol=protocol,
        frontend_ports=_normalize_ports_lenient(form_data.frontend_ports),
        backend_ports=_normalize_ports_lenient(form_data.backend_ports),
        backend_ip=backend_ip,
        caddy_ip=caddy_ip_normalized,
        source_ip=normalize_ip(form_data.source_ip),
        source_address_list=form_data.source_address_list.strip() or None,
        in_interface=source_cfg.get("interface") or None,
        in_interface_list=source_cfg.get("interface_list") or None,
        out_interface=destination_cfg.get("interface") or None,
        dst_address_list=(
            form_data.destination_address_list.strip() or destination_cfg.get("address_list") or None
        ),
        enable_nat=_to_bool(form_data.enable_nat),
        enable_filter=_to_bool(form_data.enable_filter),
        enable_dhcp=_to_bool(form_data.enable_dhcp),
        dhcp_mac=form_data.dhcp_mac.strip() or None,
        dhcp_address=normalize_ip(form_data.dhcp_address),
        dhcp_subnet=form_data.dhcp_subnet.strip() or None,
    )


def _port_mappings(frontend_ports: list[int], backend_ports: list[int]) -> list[tuple[int, int]]:
    if not frontend_ports:
        return []
    if not backend_ports:
        return [(p, p) for p in frontend_ports]
    if len(backend_ports) == 1:
        return [(p, backend_ports[0]) for p in frontend_ports]
    if len(backend_ports) == len(frontend_ports):
        return list(zip(frontend_ports, backend_ports))
    return []


def _render_commands(parsed: ParsedInput) -> list[str]:
    commands: list[str] = []
    label = parsed.service_name

    mappings = _port_mappings(parsed.frontend_ports, parsed.backend_ports)
    backend_ports_for_lists: set[int] = set()
    for _, backend_port in mappings:
        if backend_port > 0:
            backend_ports_for_lists.add(int(backend_port))
    if not backend_ports_for_lists and parsed.backend_ports:
        for backend_port in parsed.backend_ports:
            if backend_port > 0:
                backend_ports_for_lists.add(int(backend_port))

    if parsed.ingress == "caddy" and parsed.caddy_ip:
        comment = f"{COMMENT_MARKER}; single-service address-list; caddy-hosts; {label}"
        commands.append(
            "/ip firewall address-list add "
            f"list={ADDRESS_LIST_CADDY_HOSTS} address={parsed.caddy_ip} "
            f"comment={mikrotik_quote(comment)}"
        )

    if parsed.backend_ip:
        for backend_port in sorted(backend_ports_for_lists):
            list_name = _backend_group_list_name(parsed.protocol, backend_port)
            comment = (
                f"{COMMENT_MARKER}; single-service address-list; backend-group; "
                f"{parsed.protocol}:{backend_port}; {label}"
            )
            commands.append(
                "/ip firewall address-list add "
                f"list={list_name} address={parsed.backend_ip} "
                f"comment={mikrotik_quote(comment)}"
            )

    nat_target_ip = parsed.caddy_ip if parsed.ingress == "caddy" and parsed.caddy_ip else parsed.backend_ip

    if parsed.enable_nat and nat_target_ip and mappings:
        for frontend_port, backend_port in mappings:
            comment = (
                f"{COMMENT_MARKER}; single-service nat; {label}; "
                f"{parsed.protocol}:{frontend_port}->{nat_target_ip}:{backend_port}"
            )
            commands.append(
                "/ip firewall nat add chain=dstnat action=dst-nat "
                f"in-interface-list=WAN protocol={parsed.protocol} dst-port={frontend_port} "
                f"to-addresses={nat_target_ip} to-ports={backend_port} "
                f"comment={mikrotik_quote(comment)}"
            )

    if parsed.enable_filter and parsed.backend_ip:
        for _, backend_port in mappings or [(0, parsed.backend_ports[0] if parsed.backend_ports else 0)]:
            if backend_port <= 0:
                continue
            backend_list = _backend_group_list_name(parsed.protocol, int(backend_port))
            parts = [
                "/ip firewall filter add chain=forward action=accept",
                f"protocol={parsed.protocol}",
                f"dst-port={backend_port}",
                f"dst-address-list={backend_list}",
            ]
            if parsed.source_ip:
                parts.append(f"src-address={parsed.source_ip}")
            if parsed.source_address_list:
                parts.append(f"src-address-list={parsed.source_address_list}")
            elif parsed.ingress == "caddy":
                parts.append(f"src-address-list={ADDRESS_LIST_CADDY_HOSTS}")
            if parsed.in_interface:
                parts.append(f"in-interface={parsed.in_interface}")
            if parsed.in_interface_list:
                parts.append(f"in-interface-list={parsed.in_interface_list}")
            if parsed.out_interface:
                parts.append(f"out-interface={parsed.out_interface}")
            if parsed.dst_address_list:
                parts.append(f"dst-address-list={parsed.dst_address_list}")

            comment = (
                f"{COMMENT_MARKER}; single-service filter; {label}; "
                f"{parsed.protocol}:{backend_port}->{parsed.backend_ip}"
            )
            parts.append(f"comment={mikrotik_quote(comment)}")
            commands.append(" ".join(parts))

    if parsed.enable_dhcp and parsed.dhcp_mac and parsed.dhcp_address:
        comment = f"{COMMENT_MARKER}; single-service dhcp; {label}"
        commands.append(
            "/ip dhcp-server lease add "
            f"mac-address={parsed.dhcp_mac} address={parsed.dhcp_address} "
            f"comment={mikrotik_quote(comment)}"
        )

    return commands


def _build_parser(argv: list[str] | None = None) -> argparse.Namespace:
    tool_dir = Path(__file__).resolve().parent / "mikrotik"
    config_path, config = pre_parse_config(argv)

    globals_cfg = get_table(config, "globals")
    fw_cfg = get_table(config, "mikrotik") or get_table(config, "firewall")

    parser = argparse.ArgumentParser(
        prog="python -m homelab mikrotik",
        description=(
            "Prompt-driven single-service MikroTik generator. Loads defaults from config and "
            "Google Sheets, opens a curses form, then shows a curses confirmation screen before "
            "printing/writing RouterOS commands."
        ),
    )
    parser.add_argument("--config", type=Path, default=config_path)
    parser.add_argument(
        "--sheet-url",
        default=str(get_config_value(globals_cfg, "sheet_url", DEFAULT_SHEET_URL)).strip(),
    )
    parser.add_argument(
        "--services-gid",
        type=int,
        default=int(get_config_value(globals_cfg, "services_gid", get_config_value(fw_cfg, "caddy_gid", 0))),
    )
    parser.add_argument(
        "--nodes-gid",
        type=int,
        default=int(get_config_value(globals_cfg, "nodes_gid", 344016240)),
    )
    parser.add_argument(
        "--helpers-gid",
        type=int,
        default=int(get_config_value(globals_cfg, "helpers_gid", 0)),
        help="GID for Helpers sheet (required for selection options)",
    )
    parser.add_argument(
        "--sheet-timeout",
        type=float,
        default=float(get_config_value(globals_cfg, "sheet_timeout_seconds", 10)),
        help="Timeout in seconds for downloading Google Sheet CSV data",
    )
    caddy_ip_default = str(get_config_value(globals_cfg, "caddy_ip", "")).strip()
    fw_caddy_ips = get_config_value(fw_cfg, "caddy_ips", [])
    if not caddy_ip_default and isinstance(fw_caddy_ips, list) and fw_caddy_ips:
        caddy_ip_default = str(fw_caddy_ips[0]).strip()
    parser.add_argument(
        "--caddy-ip",
        default=caddy_ip_default,
        help="Caddy proxy IP used when ingress=caddy",
    )
    parser.add_argument("--service", default="", help="Optional service key to pre-select")
    parser.add_argument(
        "--no-prompt",
        action="store_true",
        help="Skip interactive UI and generate directly from sheet-derived values (requires --service)",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path(
            str(get_config_value(fw_cfg, "output", str(tool_dir / "mikrotik-single-service.rsc")))
        ),
        help="Directory where per-service .rsc files are written",
    )
    parser.add_argument("--stdout", action="store_true", help="Also print generated commands to stdout")
    parser.add_argument("--debug", action="store_true", default=False)
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = _build_parser(argv)
    configure_logging(debug=bool(args.debug))

    if not args.no_prompt and not _has_interactive_tty():
        print(
            "Error: interactive terminal required for curses UI (stdin/stdout must be a TTY).",
            file=sys.stderr,
        )
        return 2

    config = load_toml_or_exit(Path(args.config).expanduser().resolve())
    vlan_map = _parse_vlan_map(config)

    lease_cfg = get_table(config, "mikrotik") or get_table(config, "dhcp_leases")

    lease_type_column = normalize_column_name(str(get_config_value(lease_cfg, "lease_type_column", "Static/DHCP")))
    ip_column = normalize_column_name(str(get_config_value(lease_cfg, "ip_column", "IP Address")))
    subnet_column = normalize_column_name(str(get_config_value(lease_cfg, "subnet_column", "Subnet")))
    mac_column = normalize_column_name(str(get_config_value(lease_cfg, "mac_column", "MAC Address")))

    selection_options: dict[str, list[str]] = {}
    if not args.no_prompt:
        if int(args.helpers_gid) <= 0:
            print("Error: --helpers-gid is required and must be > 0.", file=sys.stderr)
            return 2

        try:
            helpers_values = _load_helpers_values(
                sheet_url=str(args.sheet_url),
                helpers_gid=int(args.helpers_gid),
                timeout_seconds=float(args.sheet_timeout),
            )
            selection_options = _build_selection_options(
                helpers_values=helpers_values,
                vlan_map=vlan_map,
            )
        except Exception as exc:
            print(f"Error: unable to load Helpers sheet values: {exc}", file=sys.stderr)
            return 1

        try:
            node_hostname_options = _list_node_hostnames_from_nodes_sheet(
                sheet_url=str(args.sheet_url),
                nodes_gid=int(args.nodes_gid),
                timeout_seconds=float(args.sheet_timeout),
            )
            if node_hostname_options:
                selection_options["hostname"] = node_hostname_options
        except Exception as exc:
            logger.warning("Unable to load Nodes sheet hostname options: %s", exc)

    service_key = str(args.service or "").strip()
    selection_source = "--service"
    if args.no_prompt and not service_key:
        print("Error: --no-prompt requires --service.", file=sys.stderr)
        return 2

    if not service_key:
        service_options: list[str] = []
        try:
            service_options = _list_services_from_sheet(
                sheet_url=str(args.sheet_url),
                services_gid=int(args.services_gid),
                timeout_seconds=float(args.sheet_timeout),
            )
        except Exception as exc:
            logger.warning("Unable to load Services sheet for menu: %s", exc)

        if service_options:
            selection = _run_service_selection_menu(services=service_options)
            if selection == "New...":
                service_key = _run_single_input_prompt("")
                selection_source = "new"
            else:
                service_key = selection
                selection_source = "sheet"
        else:
            service_key = _run_single_input_prompt("")
            selection_source = "new"

    if not service_key:
        print("Error: service key is required", file=sys.stderr)
        return 2

    prefill: dict[str, str | Any] = {}
    try:
        service_matches = _prefill_candidates_from_services_sheet(
            sheet_url=str(args.sheet_url),
            services_gid=int(args.services_gid),
            timeout_seconds=float(args.sheet_timeout),
            service_key=service_key,
        )

        if args.no_prompt:
            target = service_key.strip().lower()
            frontend_matches = [
                match
                for match in service_matches
                if str(match.get("frontend_hostname") or "").strip().lower() == target
            ]
            if len(frontend_matches) > 1:
                if not sys.stdin.isatty():
                    print(
                        (
                            f"Error: multiple services found for frontend hostname '{service_key}' "
                            "and stdin is not interactive to select one."
                        ),
                        file=sys.stderr,
                    )
                    return 1
                prefill = _prompt_select_service_by_name(
                    service_key=service_key,
                    matches=frontend_matches,
                )
            elif len(frontend_matches) == 1:
                prefill = frontend_matches[0]
            elif service_matches:
                prefill = service_matches[0]
        elif service_matches:
            prefill = service_matches[0]
    except Exception as exc:
        logger.warning("Unable to load services sheet prefill: %s", exc)

    if args.no_prompt and not prefill:
        print(
            f"Error: service '{service_key}' not found in Services sheet (required for --no-prompt).",
            file=sys.stderr,
        )
        return 1

    form = ServiceFormData(service_key=service_key)

    for key, value in prefill.items():
        if hasattr(form, key) and value:
            setattr(form, key, value)

    try:
        nodes_prefill = _prefill_from_nodes_sheet(
            sheet_url=str(args.sheet_url),
            nodes_gid=int(args.nodes_gid),
            timeout_seconds=float(args.sheet_timeout),
            hostname=form.hostname,
            lease_type_column=lease_type_column,
            ip_column=ip_column,
            subnet_column=subnet_column,
            mac_column=mac_column,
        )
        for key, value in nodes_prefill.items():
            if hasattr(form, key) and value:
                setattr(form, key, value)
    except Exception as exc:
        logger.warning("Unable to load nodes sheet prefill: %s", exc)

    if not args.no_prompt:
        form = _run_form_ui(
            form,
            title=f"MikroTik single-service form ({service_key}) [source: {selection_source}]",
            selection_options=selection_options,
        )
        confirmed = _run_confirmation_ui(form)
        if not confirmed:
            print("Aborted")
            return 130

    parsed = _normalize_form(
        form,
        vlan_map,
        caddy_ip=str(args.caddy_ip),
    )

    if parsed.enable_dhcp and parsed.dhcp_address and not parsed.dhcp_mac:
        parsed.dhcp_mac = _generate_random_mac()
        print(
            f"DHCP MAC not provided; generated random MAC {parsed.dhcp_mac}",
            file=sys.stderr,
        )

    commands = _render_commands(parsed)

    if not commands:
        print("No commands generated (check enabled sections and required fields).", file=sys.stderr)
        return 1

    timestamp = _dt.datetime.now(_dt.UTC).strftime("%Y-%m-%dT%H:%M:%SZ")
    lines = [
        f"# {COMMENT_MARKER}",
        f"# generated_at={timestamp}",
        f"# service={parsed.service_name}",
        "# address-list convention:",
        f"#   caddy hosts: {ADDRESS_LIST_CADDY_HOSTS}",
        f"#   backend groups: {ADDRESS_LIST_BACKEND_PREFIX}-<protocol>-<backend_port>",
        "# onboarding guidance:",
        "#   add/maintain caddy nodes:",
        (
            f"#     /ip firewall address-list add list={ADDRESS_LIST_CADDY_HOSTS} "
            'address=<CADDY_IP> comment="manual caddy node"'
        ),
        "#   add/maintain backend services:",
        (
            f"#     /ip firewall address-list add "
            f"list={ADDRESS_LIST_BACKEND_PREFIX}-<protocol>-<backend_port> "
            'address=<SERVICE_IP> comment="manual backend service"'
        ),
        "",
        *commands,
        "",
    ]
    content = "\n".join(lines)

    output_base = resolve_path_relative_to_config(
        Path(args.config).expanduser().resolve(),
        Path(args.output),
    )
    output_dir = output_base.parent if output_base.suffix else output_base
    output_filename = f"{_normalized_service_filename(parsed.service_name)}.rsc"
    output_path = output_dir / output_filename
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content, encoding="utf-8")
    print(f"Wrote {output_path}")

    if args.stdout:
        print(content)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
