#!/usr/bin/env python3

import argparse
import datetime as _dt
import ipaddress
import logging
import shlex
import sys
from dataclasses import dataclass
from pathlib import Path

import pandas as pd

from .config import (
    DEFAULT_SHEET_URL,
    get_config_value,
    get_table,
    is_unified_mikrotik_config,
    load_toml_or_exit,
    pre_parse_config,
    resolve_path_relative_to_config,
)
from .logging_utils import configure_logging
from .mikrotik_utils import (
    download_remote_file_via_scp,
    export_router_config_via_ssh_to_file,
    mikrotik_quote,
    remove_remote_file,
    sanitize_filename_component,
)
from .sheets import as_str, build_sheet_url
from .ssh import (
    prefix_sshpass,
    require_command,
    scp_base_args,
    ssh_base_args,
    ssh_control_path,
    ssh_run,
    ssh_start_master,
    ssh_stop_master,
    sshpass_env_from_password_env,
)

logger = logging.getLogger(__name__)

COMMENT_MARKER = "generated by python -m homelab mikrotik-dhcp"


def _parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    tool_dir = Path(__file__).resolve().parent / "mikrotik"
    config_path, config = pre_parse_config(argv)

    globals_cfg = get_table(config, "globals")

    # New unified config layout prefers dedicated sections.
    if is_unified_mikrotik_config(config):
        lease_cfg = get_table(config, "mikrotik_dhcp_leases")
        defaults_cfg = get_table(config, "mikrotik_defaults")
    else:
        # Legacy mikrotik-config.toml layout.
        lease_cfg = get_table(config, "dhcp_leases")
        defaults_cfg = get_table(config, "defaults")

    parser = argparse.ArgumentParser(
        description=(
            "Generate MikroTik RouterOS CLI commands to reconcile DHCP static leases "
            "based on the Nodes tab in a Google Sheet. The script downloads the current "
            "lease configuration from the router, compares it to the sheet, and prints "
            "the required /ip dhcp-server lease add/set commands."
        )
    )

    parser.add_argument(
        "--config",
        type=Path,
        default=config_path,
        help="Path to TOML config file containing default parameters",
    )

    parser.add_argument(
        "--sheet-url",
        default=get_config_value(
            globals_cfg,
            "sheet_url",
            DEFAULT_SHEET_URL,
        ),
        help="Google Sheets CSV export URL containing 'gid=0' that will be replaced with the Nodes GID.",
    )
    parser.add_argument(
        "--nodes-gid",
        type=int,
        default=int(get_config_value(globals_cfg, "nodes_gid", 344016240)),
        help="GID for Nodes sheet",
    )

    parser.add_argument(
        "--mikrotik-host",
        default=get_config_value(globals_cfg, "mikrotik_host", get_config_value(config, "mikrotik_host", None)),
        help="MikroTik RouterOS hostname/IP (required)",
    )
    parser.add_argument(
        "--mikrotik-user",
        default=get_config_value(globals_cfg, "mikrotik_user", get_config_value(config, "mikrotik_user", None)),
        help="MikroTik RouterOS username (required)",
    )
    parser.add_argument(
        "--ssh-port",
        type=int,
        default=int(
            get_config_value(
                globals_cfg,
                "mikrotik_ssh_port",
                get_config_value(
                    globals_cfg,
                    "ssh_port",
                    get_config_value(
                        config,
                        "mikrotik_ssh_port",
                        get_config_value(config, "ssh_port", get_config_value(defaults_cfg, "ssh_port", 22)),
                    ),
                ),
            )
        ),
        help="SSH port for RouterOS (default: 22)",
    )

    identity_value = get_config_value(
        globals_cfg,
        "mikrotik_ssh_identity_file",
        get_config_value(
            globals_cfg,
            "ssh_identity_file",
            get_config_value(
                config,
                "mikrotik_ssh_identity_file",
                get_config_value(
                    config,
                    "ssh_identity_file",
                    get_config_value(defaults_cfg, "ssh_identity_file", ""),
                ),
            ),
        ),
    )
    identity_str = str(identity_value or "").strip()
    parser.add_argument(
        "--ssh-identity-file",
        type=Path,
        default=Path(identity_str).expanduser() if identity_str else None,
        help="Optional SSH private key path (passed as -i)",
    )

    parser.add_argument(
        "--mikrotik-password-env",
        default=get_config_value(
            globals_cfg,
            "mikrotik_password_env",
            get_config_value(
                globals_cfg,
                "password_env",
                get_config_value(
                    config,
                    "mikrotik_password_env",
                    get_config_value(
                        config,
                        "password_env",
                        get_config_value(defaults_cfg, "password_env", ""),
                    ),
                ),
            ),
        ),
        help=(
            "Environment variable containing the SSH password (used via sshpass). "
            "If set, sshpass is required. Example: MIKROTIK_PASSWORD"
        ),
    )

    parser.add_argument(
        "--lease-type-column",
        default=get_config_value(
            lease_cfg,
            "lease_type_column",
            get_config_value(config, "lease_type_column", "Static/DHCP"),
        ),
        help="Nodes sheet column containing 'Static' or 'DHCP'",
    )
    parser.add_argument(
        "--ip-column",
        default=get_config_value(
            lease_cfg,
            "ip_column",
            get_config_value(config, "ip_column", "IP Address"),
        ),
        help="Nodes sheet column containing an IP address",
    )
    parser.add_argument(
        "--subnet-column",
        default=get_config_value(
            lease_cfg,
            "subnet_column",
            get_config_value(config, "subnet_column", "Subnet"),
        ),
        help="Nodes sheet column containing a subnet (e.g. 192.168.10.0/24)",
    )
    parser.add_argument(
        "--mac-column",
        default=get_config_value(
            lease_cfg,
            "mac_column",
            get_config_value(config, "mac_column", "MAC Address"),
        ),
        help="Nodes sheet column containing a MAC address",
    )

    parser.add_argument(
        "--output",
        type=Path,
        default=Path(
            get_config_value(
                lease_cfg,
                "output",
                get_config_value(config, "output", str(tool_dir / "mikrotik-dhcp-leases.rsc")),
            )
        ),
        help="Path to write generated RouterOS CLI commands",
    )

    parser.add_argument(
        "--backup-dir",
        type=Path,
        default=Path(
            get_config_value(
                globals_cfg,
                "backup_dir",
                get_config_value(
                    config,
                    "backup_dir",
                    get_config_value(defaults_cfg, "backup_dir", str(tool_dir / "backups")),
                ),
            )
        ),
        help="Directory to write RouterOS /export backups into (used after --apply)",
    )

    parser.add_argument(
        "--stdout",
        action="store_true",
        help="Print commands to stdout instead of writing --output",
    )

    parser.add_argument(
        "--apply",
        action="store_true",
        help=(
            "If set, apply the required changes to the router over SSH. "
            "Without --apply, the script only generates the commands file."
        ),
    )

    parser.add_argument(
        "--yes",
        action="store_true",
        help="Skip the interactive confirmation prompt when used with --apply.",
    )

    parser.add_argument(
        "--debug",
        action="store_true",
        default=bool(get_config_value(lease_cfg, "debug", get_config_value(config, "debug", False))),
        help="Print debug output (including why Static rows were skipped).",
    )

    parser.add_argument(
        "--debug-row",
        action="append",
        type=int,
        default=[],
        help=(
            "Print detailed debug info for a specific Nodes sheet row number (1-based, as shown in Sheets). "
            "May be provided multiple times."
        ),
    )

    return parser.parse_args(argv)


def _normalize_mac(mac: str) -> str:
    mac = mac.strip().upper().replace("-", ":")
    mac = ":".join([part.zfill(2) for part in mac.split(":") if part != ""])  # tolerate 1-digit parts
    return mac


@dataclass(frozen=True)
class DesiredLease:
    mac: str
    address: str
    subnet: str


def _load_desired_leases_from_sheet(
    *,
    sheet_url: str,
    nodes_gid: int,
    lease_type_column: str,
    ip_column: str,
    subnet_column: str,
    mac_column: str,
    debug: bool,
    debug_rows: set[int],
) -> list[DesiredLease]:
    nodes_url = build_sheet_url(sheet_url, int(nodes_gid))
    logger.debug("mikrotik-dhcp: loading Nodes sheet CSV: %s", nodes_url)

    try:
        nodes_df = pd.read_csv(nodes_url)
    except Exception as exc:
        print(f"Error loading Nodes sheet CSV: {exc}", file=sys.stderr)
        print("Ensure the sheet is public (CSV export) or switch to an authenticated method.", file=sys.stderr)
        sys.exit(1)

    leases: list[DesiredLease] = []
    seen_macs: set[str] = set()
    seen_ips: set[str] = set()

    dhcp_rows = 0
    dhcp_rows_kept = 0
    dhcp_rows_skipped = 0

    # enumerate() gives us a predictable 1-based-ish row number for messages.
    # start=2 because row 1 is the header in the sheet.
    for row_number, (_, row) in enumerate(nodes_df.iterrows(), start=2):
        ip_raw = as_str(row.get(ip_column, ""))
        subnet_raw = as_str(row.get(subnet_column, ""))
        mac_raw = as_str(row.get(mac_column, ""))

        lease_type_raw = as_str(row.get(lease_type_column, ""))
        lease_type = lease_type_raw.lower()

        if row_number in debug_rows:
            print(
                "DebugRow: "
                + f"row={row_number} lease_type={lease_type_raw!r} ip={ip_raw!r} subnet={subnet_raw!r} mac={mac_raw!r}",
                file=sys.stderr,
            )
        # We manage DHCP reservations for nodes that are configured to use DHCP.
        # Rows marked Static are intentionally ignored (no warnings).
        if lease_type != "dhcp":
            continue

        dhcp_rows += 1

        def warn_missing_fields() -> None:
            missing_fields: list[str] = []
            if not ip_raw:
                missing_fields.append(ip_column)
            if not subnet_raw:
                missing_fields.append(subnet_column)
            if not mac_raw:
                missing_fields.append(mac_column)
            if missing_fields:
                print(
                    f"Warning: row {row_number} marked DHCP but missing field(s): {', '.join(missing_fields)}",
                    file=sys.stderr,
                )

        def debug_skip(reason: str) -> None:
            nonlocal dhcp_rows_skipped
            dhcp_rows_skipped += 1
            if not debug and row_number not in debug_rows:
                return
            details = f"ip={ip_raw!r} mac={mac_raw!r} subnet={subnet_raw!r}"
            print(
                f"Debug: skipping DHCP row {row_number}: {reason} ({details})",
                file=sys.stderr,
            )
            if row_number in debug_rows:
                print(f"DebugRow: decision=SKIP reason={reason}", file=sys.stderr)

        if not ip_raw or not mac_raw or not subnet_raw:
            warn_missing_fields()
            debug_skip("missing required field")
            continue

        try:
            ipaddress.ip_address(ip_raw)
        except ValueError:
            debug_skip("invalid IP")
            continue

        subnet = subnet_raw
        try:
            network = ipaddress.ip_network(subnet, strict=False)
        except ValueError:
            debug_skip("invalid Subnet CIDR")
            continue

        if ipaddress.ip_address(ip_raw) not in network:
            debug_skip("IP not in subnet")
            continue

        try:
            mac = _normalize_mac(mac_raw)
        except Exception:
            debug_skip("invalid MAC")
            continue

        if mac in seen_macs:
            debug_skip("duplicate MAC in sheet")
            continue
        if ip_raw in seen_ips:
            debug_skip("duplicate IP in sheet")
            continue

        seen_macs.add(mac)
        seen_ips.add(ip_raw)
        leases.append(DesiredLease(mac=mac, address=ip_raw, subnet=subnet))
        dhcp_rows_kept += 1

        if row_number in debug_rows:
            print("DebugRow: decision=KEEP", file=sys.stderr)

    if debug:
        summary = (
            f"Debug: Nodes sheet parsed. "
            f"dhcp_rows={dhcp_rows} kept={dhcp_rows_kept} skipped={dhcp_rows_skipped}"
        )
        print(summary, file=sys.stderr)

    return leases


def _parse_routeros_terse(text: str) -> list[dict]:
    rows: list[dict] = []
    for raw_line in text.splitlines():
        line = raw_line.strip()
        if not line:
            continue

        try:
            tokens = shlex.split(line, posix=True)
        except ValueError:
            tokens = line.split()

        row: dict[str, str] = {}
        for token in tokens:
            if "=" not in token:
                continue
            key, value = token.split("=", 1)
            row[key] = value

        if row:
            rows.append(row)

    return rows


def _fetch_static_leases_from_router(
    *,
    ssh_args: list[str],
    target: str,
    env: dict[str, str] | None,
) -> list[dict]:
    # Terse output is easiest to parse.
    cmd = "/ip dhcp-server lease print terse without-paging"
    result = ssh_run(ssh_args=ssh_args, target=target, command=cmd, env=env)
    rows = _parse_routeros_terse(result.stdout)

    static_leases: list[dict] = []
    for lease in rows:
        dynamic_raw = str(lease.get("dynamic", "no")).lower()
        is_dynamic = dynamic_raw in {"yes", "true", "1"}
        if is_dynamic:
            continue
        static_leases.append(lease)
    return static_leases


def _fetch_dhcp_server_by_subnet_from_router(
    *,
    ssh_args: list[str],
    target: str,
    env: dict[str, str] | None,
) -> dict[str, str]:
    cmd = "/ip dhcp-server network print terse without-paging"
    result = ssh_run(ssh_args=ssh_args, target=target, command=cmd, env=env)
    rows = _parse_routeros_terse(result.stdout)

    mapping: dict[str, str] = {}
    for row in rows:
        cidr = as_str(row.get("address", ""))
        server = as_str(row.get("dhcp-server", ""))
        if cidr and server:
            mapping[cidr] = server
    return mapping


def _index_leases(static_leases: list[dict]):
    by_mac: dict[str, dict] = {}
    by_ip: dict[str, dict] = {}

    for lease in static_leases:
        mac = as_str(lease.get("mac-address", ""))
        addr = as_str(lease.get("address", ""))
        if mac:
            try:
                by_mac[_normalize_mac(mac)] = lease
            except Exception:
                pass
        if addr:
            by_ip[addr] = lease

    return by_mac, by_ip


def _build_comment(*, subnet: str) -> str:
    if subnet:
        return f"{COMMENT_MARKER}; subnet={subnet}"
    return COMMENT_MARKER


@dataclass(frozen=True)
class LeaseOperation:
    kind: str  # 'add' | 'set'
    command: str


def _plan_operations(
    *,
    desired: list[DesiredLease],
    existing_static: list[dict],
    dhcp_server_by_subnet: dict[str, str],
    debug: bool,
) -> list[LeaseOperation]:
    by_mac, by_ip = _index_leases(existing_static)

    ops: list[LeaseOperation] = []

    for lease in desired:
        comment = _build_comment(subnet=lease.subnet)
        server = ""
        if lease.subnet and lease.subnet in dhcp_server_by_subnet:
            server = dhcp_server_by_subnet[lease.subnet]

        def build_set_command(*, selector: str) -> str:
            parts = [
                "/ip dhcp-server lease set",
                selector,
                f"address={lease.address}",
                f"mac-address={mikrotik_quote(lease.mac)}",
                f"comment={mikrotik_quote(comment)}",
                "disabled=no",
            ]
            if server:
                parts.append(f"server={mikrotik_quote(server)}")
            return " ".join(parts)

        def build_add_command() -> str:
            parts = [
                "/ip dhcp-server lease add",
                f"address={lease.address}",
                f"mac-address={mikrotik_quote(lease.mac)}",
                f"comment={mikrotik_quote(comment)}",
                "disabled=no",
            ]
            if server:
                parts.append(f"server={mikrotik_quote(server)}")
            return " ".join(parts)

        existing = by_mac.get(lease.mac)
        if existing is not None:
            existing_addr = as_str(existing.get("address", ""))
            existing_comment = as_str(existing.get("comment", ""))
            existing_disabled = str(existing.get("disabled", "false")).lower() == "true"

            if existing_addr == lease.address and (not existing_disabled) and debug:
                print(
                    "Debug: desired lease already exists (MAC+IP match): "
                    + f"mac={lease.mac} ip={lease.address}",
                    file=sys.stderr,
                )

            if existing_addr == lease.address and (not existing_disabled) and (COMMENT_MARKER in existing_comment):
                continue

            selector = f"[find where mac-address={mikrotik_quote(lease.mac)}]"
            ops.append(LeaseOperation(kind="set", command=build_set_command(selector=selector)))
            continue

        existing = by_ip.get(lease.address)
        if existing is not None:
            existing_mac = as_str(existing.get("mac-address", ""))
            if existing_mac:
                try:
                    existing_mac = _normalize_mac(existing_mac)
                except Exception:
                    pass

            if (existing_mac == lease.mac) and debug:
                print(
                    "Debug: desired lease already exists (IP+MAC match): "
                    + f"mac={lease.mac} ip={lease.address}",
                    file=sys.stderr,
                )

            # Lease exists for this IP but may be the wrong MAC/comment/server.
            selector = f"[find where address={lease.address}]"
            ops.append(LeaseOperation(kind="set", command=build_set_command(selector=selector)))
            continue

        ops.append(LeaseOperation(kind="add", command=build_add_command()))

    return ops


def _generate_commands(
    *,
    desired: list[DesiredLease],
    existing_static: list[dict],
    dhcp_server_by_subnet: dict[str, str],
):
    ops = _plan_operations(
        desired=desired,
        existing_static=existing_static,
        dhcp_server_by_subnet=dhcp_server_by_subnet,
        debug=False,
    )

    now = _dt.datetime.now(tz=_dt.timezone.utc).isoformat()
    commands: list[str] = [
        f"# {COMMENT_MARKER}",
        f"# generated-at={now}",
        "#",
        "# Apply with: /import file-name=mikrotik-dhcp-leases.rsc",
        "",
    ]

    for op in ops:
        commands.append(op.command)

    if not ops:
        commands.append("# No changes required")

    return commands


def _apply_operations_to_router(
    *,
    ssh_args: list[str],
    target: str,
    ops: list[LeaseOperation],
    env: dict[str, str] | None,
) -> None:
    if not ops:
        print("No changes to apply")
        return

    adds = sum(1 for op in ops if op.kind == "add")
    sets = sum(1 for op in ops if op.kind == "set")

    # Run in one SSH invocation to reduce overhead and auth prompts.
    joined = "; ".join(op.command for op in ops)
    ssh_run(ssh_args=ssh_args, target=target, command=joined, env=env)
    print(f"Applied changes to router: {adds} adds, {sets} updates")


def _command_lines_only(commands: list[str]) -> list[str]:
    return [line for line in commands if line.strip().startswith("/ip ")]


def _confirm_apply(*, commands: list[str], op_count: int) -> None:
    command_lines = _command_lines_only(commands)

    print("Planned RouterOS commands:", file=sys.stderr)
    if command_lines:
        for line in command_lines:
            print(line, file=sys.stderr)
    else:
        print("(No command lines; nothing to apply)", file=sys.stderr)

    print("", file=sys.stderr)
    print(f"Summary: {op_count} change(s)", file=sys.stderr)
    print("Type 'apply' to continue, or anything else to abort:", file=sys.stderr)

    try:
        response = input("> ").strip().lower()
    except EOFError:
        response = ""

    if response != "apply":
        raise SystemExit("Aborted")


def main(argv: list[str] | None = None) -> int:
    args = _parse_args(argv)

    if args.debug:
        configure_logging(debug=True)
        logger.debug("mikrotik-dhcp: debug enabled")

    logger.debug("mikrotik-dhcp: argv=%r", argv)

    config_path = args.config.expanduser().resolve()
    logger.debug("mikrotik-dhcp: config_path=%s", config_path)

    missing: list[str] = []
    if not args.mikrotik_host:
        missing.append("mikrotik_host")
    if not args.mikrotik_user:
        missing.append("mikrotik_user")

    if missing:
        print(
            "Error: missing router credential(s): " + ", ".join(missing),
            file=sys.stderr,
        )
        print(f"Config file used: {config_path}", file=sys.stderr)
        if "mikrotik_host" in missing or "mikrotik_user" in missing:
            print(
                "Host/user sources checked: --mikrotik-host/--mikrotik-user and mikrotik_host/mikrotik_user in config",
                file=sys.stderr,
            )
        return 2

    # Type narrowing for static analyzers (and to guard against non-string TOML values).
    mikrotik_host: str = str(args.mikrotik_host)
    mikrotik_user: str = str(args.mikrotik_user)

    try:
        require_command("ssh")
        if args.apply:
            require_command("scp")
    except RuntimeError as exc:
        print(f"Error: {exc}", file=sys.stderr)
        return 1

    password_env_raw = str(args.mikrotik_password_env or "").strip()
    password_env = password_env_raw or None
    run_env = sshpass_env_from_password_env(password_env=password_env)
    use_sshpass = run_env is not None
    if use_sshpass:
        try:
            require_command("sshpass")
        except RuntimeError as exc:
            print(f"Error: {exc}", file=sys.stderr)
            return 1

    ssh_port: int = int(args.ssh_port)
    identity_file: Path | None = (
        resolve_path_relative_to_config(config_path, args.ssh_identity_file)
        if args.ssh_identity_file is not None
        else None
    )
    if identity_file is not None and not identity_file.exists():
        print(f"Error: SSH identity file not found: {identity_file}", file=sys.stderr)
        return 2

    target = f"{mikrotik_user}@{mikrotik_host}"
    logger.debug("mikrotik-dhcp: target=%s port=%s apply=%s", target, ssh_port, bool(args.apply))
    control_path = ssh_control_path(prefix="mikrotik", username=mikrotik_user, host=mikrotik_host, port=ssh_port)
    ssh_args = prefix_sshpass(
        ssh_base_args(control_path=control_path, port=ssh_port, identity_file=identity_file),
        enabled=use_sshpass,
    )
    scp_args = prefix_sshpass(
        scp_base_args(control_path=control_path, port=ssh_port, identity_file=identity_file),
        enabled=use_sshpass,
    )

    config = load_toml_or_exit(config_path)
    if is_unified_mikrotik_config(config):
        lease_cfg = get_table(config, "mikrotik_dhcp_leases")
    else:
        lease_cfg = get_table(config, "dhcp_leases")

    dhcp_server_by_subnet_override = get_config_value(
        lease_cfg,
        "dhcp_server_by_subnet",
        {},
    )
    if dhcp_server_by_subnet_override is None:
        dhcp_server_by_subnet_override = {}

    desired_leases = _load_desired_leases_from_sheet(
        sheet_url=args.sheet_url,
        nodes_gid=args.nodes_gid,
        lease_type_column=args.lease_type_column,
        ip_column=args.ip_column,
        subnet_column=args.subnet_column,
        mac_column=args.mac_column,
        debug=bool(args.debug),
        debug_rows=set(int(x) for x in (args.debug_row or []) if x is not None),
    )

    adds = 0
    sets = 0
    try:
        ssh_start_master(ssh_args=ssh_args, target=target, env=run_env)

        logger.debug("mikrotik-dhcp: fetching existing static leases")

        existing_static = _fetch_static_leases_from_router(
            ssh_args=ssh_args,
            target=target,
            env=run_env,
        )

        dhcp_server_by_subnet = _fetch_dhcp_server_by_subnet_from_router(
            ssh_args=ssh_args,
            target=target,
            env=run_env,
        )

        # User config overrides router-discovered mapping.
        dhcp_server_by_subnet.update(dict(dhcp_server_by_subnet_override))

        commands = _generate_commands(
            desired=desired_leases,
            existing_static=existing_static,
            dhcp_server_by_subnet=dict(dhcp_server_by_subnet),
        )

        ops = _plan_operations(
            desired=desired_leases,
            existing_static=existing_static,
            dhcp_server_by_subnet=dict(dhcp_server_by_subnet),
            debug=bool(args.debug),
        )

        adds = sum(1 for op in ops if op.kind == "add")
        sets = sum(1 for op in ops if op.kind == "set")

        if args.apply:
            if not ops:
                print("No changes to apply")
                return 0
            if not args.yes:
                _confirm_apply(commands=commands, op_count=len(ops))

            _apply_operations_to_router(
                ssh_args=ssh_args,
                target=target,
                ops=ops,
                env=run_env,
            )

            safe_host = sanitize_filename_component(mikrotik_host)
            timestamp = _dt.datetime.now(tz=_dt.timezone.utc).strftime("%Y%m%dT%H%M%SZ")
            export_base = f"router-export-{safe_host}-{timestamp}"

            remote_filename = export_router_config_via_ssh_to_file(
                ssh_args=ssh_args,
                target=target,
                export_base_name=export_base,
                env=run_env,
            )
            backup_dir = resolve_path_relative_to_config(config_path, args.backup_dir)
            backup_path = backup_dir / remote_filename
            logger.debug("mikrotik-dhcp: writing backup to %s", backup_path)
            download_remote_file_via_scp(
                scp_args=scp_args,
                target=target,
                remote_filename=remote_filename,
                local_path=backup_path,
                env=run_env,
                attempts=1,
            )
            remove_remote_file(
                ssh_args=ssh_args,
                target=target,
                remote_filename=remote_filename,
                env=run_env,
            )
            print(f"Wrote router export backup: {backup_path}")
    finally:
        ssh_stop_master(ssh_args=ssh_args, target=target, env=run_env)

    output_path = resolve_path_relative_to_config(config_path, args.output)
    logger.debug("mikrotik-dhcp: output_path=%s stdout=%s", output_path, bool(args.stdout))
    if args.stdout:
        print("\n".join(commands))
    else:
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text("\n".join(commands) + "\n", encoding="utf-8")
        print(f"Wrote {len(commands)} lines to {output_path}")

    if not args.apply:
        print("Dry run (no --apply): no remote changes made")
        if args.stdout:
            print("- generated: stdout")
        else:
            print(f"- generated: {output_path}")

        if adds + sets == 0:
            print("- would ssh: skipped (no changes needed)")
        else:
            print(
                f"- would ssh: {target} apply {adds + sets} change(s): {adds} add(s), {sets} update(s)"
            )
            if not bool(args.yes):
                print("- would prompt: confirmation (use --yes to skip)")

        backup_dir = resolve_path_relative_to_config(config_path, args.backup_dir)
        print(f"- would back up: RouterOS /export downloaded into {backup_dir}")
        print("Re-run with --apply to perform these actions.")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
