from __future__ import annotations

import argparse
import datetime as _dt
import logging
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import pandas as pd

from .config import (
    get_table,
    is_unified_mikrotik_config,
    load_toml_or_exit,
    pre_parse_config,
    resolve_path_relative_to_config,
)
from .logging_utils import configure_logging
from .mikrotik_utils import mikrotik_quote
from .sheets import (
    as_str,
    build_sheet_url,
    df_with_normalized_columns,
    load_nodes_lookup,
    normalize_ip,
    normalize_ports,
    parse_bool,
)
from .ssh import (
    prefix_sshpass,
    require_command,
    ssh_base_args,
    ssh_control_path,
    ssh_run,
    ssh_start_master,
    ssh_stop_master,
    sshpass_env_from_password_env,
)

logger = logging.getLogger(__name__)

COMMENT_MARKER = "generated by python -m homelab mikrotik-firewall"


def _normalize_protocol(value: Any) -> str:
    proto = as_str(value).lower()
    if proto in {"tcp", "udp"}:
        return proto
    return ""


def _split_csv_list(value: str) -> list[str]:
    if not value:
        return []
    parts = [item.strip() for item in value.split(",")]
    return [item for item in parts if item]


@dataclass(frozen=True)
class NatRule:
    protocol: str
    dst_port: int
    to_address: str
    to_port: int
    comment: str

    def render(self) -> str:
        return (
            "/ip firewall nat add chain=dstnat action=dst-nat "
            f"in-interface-list=WAN protocol={self.protocol} dst-port={self.dst_port} "
            f"to-addresses={self.to_address} to-ports={self.to_port} "
            f"comment={mikrotik_quote(self.comment)}"
        )


@dataclass(frozen=True)
class FilterRule:
    protocol: str
    dst_port: int
    dst_address: str | None
    in_interface_list: str | None
    in_interface: str | None
    out_interface: str | None
    src_address_list: str | None
    dst_address_list: str | None
    connection_nat_state: str | None
    comment: str

    def render(self) -> str:
        parts = [
            "/ip firewall filter add chain=forward action=accept",
            f"protocol={self.protocol}",
            f"dst-port={self.dst_port}",
        ]

        if self.in_interface_list:
            parts.append(f"in-interface-list={self.in_interface_list}")
        if self.in_interface:
            parts.append(f"in-interface={self.in_interface}")
        if self.out_interface:
            parts.append(f"out-interface={self.out_interface}")
        if self.dst_address:
            parts.append(f"dst-address={self.dst_address}")
        if self.src_address_list:
            parts.append(f"src-address-list={self.src_address_list}")
        if self.dst_address_list:
            parts.append(f"dst-address-list={self.dst_address_list}")
        if self.connection_nat_state:
            parts.append(f"connection-nat-state={self.connection_nat_state}")

        parts.append(f"comment={mikrotik_quote(self.comment)}")
        return " ".join(parts)


@dataclass(frozen=True)
class AddressListEntry:
    list_name: str
    address: str
    comment: str

    def render(self) -> str:
        return (
            f"/ip firewall address-list add list={self.list_name} address={self.address} "
            f"comment={mikrotik_quote(self.comment)}"
        )


def build_parser(argv: list[str] | None = None) -> argparse.ArgumentParser:
    tool_dir = Path(__file__).resolve().parent / "mikrotik"
    config_path, config = pre_parse_config(argv)

    globals_cfg = get_table(config, "globals")

    if is_unified_mikrotik_config(config):
        fw_cfg = get_table(config, "mikrotik_firewall")
        lease_cfg = get_table(config, "mikrotik_dhcp_leases")
        defaults_cfg = get_table(config, "mikrotik_defaults")
    else:
        fw_cfg = get_table(config, "firewall")
        lease_cfg = get_table(config, "dhcp_leases")
        defaults_cfg = get_table(config, "defaults")

    def _cfg_tool(key: str, default: Any) -> Any:
        # Tool-specific precedence (no globals): firewall section first, then
        # dhcp_leases, then defaults.
        if key in fw_cfg:
            return fw_cfg.get(key, default)
        if key in lease_cfg:
            return lease_cfg.get(key, default)
        if key in defaults_cfg:
            return defaults_cfg.get(key, default)
        return default

    def _cfg_shared(key: str, default: Any) -> Any:
        # Shared settings come from [globals] and must not be overridden by
        # tool sections.
        if key in globals_cfg:
            return globals_cfg.get(key, default)
        return _cfg_tool(key, default)

    parser = argparse.ArgumentParser(
        prog="python -m homelab mikrotik-firewall",
        description=(
            "Generate and apply MikroTik RouterOS firewall rules (dstnat + forward filter) "
            "from the Services tab in a Google Sheet. Also generates Caddy DMZ->homelab "
            "address lists grouped by backend port to keep rule count low."
        ),
    )

    parser.add_argument(
        "--config",
        type=Path,
        default=config_path,
        help="Path to TOML config file containing default parameters",
    )

    parser.add_argument(
        "--sheet-url",
        default=str(_cfg_shared("sheet_url", "")).strip(),
        help="Google Sheets CSV export URL containing 'gid=0' (the script substitutes gids)",
    )
    parser.add_argument(
        "--caddy-gid",
        type=int,
        default=_cfg_shared("services_gid", _cfg_tool("caddy_gid", _cfg_tool("services_gid", None))),
        help="GID for the Services sheet tab (same tab used by the Caddy generator)",
    )
    parser.add_argument(
        "--nodes-gid",
        type=int,
        default=_cfg_shared("nodes_gid", None),
        help="Optional: Nodes gid for hostname->IP lookup fallback",
    )

    parser.add_argument(
        "--mikrotik-host",
        default=_cfg_shared("mikrotik_host", None),
        help="MikroTik RouterOS hostname/IP (required)",
    )
    parser.add_argument(
        "--mikrotik-user",
        default=_cfg_shared("mikrotik_user", None),
        help="MikroTik RouterOS username (required)",
    )
    parser.add_argument(
        "--ssh-port",
        type=int,
        default=int(
            _cfg_shared(
                "mikrotik_ssh_port",
                _cfg_shared("ssh_port", _cfg_tool("mikrotik_ssh_port", _cfg_tool("ssh_port", 22))),
            )
        ),
        help="SSH port for RouterOS (default: 22)",
    )
    parser.add_argument(
        "--ssh-identity-file",
        type=Path,
        default=Path(
            str(_cfg_shared("mikrotik_ssh_identity_file", _cfg_shared("ssh_identity_file", "")))
        )
        if str(_cfg_shared("mikrotik_ssh_identity_file", _cfg_shared("ssh_identity_file", ""))).strip()
        else None,
        help="Optional SSH private key path (passed as -i)",
    )
    parser.add_argument(
        "--mikrotik-password-env",
        default=str(
            _cfg_shared(
                "mikrotik_password_env",
                _cfg_shared("password_env", _cfg_tool("mikrotik_password_env", _cfg_tool("password_env", ""))),
            )
        ).strip(),
        help=(
            "Environment variable containing the SSH password (used via sshpass). "
            "If set, sshpass is required. Example: MIKROTIK_PASSWORD"
        ),
    )

    parser.add_argument(
        "--caddy-ip",
        action="append",
        default=[],
        help=(
            "Caddy proxy IP in the DMZ VLAN (may be provided multiple times). "
            "Overrides [globals].caddy_ip and firewall.caddy_ip(s) in config."
        ),
    )
    parser.add_argument(
        "--dmz-interface",
        default=str(_cfg_tool("dmz_interface", "vlan20-dmz")).strip(),
        help="RouterOS interface name for DMZ VLAN (default: vlan20-dmz)",
    )
    parser.add_argument(
        "--homelab-interface",
        default=str(_cfg_tool("homelab_interface", "vlan30-homelab")).strip(),
        help="RouterOS interface name for homelab VLAN (default: vlan30-homelab)",
    )
    parser.add_argument(
        "--caddy-default-backend-port",
        type=int,
        default=int(_cfg_tool("caddy_default_backend_port", 80)),
        help="Default backend port to assume for ingress=caddy rows missing backend_port (default: 80)",
    )

    parser.add_argument(
        "--output",
        type=Path,
        default=Path(str(_cfg_tool("output", str(tool_dir / "mikrotik-firewall.rsc")))),
        help="Path to write generated RouterOS CLI commands",
    )
    parser.add_argument(
        "--stdout",
        action="store_true",
        help="Print commands to stdout instead of writing --output",
    )
    parser.add_argument(
        "--apply",
        action="store_true",
        help="Apply the generated rules to the router over SSH",
    )
    parser.add_argument(
        "--yes",
        action="store_true",
        help="Skip the interactive confirmation prompt when used with --apply",
    )
    parser.add_argument(
        "--debug",
        action="store_true",
        default=bool(_cfg_tool("debug", False)),
        help="Enable verbose debug output to stderr",
    )

    return parser


def _service_label(row: pd.Series) -> str:
    for key in ["service_name", "frontend_hostname", "hostname"]:
        value = as_str(row.get(key))
        if value:
            return value
    return "service"


def _resolve_backend_ip(row: pd.Series, nodes_lookup: dict[str, str] | None, debug: bool, row_id: int) -> str | None:
    backend_ip = normalize_ip(as_str(row.get("ip_address")))
    if backend_ip:
        return backend_ip
    if nodes_lookup:
        backend_node = as_str(row.get("hostname")).lower()
        if backend_node and backend_node in nodes_lookup:
            return nodes_lookup[backend_node]
    if debug:
        print(f"[debug] Row {row_id}: missing ip_address (and no Nodes match); skipping", file=sys.stderr)
    return None


def _resolve_port_mappings(
    *,
    frontend_ports: list[int],
    backend_ports: list[int],
    debug: bool,
    row_id: int,
) -> list[tuple[int, int]]:
    if not frontend_ports:
        return []
    if not backend_ports:
        return [(p, p) for p in frontend_ports]
    if len(backend_ports) == 1:
        return [(p, backend_ports[0]) for p in frontend_ports]
    if len(backend_ports) == len(frontend_ports):
        return list(zip(frontend_ports, backend_ports))
    if debug:
        print(
            f"[debug] Row {row_id}: frontend_port={frontend_ports} backend_port={backend_ports} mismatch; skipping",
            file=sys.stderr,
        )
    return []


def _collect_desired_state(
    *,
    services_df: pd.DataFrame,
    nodes_lookup: dict[str, str] | None,
    caddy_default_backend_port: int,
    caddy_ips: list[str],
    dmz_interface: str,
    homelab_interface: str,
    debug: bool,
) -> tuple[list[AddressListEntry], list[NatRule], list[FilterRule], list[FilterRule], list[FilterRule]]:
    """Return (address_entries, nat_rules, wan_filter_rules, caddy_filter_rules, all_filter_rules).

    Split forward filter rules into WAN-focused and Caddy DMZ->homelab so we can
    order/move them independently.
    """

    nat_rules: dict[tuple[str, int, str, int], NatRule] = {}
    wan_filter: dict[tuple[str, int, str, int], FilterRule] = {}

    # backend_port -> set(backend_ip)
    caddy_groups: dict[int, set[str]] = {}

    for idx, row in services_df.iterrows():
        row_id = int(idx)
        enabled = parse_bool(row.get("frontend_enabled"), default=False)
        if not enabled:
            continue

        ingress = as_str(row.get("ingress")).lower()
        exposure = as_str(row.get("exposure")).lower()
        proto = _normalize_protocol(row.get("protocol"))

        backend_ip = _resolve_backend_ip(row, nodes_lookup, debug, row_id)
        if not backend_ip:
            continue

        label = _service_label(row)

        if ingress == "dnat":
            if exposure != "public":
                continue
            if not proto:
                if debug:
                    proto_raw = as_str(row.get("protocol"))
                    print(
                        f"[debug] Row {row_id}: invalid protocol={proto_raw!r}; skipping",
                        file=sys.stderr,
                    )
                continue

            frontend_ports = normalize_ports(row.get("frontend_port"))
            backend_ports = normalize_ports(row.get("backend_port"))
            mappings = _resolve_port_mappings(
                frontend_ports=frontend_ports,
                backend_ports=backend_ports,
                debug=debug,
                row_id=row_id,
            )
            if not mappings:
                if debug:
                    print(f"[debug] Row {row_id}: missing/invalid ports; skipping", file=sys.stderr)
                continue

            for dst_port, to_port in mappings:
                key = (proto, int(dst_port), backend_ip, int(to_port))
                comment = f"{COMMENT_MARKER}; wan dnat; {label}; {proto}:{dst_port}->{backend_ip}:{to_port}"
                nat_rules.setdefault(
                    key,
                    NatRule(
                        protocol=proto,
                        dst_port=int(dst_port),
                        to_address=backend_ip,
                        to_port=int(to_port),
                        comment=comment,
                    ),
                )

                # Match the NATed connection explicitly.
                wan_filter.setdefault(
                    key,
                    FilterRule(
                        protocol=proto,
                        dst_port=int(to_port),
                        dst_address=backend_ip,
                        in_interface_list="WAN",
                        in_interface=None,
                        out_interface=None,
                        src_address_list=None,
                        dst_address_list=None,
                        connection_nat_state="dstnat",
                        comment=f"{COMMENT_MARKER}; wan forward; {label}; {proto}:{dst_port}->{backend_ip}:{to_port}",
                    ),
                )

        elif ingress == "caddy":
            # Keep this tcp-only for now (matches the existing caddyfile generator behavior).
            if proto and proto != "tcp":
                if debug:
                    print(f"[debug] Row {row_id}: ingress=caddy but protocol={proto}; skipping", file=sys.stderr)
                continue

            backend_ports = normalize_ports(row.get("backend_port"))
            if not backend_ports:
                backend_ports = [int(caddy_default_backend_port)]
            port = int(backend_ports[0])
            caddy_groups.setdefault(port, set()).add(backend_ip)

    # Address list entries
    entries: list[AddressListEntry] = []

    for caddy_ip in caddy_ips:
        entries.append(
            AddressListEntry(
                list_name="caddy-host",
                address=caddy_ip,
                comment=f"{COMMENT_MARKER}; caddy-host",
            )
        )

    caddy_filter_rules: list[FilterRule] = []
    for port in sorted(caddy_groups.keys()):
        list_name = f"caddy-{port}"
        for backend_ip in sorted(caddy_groups[port]):
            entries.append(
                AddressListEntry(
                    list_name=list_name,
                    address=backend_ip,
                    comment=f"{COMMENT_MARKER}; caddy-backend; port={port}",
                )
            )

        caddy_filter_rules.append(
            FilterRule(
                protocol="tcp",
                dst_port=int(port),
                dst_address=None,
                in_interface=None,
                out_interface=None,
                in_interface_list=None,
                src_address_list="caddy-host",
                dst_address_list=list_name,
                connection_nat_state=None,
                comment=f"{COMMENT_MARKER}; caddy forward; port={port}",
            )
        )

    # Default WAN->Caddy rules (always present)
    if caddy_ips:
        # Use the first IP as dstnat target.
        caddy_ip = caddy_ips[0]
        for port in [80, 443]:
            key = ("tcp", port, caddy_ip, port)
            nat_rules.setdefault(
                key,
                NatRule(
                    protocol="tcp",
                    dst_port=port,
                    to_address=caddy_ip,
                    to_port=port,
                    comment=f"{COMMENT_MARKER}; wan->caddy; tcp:{port}->{caddy_ip}:{port}",
                ),
            )

        wan_filter.setdefault(
            ("tcp", 80, caddy_ip, 80),
            FilterRule(
                protocol="tcp",
                dst_port=80,
                dst_address=caddy_ip,
                in_interface_list="WAN",
                in_interface=None,
                out_interface=None,
                src_address_list=None,
                dst_address_list=None,
                connection_nat_state="dstnat",
                comment=f"{COMMENT_MARKER}; wan forward; caddy; tcp:80->{caddy_ip}:80",
            ),
        )
        wan_filter.setdefault(
            ("tcp", 443, caddy_ip, 443),
            FilterRule(
                protocol="tcp",
                dst_port=443,
                dst_address=caddy_ip,
                in_interface_list="WAN",
                in_interface=None,
                out_interface=None,
                src_address_list=None,
                dst_address_list=None,
                connection_nat_state="dstnat",
                comment=f"{COMMENT_MARKER}; wan forward; caddy; tcp:443->{caddy_ip}:443",
            ),
        )

    # Ensure DMZ->homelab rule additionally pins interfaces for safety.
    # (src is pinned via caddy-host list; ingress interface ensures directionality.)
    caddy_filter_rules = [
        FilterRule(
            **{
                **rule.__dict__,
                "in_interface": dmz_interface,
            }
        )
        for rule in caddy_filter_rules
    ]

    nat_list = [nat_rules[k] for k in sorted(nat_rules.keys())]
    wan_filter_list = [wan_filter[k] for k in sorted(wan_filter.keys())]
    all_filter = [*wan_filter_list, *caddy_filter_rules]
    return entries, nat_list, wan_filter_list, caddy_filter_rules, all_filter


def _generate_rsc(
    *,
    address_entries: list[AddressListEntry],
    nat_rules: list[NatRule],
    filter_rules: list[FilterRule],
    output_path: Path,
    stdout: bool,
) -> None:
    now = _dt.datetime.now(tz=_dt.timezone.utc).isoformat()

    lines: list[str] = [
        f"# {COMMENT_MARKER}",
        f"# generated-at={now}",
        "#",
        f"# Apply with: /import file-name={output_path.name}",
        "",
        "/ip firewall address-list",
    ]

    if address_entries:
        lines.extend(entry.render() for entry in address_entries)
    else:
        lines.append("# (no address-list entries)")

    lines.extend(["", "/ip firewall nat"])
    if nat_rules:
        lines.extend(rule.render() for rule in nat_rules)
    else:
        lines.append("# (no nat rules)")

    lines.extend(["", "/ip firewall filter"])
    if filter_rules:
        lines.extend(rule.render() for rule in filter_rules)
    else:
        lines.append("# (no filter rules)")

    text = "\n".join(lines) + "\n"

    if stdout:
        print(text, end="")
        return

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(text, encoding="utf-8")
    print(f"Wrote RouterOS script: {output_path}")


def _confirm_apply(*, command_count: int) -> None:
    prompt = f"Apply {command_count} RouterOS command(s) to the router? [y/N] "
    answer = input(prompt).strip().lower()
    if answer not in {"y", "yes"}:
        raise SystemExit(0)


def _build_apply_commands(
    *,
    address_entries: list[AddressListEntry],
    nat_rules: list[NatRule],
    wan_filter_rules: list[FilterRule],
    caddy_filter_rules: list[FilterRule],
) -> list[str]:
    cmds: list[str] = []

    # Clear previous generated items.
    marker = COMMENT_MARKER
    cmds.append(f'/ip firewall address-list remove [find where comment~"{marker}"]')
    cmds.append(f'/ip firewall nat remove [find where comment~"{marker}"]')
    cmds.append(f'/ip firewall filter remove [find where comment~"{marker}"]')

    # Re-add desired state.
    cmds.extend(entry.render() for entry in address_entries)
    cmds.extend(rule.render() for rule in nat_rules)
    cmds.extend(rule.render() for rule in [*wan_filter_rules, *caddy_filter_rules])

    # Move rules into correct positions.
    # - Caddy DMZ->homelab rules must be above "block DMZ -> HOMELAB".
    # - WAN forward rules must be above "drop all other forward".
    cmds.append(':local dropDmz [/ip firewall filter find where comment="block DMZ -> HOMELAB"];')
    cmds.append(':local dropAll [/ip firewall filter find where comment="drop all other forward"];')

    # Move in reverse order so final ordering is stable.
    for rule in reversed(caddy_filter_rules):
        cmds.append(
            (
                f':if ([:len $dropDmz] > 0) do={{/ip firewall filter move '
                f'[find where comment={mikrotik_quote(rule.comment)}] destination=($dropDmz->0);}}'
            )
        )

    for rule in reversed(wan_filter_rules):
        cmds.append(
            (
                f':if ([:len $dropAll] > 0) do={{/ip firewall filter move '
                f'[find where comment={mikrotik_quote(rule.comment)}] destination=($dropAll->0);}}'
            )
        )

    return cmds


def main(argv: list[str] | None = None) -> int:
    parser = build_parser(argv)
    args = parser.parse_args(argv)

    if args.debug:
        configure_logging(debug=True)
        logger.debug("mikrotik-firewall: debug enabled")

    logger.debug("mikrotik-firewall: argv=%r", argv)

    config_path = args.config.expanduser().resolve()
    logger.debug("mikrotik-firewall: config_path=%s", config_path)

    missing: list[str] = []
    if not args.sheet_url:
        missing.append("sheet_url")
    if args.caddy_gid is None:
        missing.append("caddy_gid")
    if not args.mikrotik_host:
        missing.append("mikrotik_host")
    if not args.mikrotik_user:
        missing.append("mikrotik_user")

    if missing:
        print("Error: missing required value(s): " + ", ".join(missing), file=sys.stderr)
        print(f"Config file used: {config_path}", file=sys.stderr)
        return 2

    sheet_url = str(args.sheet_url)
    services_gid = int(args.caddy_gid)

    # Determine Caddy IPs from CLI or config.
    cli_caddy_ips: list[str] = []
    for item in (args.caddy_ip or []):
        cli_caddy_ips.extend(_split_csv_list(str(item)))
    cli_caddy_ips = [ip for ip in cli_caddy_ips if normalize_ip(ip)]

    config = load_toml_or_exit(config_path)
    globals_cfg = get_table(config, "globals")
    if is_unified_mikrotik_config(config):
        fw_cfg = get_table(config, "mikrotik_firewall")
    else:
        fw_cfg = get_table(config, "firewall")

    cfg_caddy_ips: list[str] = []
    raw = fw_cfg.get("caddy_ips", fw_cfg.get("caddy_ip", globals_cfg.get("caddy_ip", "")))
    if isinstance(raw, list):
        cfg_caddy_ips = [str(x).strip() for x in raw if str(x).strip()]
    elif isinstance(raw, str):
        cfg_caddy_ips = _split_csv_list(raw)
    cfg_caddy_ips = [ip for ip in cfg_caddy_ips if normalize_ip(ip)]

    caddy_ips = cli_caddy_ips or cfg_caddy_ips
    if not caddy_ips:
        print(
            "Error: caddy IP is required (set [globals].caddy_ip / firewall.caddy_ips or pass --caddy-ip)",
            file=sys.stderr,
        )
        return 2

    logger.debug("mikrotik-firewall: caddy_ips=%s", caddy_ips)

    services_url = build_sheet_url(sheet_url, services_gid)
    if args.debug:
        logger.debug("mikrotik-firewall: loading Services sheet CSV: %s", services_url)

    try:
        services_df = pd.read_csv(services_url)
    except Exception as exc:
        print(f"Error: failed to read Services sheet CSV: {exc}", file=sys.stderr)
        return 1

    services_df = df_with_normalized_columns(services_df)

    nodes_lookup: dict[str, str] | None = None
    if args.nodes_gid is not None:
        nodes_url = build_sheet_url(sheet_url, int(args.nodes_gid))
        logger.debug("mikrotik-firewall: loading Nodes sheet CSV: %s", nodes_url)
        try:
            nodes_df = pd.read_csv(nodes_url)
            nodes_lookup = load_nodes_lookup(nodes_df)
        except Exception as exc:
            print(f"Error: failed to read Nodes sheet CSV: {exc}", file=sys.stderr)
            return 1

    address_entries, nat_rules, wan_filter_rules, caddy_filter_rules, all_filter_rules = _collect_desired_state(
        services_df=services_df,
        nodes_lookup=nodes_lookup,
        caddy_default_backend_port=int(args.caddy_default_backend_port),
        caddy_ips=caddy_ips,
        dmz_interface=str(args.dmz_interface),
        homelab_interface=str(args.homelab_interface),
        debug=bool(args.debug),
    )

    output_path: Path = resolve_path_relative_to_config(config_path, args.output)
    logger.debug(
        "mikrotik-firewall: generated address_entries=%d nat_rules=%d filter_rules=%d output=%s",
        len(address_entries),
        len(nat_rules),
        len(all_filter_rules),
        output_path,
    )
    _generate_rsc(
        address_entries=address_entries,
        nat_rules=nat_rules,
        filter_rules=all_filter_rules,
        output_path=output_path,
        stdout=bool(args.stdout),
    )

    if not args.apply:
        # Dry-run summary for apply.
        target = f"{str(args.mikrotik_user)}@{str(args.mikrotik_host)}"
        commands = _build_apply_commands(
            address_entries=address_entries,
            nat_rules=nat_rules,
            wan_filter_rules=wan_filter_rules,
            caddy_filter_rules=caddy_filter_rules,
        )
        print("Dry run (no --apply): no remote changes made")
        if bool(args.stdout):
            print("- generated: stdout")
        else:
            print(f"- generated: {output_path}")
            print(f"- hint: can be imported manually via /import file-name={output_path.name}")

        print(f"- would ssh: {target} apply {len(commands)} RouterOS command(s)")
        if not bool(args.yes):
            print("- would prompt: confirmation (use --yes to skip)")
        print("Re-run with --apply to perform these actions.")
        return 0

    # Apply over SSH
    require_command("ssh")
    password_env = str(args.mikrotik_password_env or "").strip() or None
    run_env = sshpass_env_from_password_env(password_env=password_env)
    use_sshpass = run_env is not None
    if use_sshpass:
        require_command("sshpass")

    identity_file: Path | None = (
        resolve_path_relative_to_config(config_path, args.ssh_identity_file)
        if args.ssh_identity_file is not None
        else None
    )
    if identity_file is not None and not identity_file.exists():
        print(f"Error: SSH identity file not found: {identity_file}", file=sys.stderr)
        return 2

    target = f"{str(args.mikrotik_user)}@{str(args.mikrotik_host)}"
    control_path = ssh_control_path(
        prefix="mikrotik",
        username=str(args.mikrotik_user),
        host=str(args.mikrotik_host),
        port=int(args.ssh_port),
    )
    ssh_args = prefix_sshpass(
        ssh_base_args(control_path=control_path, port=int(args.ssh_port), identity_file=identity_file),
        enabled=use_sshpass,
    )

    commands = _build_apply_commands(
        address_entries=address_entries,
        nat_rules=nat_rules,
        wan_filter_rules=wan_filter_rules,
        caddy_filter_rules=caddy_filter_rules,
    )

    if not args.yes:
        _confirm_apply(command_count=len(commands))

    joined = "; ".join(commands)
    logger.debug("mikrotik-firewall: applying %d commands", len(commands))

    try:
        ssh_start_master(ssh_args=ssh_args, target=target, env=run_env)
        ssh_run(ssh_args=ssh_args, target=target, command=joined, check=True, env=run_env)
    finally:
        ssh_stop_master(ssh_args=ssh_args, target=target, env=run_env)

    print(f"Applied firewall changes to router ({len(commands)} commands)")
    return 0
