- name: Update CA trust
  ansible.builtin.command: update-ca-certificates
  changed_when: true

- name: Run pam-auth-update
  ansible.builtin.command: pam-auth-update --package
  changed_when: false

- name: Restart kanidm-unixd
  ansible.builtin.systemd:
    name: kanidm-unixd
    state: restarted

- name: Restart kanidm-unixd-tasks
  ansible.builtin.systemd:
    name: kanidm-unixd-tasks
    state: restarted

- name: Restart ssh
  ansible.builtin.systemd:
    name: ssh
    state: restarted
