base_url = "https://192.168.10.30"
work_dir = "./downloads"

netbox_zone_filters = [
	{ zone = "moyer.wtf", views = ["external"] },
	{ zone = "thomasmoyer.org", views = ["external"] },
]

caddy_zones = [
	{ zone = "moyer.wtf", wildcard = true, redirect_www = false },
	{ zone = "thomasmoyer.org", wildcard = true, redirect_www = true },
]

[caddy_deploy]
host = "192.168.20.3"
username = "root"
path = "/opt/proxy/Caddyfile"
restart_command = "cd /opt/proxy && docker compose restart"
port = 22

