services:
  taskchampion:
    image: ghcr.io/gothenburgbitfactory/taskchampion-sync-server:0.7.1
    restart: unless-stopped
    environment:
      - RUST_LOG=info
      - DATA_DIR=/var/lib/taskchampion-sync-server/data
      - LISTEN=0.0.0.0:8080
      - CLIENT_ID=${TASKCHAMPION_SYNC_SERVER_CLIENT_ID}
    volumes:
      - taskchampion_data:/var/lib/taskchampion-sync-server/data

  timew-sync:
    image: timew-sync-server:local
    build: https://github.com/timewarrior-synchronize/timew-sync-server.git
    restart: unless-stopped
    command:
      - start
      - --port
      - "8080"
      - --keys-location
      - /data/authorized_keys
      - --sqlite-db
      - /data/db.sqlite
    volumes:
      - timew_sync_data:/data

volumes:
  taskchampion_data:
  timew_sync_data: