services:
  web:
    image: gitea.priv.moyer.wtf/tmoyer/www:latest
    ports:
      - "8080:8080"
    healthcheck:
      test:
        - CMD-SHELL
        - wget --no-verbose --tries=1 --spider http://127.0.0.1:8080/ || exit 1
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: unless-stopped