# generated by python -m homelab mikrotik
# generated_at=2026-03-23T18:10:31Z
# service=Proxmox VIP
# address-list convention:
#   caddy hosts: hlb-caddy-hosts
#   backend groups: hlb-backend-<protocol>-<backend_port>
# onboarding guidance:
#   add/maintain caddy nodes:
#     /ip firewall address-list add list=hlb-caddy-hosts address=<CADDY_IP> comment="manual caddy node"
#   add/maintain backend services:
#     /ip firewall address-list add list=hlb-backend-<protocol>-<backend_port> address=<SERVICE_IP> comment="manual backend service"

/ip firewall address-list add list=hlb-caddy-hosts address=192.168.20.2 comment="generated by python -m homelab mikrotik; single-service address-list; caddy-hosts; Proxmox VIP"
/ip firewall address-list add list=hlb-backend-tcp-8006 address=192.168.10.15 comment="generated by python -m homelab mikrotik; single-service address-list; backend-group; tcp:8006; Proxmox VIP"
/ip firewall nat add chain=dstnat action=dst-nat in-interface-list=WAN protocol=tcp dst-port=443 to-addresses=192.168.20.2 to-ports=8006 comment="generated by python -m homelab mikrotik; single-service nat; Proxmox VIP; tcp:443->192.168.20.2:8006"
/ip firewall filter add chain=forward action=accept protocol=tcp dst-port=8006 dst-address-list=hlb-backend-tcp-8006 src-address-list=hlb-caddy-hosts comment="generated by python -m homelab mikrotik; single-service filter; Proxmox VIP; tcp:8006->192.168.10.15"
