# generated by python -m homelab mikrotik
# generated_at=2026-03-19T22:30:50Z
# service=Pterodactyl Panel
# address-list convention:
#   caddy hosts: hlb-caddy-hosts
#   backend groups: hlb-backend-<protocol>-<backend_port>
# onboarding guidance:
#   add/maintain caddy nodes:
#     /ip firewall address-list add list=hlb-caddy-hosts address=<CADDY_IP> comment="manual caddy node"
#   add/maintain backend services:
#     /ip firewall address-list add list=hlb-backend-<protocol>-<backend_port> address=<SERVICE_IP> comment="manual backend service"

/ip firewall address-list add list=hlb-caddy-hosts address=192.168.20.2 comment="generated by python -m homelab mikrotik; single-service address-list; caddy-hosts; Pterodactyl Panel"
/ip firewall address-list add list=hlb-backend-tcp-80 address=192.168.20.2 comment="generated by python -m homelab mikrotik; single-service address-list; backend-group; tcp:80; Pterodactyl Panel"
/ip firewall nat add chain=dstnat action=dst-nat in-interface-list=WAN protocol=tcp dst-port=443 to-addresses=192.168.20.2 to-ports=80 comment="generated by python -m homelab mikrotik; single-service nat; Pterodactyl Panel; tcp:443->192.168.20.2:80"
/ip firewall filter add chain=forward action=accept protocol=tcp dst-port=80 dst-address-list=hlb-backend-tcp-80 src-address-list=hlb-caddy-hosts comment="generated by python -m homelab mikrotik; single-service filter; Pterodactyl Panel; tcp:80->192.168.20.2"
/ip dhcp-server lease add mac-address=BC:24:11:31:7D:EA address=192.168.30.2 comment="generated by python -m homelab mikrotik; single-service dhcp; Pterodactyl Panel"
