#!/usr/bin/env python3
"""
apply_mikrotik_dns.py

Applies internal DNS records (provider=mikrotik) as Mikrotik static DNS entries.

It generates and imports (via /import) a .rsc script that:
  - removes previously-generated records (by comment)
  - adds new /ip dns static entries

Router endpoint resolution:
  - Prefer --router-host/--router-user/--router-port (CLI)
  - Else dns-config.toml router_host/router_user/router_port
  - Else per-VLAN servers entries where type=mikrotik (vlans.yaml or toml)

Dry-run writes scripts under ./dry-run/
"""

from __future__ import annotations

import argparse
import datetime
import os
from typing import Any, Dict, List

from netops_lib import (
    check_prerequisites,
    deploy_mikrotik_script,
    iter_internal_dns_records,
    load_config_toml,
    load_sot,
    prompt_password_once,
    resolve_vlan_server,
)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--data-dir", default="data")
    ap.add_argument("--config", default="dns-config.toml")
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--keep", action="store_true")
    ap.add_argument("--vlan", action="append", help="Limit to VLAN(s). Can be repeated.")
    ap.add_argument("--router-host")
    ap.add_argument("--router-user")
    ap.add_argument("--router-port")
    ap.add_argument("--router-password")
    args = ap.parse_args()

    if not check_prerequisites(needs_dnscontrol=False):
        return 1

    sot = load_sot(args.data_dir)
    cfg, _ = load_config_toml(args.config)

    vlan_filter = {v.lower() for v in args.vlan} if args.vlan else None

    grouped: Dict[str, List[Dict[str, Any]]] = {}
    for r in iter_internal_dns_records(sot, vlans_doc=sot.get("vlans_doc")):
        if r["provider"] != "mikrotik":
            continue
        vlan_id = r["vlan_id"].lower()
        if vlan_filter and vlan_id not in vlan_filter:
            continue
        grouped.setdefault(vlan_id, []).append(r)

    if not grouped:
        print("No Mikrotik DNS records to apply.")
        return 0

    # Global router defaults
    router_host = args.router_host or cfg.get("router_host")
    router_user = args.router_user or cfg.get("router_user") or "admin"
    router_port = str(args.router_port or cfg.get("router_port", 22))
    password = args.router_password or cfg.get("router_password")

    if args.dry_run:
        os.makedirs("dry-run", exist_ok=True)

    for vlan_id, entries in grouped.items():
        # If no global router host, try vlan-scoped mikrotik host
        if not router_host:
            sc = resolve_vlan_server(vlan_id, want_type="mikrotik", vlans_doc=sot.get("vlans_doc"), config=cfg)
            router_host = sc.get("host")
            router_user = sc.get("user") or router_user
            router_port = str(sc.get("port") or router_port)

        if not router_host:
            print(f"[Warning] VLAN {vlan_id}: no Mikrotik host configured. Skipping.")
            continue

        who = f"{router_user}@{router_host}"
        password = prompt_password_once(password, who=who, dry_run=args.dry_run)

        script_comment = f"Generated by netops (DNS: {vlan_id})"
        filename = f"mikrotik-{vlan_id}-dns.rsc"
        if args.dry_run:
            filename = os.path.join("dry-run", filename)

        lines = [
            f"# Generated on {datetime.datetime.now()}",
            f':put "Starting DNS update for VLAN: {vlan_id}"',
            f'/ip dns static remove [find comment="{script_comment}"]',
            ':put "Updating DNS entries..."',
        ]

        seen = set()
        for e in entries:
            fqdn = e["fqdn"]
            rtype = str(e.get("record_type") or "A").upper()
            val = e["value"]

            key = (fqdn, rtype, val)
            if key in seen:
                continue
            seen.add(key)

            if rtype == "CNAME":
                # RouterOS: type=CNAME + cname=<target> :contentReference[oaicite:2]{index=2}
                lines.append(
                    f'/ip dns static add name="{fqdn}" type=CNAME cname="{val}" comment="{script_comment}"'
                )
            else:
                lines.append(
                    f'/ip dns static add name="{fqdn}" type=A address="{val}" comment="{script_comment}"'
                )


        print(f"Updating Mikrotik DNS for VLAN {vlan_id} on {router_host}...")
        deploy_mikrotik_script(
            filename,
            lines,
            host=router_host,
            user=router_user,
            port=router_port,
            password=password,
            dry_run=args.dry_run,
            keep_files=args.keep,
        )

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
