#!/usr/bin/env python3
"""
update_caddyfile_map.py

Updates Caddyfile map {host} {backend} entries from YAML SoT:
  - For dns_names.kind == "access" referencing a service
  - Where that service routes via Caddy (service.routing.internal_dns_target == caddy_ip)
  - Backend is service backend ip + (service backend port or first service port)

Writes:
  - dry-run/Caddyfile (if --dry-run)
  - or edits Caddyfile in place
"""

from __future__ import annotations

import argparse
import os
import sys
from typing import Dict, List

from netops_lib import (
    load_config_toml,
    load_sot,
    service_backend_ip,
    service_backend_port,
    update_caddyfile_map,
)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--data-dir", default="data")
    ap.add_argument("--config", default="dns-config.toml")
    ap.add_argument("--caddy-ip", help="Reverse proxy IP (fallback vlans.yaml globals.caddy_ip then config caddy_ip)")
    ap.add_argument("--caddyfile", default="Caddyfile")
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    sot = load_sot(args.data_dir)
    cfg, _ = load_config_toml(args.config)

    caddy_ip = args.caddy_ip
    if not caddy_ip:
        vl = sot.get("vlans_doc") or {}
        globals_ = (vl.get("globals") or {}) if isinstance(vl, dict) else {}
        caddy_ip = globals_.get("caddy_ip") or cfg.get("caddy_ip")

    if not caddy_ip:
        print("[Error] caddy_ip not provided (use --caddy-ip, or set in vlans.yaml globals.caddy_ip, or config).")
        return 2

    caddyfile_path = os.path.abspath(args.caddyfile)
    if not os.path.isfile(caddyfile_path):
        print(f"[Error] Caddyfile not found at {caddyfile_path}", file=sys.stderr)
        return 2

    assets_by_id = sot["assets_by_id"]
    services_by_id = sot["services_by_id"]

    records: List[Dict[str, str]] = []
    for dn in sot["dns_names"]:
        if not isinstance(dn, dict):
            continue
        if str(dn.get("kind") or "").lower() != "access":
            continue
        targets = dn.get("targets") or {}
        if not isinstance(targets, dict) or not targets.get("service_id"):
            continue
        service = services_by_id.get(str(targets["service_id"]))
        if not service:
            continue
        routing = service.get("routing") or {}
        if not isinstance(routing, dict):
            continue
        if str(routing.get("internal_dns_target") or "").strip() != str(caddy_ip).strip():
            continue

        backend_ip = service_backend_ip(service, assets_by_id)
        if not backend_ip:
            continue

        port = service_backend_port(service)
        backend = f"{backend_ip}:{port}" if port else backend_ip
        records.append({"host": str(dn.get("fqdn")), "backend": backend})

    if not records:
        print("No Caddy map records to apply.")
        return 0

    with open(caddyfile_path, "r", encoding="utf-8") as f:
        content = f.read()

    new_content = update_caddyfile_map(content, records, generator_tag="Generated by update_caddyfile_map.py")

    if args.dry_run:
        os.makedirs("dry-run", exist_ok=True)
        out_path = os.path.join("dry-run", "Caddyfile")
        with open(out_path, "w", encoding="utf-8") as f:
            f.write(new_content)
        print(f"[Dry Run] Wrote: {out_path}")
        return 0

    with open(caddyfile_path, "w", encoding="utf-8") as f:
        f.write(new_content)
    print(f"Updated Caddyfile: {caddyfile_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
