version: v1alpha1
debug: false
persist: true
machine:
    type: controlplane
    token: 928abn.lm8wyj069i53vhkf
    ca:
        crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJQakNCOGFBREFnRUNBaEJJSkdXckJRcEovUkZnd2krTTFtVnZNQVVHQXl0bGNEQVFNUTR3REFZRFZRUUsKRXdWMFlXeHZjekFlRncweU5qQTJNRGd4T0RFeU1ESmFGdzB6TmpBMk1EVXhPREV5TURKYU1CQXhEakFNQmdOVgpCQW9UQlhSaGJHOXpNQ293QlFZREsyVndBeUVBbTFzS0J0RmRVbVZHM0kwQ2RKT3UvTllSMDVQSkJtRDZPc0Z5CkNKS2ZNcytqWVRCZk1BNEdBMVVkRHdFQi93UUVBd0lDaERBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUkKS3dZQkJRVUhBd0l3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFkQmdOVkhRNEVGZ1FVdDNzTGFZYkc1Y1d4T0JpUwp0T3hIMHFHWWc2VXdCUVlESzJWd0EwRUE5cGlabEdHeTdoRmU2QTltOEFlemgrZEsxQUI3UUhvOG1kanNPMzN3CnFlMFNFWnpKVkJBTGVUOXMvTzNCUUxudHhabVFZVThtZkRocDFOTklGVkloRFE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
        key: LS0tLS1CRUdJTiBFRDI1NTE5IFBSSVZBVEUgS0VZLS0tLS0KTUM0Q0FRQXdCUVlESzJWd0JDSUVJTmlkbzZING42LzNGVDJvM2duNElMajgyY05QdHRXUWVxVG9ybE9EVmJRNwotLS0tLUVORCBFRDI1NTE5IFBSSVZBVEUgS0VZLS0tLS0K
    certSANs:
        - 192.168.30.3
        - talos-vm-0.homelab.moyer.wtf
        - talos-vm-0.moyer.wtf
        - talos.moyer.wtf
        - talos.homelab.moyer.wtf
        - 192.168.30.21
    kubelet:
        image: ghcr.io/siderolabs/kubelet:v1.36.1
        defaultRuntimeSeccompProfileEnabled: true
        disableManifestsDirectory: true
    network:
        hostname: talos-vm-0
    install:
        disk: /dev/sda
        image: ghcr.io/siderolabs/installer:v1.13.3
        wipe: false
        grubUseUKICmdline: true
    features:
        diskQuotaSupport: true
        kubePrism:
            enabled: true
            port: 7445
        hostDNS:
            enabled: true
            forwardKubeDNSToHost: true
    nodeLabels:
        node.kubernetes.io/exclude-from-external-load-balancers: ""
cluster:
    id: PIJEky5A3MB74iDbMjeFnkmU1MeoKzhgnu6_4QgYLdw=
    secret: XlXUMS2+v0OdaKsoU5ZlDwqOn0H88AZiodOtke2eBYQ=
    controlPlane:
        endpoint: https://192.168.30.3:6443
    clusterName: homelab
    network:
        dnsDomain: cluster.local
        podSubnets:
            - 10.244.0.0/16
        serviceSubnets:
            - 10.96.0.0/12
    token: c262r9.u6iekak1c5dctxc6
    secretboxEncryptionSecret: RK+GRJFDzdLPxRkPdMFUk0Se/1Fg+AG28bqobbMH3ZI=
    ca:
        crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJpRENDQVMrZ0F3SUJBZ0lRWjRiRTV3bnNRQStwSEt4aCtxbUg2ekFLQmdncWhrak9QUVFEQWpBVk1STXcKRVFZRFZRUUtFd3ByZFdKbGNtNWxkR1Z6TUI0WERUSTJNRFl3T0RFNE1USXdNbG9YRFRNMk1EWXdOVEU0TVRJdwpNbG93RlRFVE1CRUdBMVVFQ2hNS2EzVmlaWEp1WlhSbGN6QlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VICkEwSUFCS214MlRFMjlJUXBsMDN5R1hONWo3Ri9KYlMzcExhUlNCSjMwYUQ4VmFsb2dnV0xrR0hsS3ZnRFgxTGUKcWRIODNzV1hFelRSblcva1dwRkIzejdwMlRhallUQmZNQTRHQTFVZER3RUIvd1FFQXdJQ2hEQWRCZ05WSFNVRQpGakFVQmdnckJnRUZCUWNEQVFZSUt3WUJCUVVIQXdJd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFCkZnUVV6MWhIb2J0RVhmUTFKWlpZN1pTNUliYTZqNlF3Q2dZSUtvWkl6ajBFQXdJRFJ3QXdSQUlnUG12RmJodVcKd2lIVGtGNURKMVVHMW9ZMzZJU01ualhVTVlZblEzM2VNU1lDSUZTNXdmemtYVXVhaS8wUGZ6TktZREdLM2s0Tgo2RnB4Lzg0L3NmUjNacjNGCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
        key: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUpFWFI4VzJJMzFBY0QrOWdzUGdHYW15WW5LYVBaS2JuVTQ0ekpvQWlCRXpvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFcWJIWk1UYjBoQ21YVGZJWmMzbVBzWDhsdExla3RwRklFbmZSb1B4VnFXaUNCWXVRWWVVcQorQU5mVXQ2cDBmemV4WmNUTk5HZGIrUmFrVUhmUHVuWk5nPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
    aggregatorCA:
        crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJZRENDQVFXZ0F3SUJBZ0lRVWlZejlKa3RPdDdqS2puSHlhM3VZakFLQmdncWhrak9QUVFEQWpBQU1CNFgKRFRJMk1EWXdPREU0TVRJd01sb1hEVE0yTURZd05URTRNVEl3TWxvd0FEQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxRwpTTTQ5QXdFSEEwSUFCQ3p0MzQ4M3ZUSTZEcDJhbE5td0NiL2dOTlF3MnlxZ3lnbHR0djlNNTNEMGwzYVlyV21pCjhJS3czV0dFRlFGN0p6ZHhZMnFINkd1VFQ5WnJXVHdoL3E2allUQmZNQTRHQTFVZER3RUIvd1FFQXdJQ2hEQWQKQmdOVkhTVUVGakFVQmdnckJnRUZCUWNEQVFZSUt3WUJCUVVIQXdJd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZApCZ05WSFE0RUZnUVV3cExZbWZhTmdHWE9WN0RDZHhUbG85dDRzTmd3Q2dZSUtvWkl6ajBFQXdJRFNRQXdSZ0loCkFOdFlDU1pmMUsrMDBmWlhJWmNSSUlzVzdxd3I2MkN4K2xkZk8wM041eldBQWlFQXJ0SzBjTGJJY3A4dm9wUEoKVDlnaWk4NnF3Q3FyTzlVSVBJK3IrTWV1TWdjPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
        key: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSU1BOG5GemlaZVh1Vmpta1RhSnlIdXNuY0NCV3psRU1iTS83Z0hkaWpROWJvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFTE8zZmp6ZTlNam9PblpxVTJiQUp2K0EwMUREYktxREtDVzIyLzB6bmNQU1hkcGl0YWFMdwpnckRkWVlRVkFYc25OM0ZqYW9mb2E1TlAxbXRaUENIK3JnPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
    serviceAccount:
        key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlKS0FJQkFBS0NBZ0VBekhLTGZ3OG1XbjgrcjFIMjlzQ1V1VXVDK3l4bW9ycFhVRzJMaXVTZHRpdE05WVZHCko0SDJLY2lJM3ZBOVRtenF2VHNadzZPWXZXU2ovbTloWFdVLzVxS0Z4UE4yMysySlJuQU4vR1BmTEg3Q1QzaEYKYXpSU3p4d3NwTGxRU052Wm5RWjZQRnIzSVZ4UXMvdlUvVnZFZTgyNGt0dEh2amRoZUR6TTN3OHczdE5MaDJvNwpGQ0V6My9PNkVlbnlvZDNpLzQwNnQ2bG9ZcFViM0hXUVRVQU43L0M2WWFOY2ZTcENjdXpNc0JhR3JqU0JLcTVSClFnWEFkaVc4N2xld2QrMlNEVWhxUUtmRzd4Z2ZzdSt0TU1mV1NGYVNUZDJ2Tk9UT2prVjAxTGdSVUhCY1B3Ni8KOEpLNWVYZFFnU2ZNcTR3TGRKTHRxcUlDMk1QMFhKTUFNTnhHRUFhTjJqN0RQMTVPQTFkaHZtakxyNWlGOGpyUgpJSW92b0ltU3V5TzY1UXRIc0kyTzIzOXJTRDgxOUNnUVJGTmEvenV2ZVFvdnBqMDJKcE5jaFR2VFpMT2ZJMHFjCkxyd2JXSGtRd0JSWnBFUFllNXkwM1YwMmNVWVZpU2xXWEtsN2NWeitUb2dyNFNKNUhlT0FKa0tGcFljRWpLUnIKV2MxNFdrNHpTbDNQQjJYNXY4UEIrSk5wRHAyeWQ3U0JiVTFvNFh6S3h4MVdzZVNYQ1E4NStCWlp1eGFqdGQvSApETFFkTHQ5VTNWUm5hWnFCL3hRR2JkMk9YYUY1bFBCYWxrRzY2aitVSzZidU5CUXNwQnl4MEdnM1dwU0V0cHNZClJLNTFpcU9IZDdRdlcyNmgvcU1zYVBJMVZKV1R2dE5mUVFaUDZiRVJ3YmFLVXBRZ0VDNDdoMG1MNkkwQ0F3RUEKQVFLQ0FnQk1hTVQ4N0Q4VDFIbXJrWkVnNEpIVS9NVkx0V2o0aVhjbmpvRjRIQUJiZkt4ckdHL0RSVDJvbVJPYQphcVFuQXVycVpVTzRUQlRDTi9KWW5lMEFPRjZkQm9IRFBaRGdtUWpVby8xK0poOWJKRmJmMTUzdU5xUjZWbGZUCkNwVllYWjVqb3UrZFRnd04wbEF4TEQ0S29MajY0a1NJMGw1cVY0MWNvRENiYnpSL0d1NGdBcEpvOEEzUXRla0YKVisvQUVrc0w0bzhlNURnb20vekpOTUVGTmhyZllaTnUrVnlRUlBLSHZEdTExZjFvN3lPVlBZZ09DbE5IZE13NwpNZGU0d3JmeXNlMVFFOFIwU0lwVVdHSmNtRnRjTnNyQVFrbUFsY0VqQ0E5bGp4T2RnaGpmMGxYbkJoYytyOXFOCklzQktIdkdMRkh5eDZKSHl6SzJ2eVpycEovSWcwT1pNWlU2WFplc3BOeEJFdFZlRFpFQWQzUUoyZTJZZ0wxMnkKTzFCa0FTWHUvWlhXamtoRm9SYlV1R0VGQjR4eHZWdW9JNVFYQ25UcjgxRjg0TEw2WHM4TEV6Kzl1aU9VTzNiWQpBUnRJd0E3Y21id0YyZ2dLai9aMkZxSjNIWW1mSHJ3MXJ6ZXB6aDJNcXk2RXJVNFpuU2ZOY0M5UFNZanBES05SClpzbEpINVhGTExGMUE0NkRUaXp3MDFDc0NuUkU0bnlkVnlUdnJqSFhRSDJMWU5WN1NNSlpZak90Vy9meFlxT0cKRmthemRQQ3Z5MWkwTys0bG5ERUh4Rnd0djJrbUtqd2Npd05rL2hMZmQwK1RUZ0kwWWJMZFp5d3BBeWR3Wm42bQpHRmF5WFhKaEZrQ2FqRlVFdmVobU53TWJVdXR6NXNrSTROYVJHNXRHcmJqQysyWThld0tDQVFFQTJJVEZpQU8zCmY0alNPdUFLY1BySjVhdGJ2VUdGM2JpYXE5WFF5OHBXU3dFcVlMSmZTb0tuRVdOQU42M0hTbXh1aGdyOXFpTHEKVHllR09sQ0R1TWVobjI4cFAwbm5ERDRFaFowZGRpdVNua3NGMGJONXQ3Ri9wRFNUcHFMT1FTRXk2dDJzbDlFdAovcGx5WjI4Y2lIN1BpQkJwYzF3Q2ttZlJYYkJieXVSaFl6SFR0MFRzWE9jMWZMTFgrYll6UU9OTVoydWcvR2lJCjlMVnZQcUJzb08vbFhNT0dEVngwekFLQUdZSzZOd0ZKbHR1UjZtayt5Z2c5NzNadS9OY3ZJazh5eWlmWkZnUDAKVXd2K2swSnhsc3NZdWFQNGYxYzZyYld6eDRPL3BZaXlYZ2FTaGZNUFN3NEVJSDFCR0NhRk5iM0NxZ3lDMmkybgozRUFmWXNCdVZlYlAvd0tDQVFFQThicElOV01QMjV1bVkxdjRKaDF0Z3QxVE5Md21UNEF0Z243U0RiUnZrViszCmRINkFaWVdJUU1YQ3FIbGlTY092RnZHMXdFRjNtSXFSeG96eElIZHVGbUlZRndkL2ZDSzVRN3h0UWNubW5QM04KNm5yR1pqMkQvNmJRdllOSmw5L0l5V1ZxbVAxY014VWdxdElOVHVpMXA5QWtBY3RrNmVlWU10UkhDcXBrWFdDNgpyTko3djZlalRqM1pNNEJNdFk0RXcxU2xrR3ZtekFhN014SzJtdEVFd0ZBSGpsZnVYMXNHZFBUakN0N0VaelpGCmZNTlBvSGptNUV0UmFuM0xXVkJwSDc5S2RaMmZPSlpWTys5VEl5a2tlSXpySWxrMFJ1aEN5UENIVTNrR28wNHMKVGdsMUJ0bGY4cGlqNnZEaWdjQllpTzVrSGcxRDljVnhRempUZE5PSGN3S0NBUUFQdjhDYWZ5SzJ6UjMxbUZ4SwpFWVBrQjgzWmUwMmdiaEFhRmFobFdtZGlkMGc4MWx5bUQ5RFZLL0g4MnRBWE1zSHJVQnRaWjhiQlVTK3JTRFg4Cmw5REN4eFFwL1Zjb0JjN1FaVGhDWXpMNy9wc0N3TnBHcVV1T2h5Q0NTMjlUUDNYenJZSWpYTnpLbXlDK00wL1IKQWVCWWxsRUZTaGtKeXpGb2JpNlBHSU9ZOG9QaTNjbVBqR1hRbHpXc2ZUdEhLZ0ZodUd0eVVLdzltSURwL2tOSQpoWXFhYjhKdGNGOHlnN0FMcXYyZWlLSndyYkgwYWdsZUtyRk9uTCsvOW1zQVJPQjk0ZDRoZ3RJZnhFeVZLNDBWCm1kcEhqb3pCdm5lUE1SdE5sT0M0eXJPbXNUV3hOcGZUTHNiUUVpeE05R2hXRzJKd2VnNStqam1haExPRHZGbUsKT0FyREFvSUJBUUNWNXFBYXcwaTFOZXZUMTllbHcwQURGRDhpQjc5Mk01V0ZSQ0g4cjdVMElIaEN2S1BnMFJMeQpuL0NieTFKaFRnRkpLREUrZlJxdU5OZzdtWEY2WWJXYUdkQzRqMFRHZFQ0UVBFeEFyUFRlekNHaTArb3V3dDBWCmI1d291YjZzZVBFcHUwT0VoakZqMkNrKzVTMnRqbkFBRmZvT1J0UlluTzdzTG1tenVvQ3N5MnhYK2RzVnVkNXkKaWJZazB0NC9CRWY5M1lNaWNWZFpsSjhJQ0FYSE1mRlJWUStxZk9yc3BTVDI2Rm5YaHRlaTdhdmZ0N3FzVisxUApDMG44ME8rR2ZuQUNhUHpDdlRGY3hSVXNLcmlTcUZQZWtmektleWtKQThWT21LSkM2RjF1YmU3Wm9kRzVvcGwyCmRxUEg4UU4xMVJMU0w0dFVlNE4yYUs5Wk1XY29Ibmp6QW9JQkFCbm14a3JqaExGMnZMZVB0ZnUwc0dQVS9HRmUKS3Qvd2pRM3BKME5OL2RqOHBINVRheU1xZEpiMlFVODlDY0hLUFNCWElNUVRLWXZtVjNJaTk3eGFnRHBKMmZIUgpnNThJZmY0d1paZjQvRERpYkhncGU2QU0wV2JCQ3YxaUNxZjZJeEkwQTZRdXFHbkVVeU5mcHhiTjQyMEZOSldTCjYxL1FYQzZVQnRFVG40dUFwcTZKMnJWdWNyVW1CYlhGWjJkK09EZ2t4UXRBaXJVVzlOWnFGMEo2dW9MRk1YV0YKdWxVNUdOd3lxNTVPakQ4aVVIYXhnem0ySlJ5c240eEpPMTRiZDF2OTJxV0pmUWdNKzBmdm5wbzJ2dWhQeFJpUgpMaUduU3RBODhlejd1WlN3WDR0MER2a3EvL25Wczd5YXhON2NnWlk1SGFPNWNEWjNFRy9BUldwRGtnTT0KLS0tLS1FTkQgUlNBIFBSSVZBVEUgS0VZLS0tLS0K
    allowSchedulingOnControlPlanes: true
    apiServer:
        image: registry.k8s.io/kube-apiserver:v1.36.1
        admissionControl:
            - name: PodSecurity
              configuration:
                apiVersion: pod-security.admission.config.k8s.io/v1alpha1
                defaults:
                    audit: restricted
                    audit-version: latest
                    enforce: baseline
                    enforce-version: latest
                    warn: restricted
                    warn-version: latest
                exemptions:
                    namespaces:
                        - kube-system
                    runtimeClasses: []
                    usernames: []
                kind: PodSecurityConfiguration
        auditPolicy:
            apiVersion: audit.k8s.io/v1
            kind: Policy
            rules:
                - level: Metadata
    controllerManager:
        image: registry.k8s.io/kube-controller-manager:v1.36.1
    proxy:
        image: registry.k8s.io/kube-proxy:v1.36.1
    scheduler:
        image: registry.k8s.io/kube-scheduler:v1.36.1
    discovery:
        enabled: true
        registries:
            kubernetes:
                disabled: true
            service: {}
    etcd:
        ca:
            crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJmakNDQVNTZ0F3SUJBZ0lSQVBRd2IyMnhyaGxOVlk4b2xEaW11MWN3Q2dZSUtvWkl6ajBFQXdJd0R6RU4KTUFzR0ExVUVDaE1FWlhSalpEQWVGdzB5TmpBMk1EZ3hPREV5TURKYUZ3MHpOakEyTURVeE9ERXlNREphTUE4eApEVEFMQmdOVkJBb1RCR1YwWTJRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DQUFUWko1UEZ1VDhSClhFUTNYb2FRaXA0SW1qNnZ6bGw1S2lOY2NhVlZIdHlNcVgzWVM0cUVUaHhNRG5vblEvTmxlRWlraXNHV29zZ2IKam80Z2NHUzBNK2txbzJFd1h6QU9CZ05WSFE4QkFmOEVCQU1DQW9Rd0hRWURWUjBsQkJZd0ZBWUlLd1lCQlFVSApBd0VHQ0NzR0FRVUZCd01DTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3SFFZRFZSME9CQllFRkRtT3ozMVcrako2Ck1IUHZiMWpYb1V0RkRFVGxNQW9HQ0NxR1NNNDlCQU1DQTBnQU1FVUNJRVBIcGtueWJLSW1IYTlBR0UxU0o1RWQKQVVjN244MUo4SzNZcHg1a2FRb2RBaUVBbmlCa3FYZW5ycWxQVUV0TFJ4SzNnaytFZDg0ZFlVb0hYeEx0MXlqOQpCaWM9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
            key: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUtYNzBRdW1KMVJIZlFYVmxWYVM4VWV6d09aak1JdVdQa2NQSTVPdmQ2YlJvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFMlNlVHhiay9FVnhFTjE2R2tJcWVDSm8rcjg1WmVTb2pYSEdsVlI3Y2pLbDkyRXVLaEU0YwpUQTU2SjBQelpYaElwSXJCbHFMSUc0Nk9JSEJrdERQcEtnPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
