from __future__ import annotations

import argparse
import os
from pathlib import Path

from .common import ensure_dir, run_cmd
from .sot import load_sot


def _strip_dot(s: str) -> str:
    return s[:-1] if s.endswith(".") else s


def _zone_for_fqdn(fqdn: str, zones: list[str]) -> str | None:
    fqdn = _strip_dot(fqdn)
    zones_sorted = sorted((_strip_dot(z) for z in zones), key=len, reverse=True)
    for z in zones_sorted:
        if fqdn == z or fqdn.endswith("." + z):
            return z
    return None


def _name_relative(fqdn: str, zone: str) -> str:
    fqdn = _strip_dot(fqdn)
    zone = _strip_dot(zone)
    if fqdn == zone:
        return "@"
    return fqdn[: -(len(zone) + 1)]


def _proxy_meta(proxy_status: str | None) -> str:
    if not proxy_status:
        return "CF_PROXY_OFF"
    ps = proxy_status.strip().lower()
    if ps in ("proxied", "on", "orange", "true"):
        return "CF_PROXY_ON"
    return "CF_PROXY_OFF"  # includes "dns-only"


def generate_dnscontrol_include(*, sot, zones: list[str]) -> str:
    # grouped by zone
    grouped: dict[str, list[str]] = {z: [] for z in zones}

    for dn in sot.dns_names.values():
        if not dn.external.enabled:
            continue
        zone = _zone_for_fqdn(dn.fqdn, zones)
        if not zone:
            continue

        name = _name_relative(dn.fqdn, zone)

        rtype = (dn.external.record_type or "A").upper()
        meta = _proxy_meta(dn.cloudflare.proxy_status if dn.cloudflare else None)

        if rtype == "A":
            ip = None
            # Prefer explicit cloudflare.target_ip if present
            if dn.cloudflare and dn.cloudflare.target_ip:
                ip = dn.cloudflare.target_ip
            elif dn.external.target and dn.external.target == "cloudflare_target_ip":
                # Your schema indicates a per-record cloudflare.target_ip will exist.
                raise ValueError(f"{dn.dns_id}: external.target indicates cloudflare_target_ip but cloudflare.target_ip missing")
            elif dn.external.target:
                ip = dn.external.target
            if not ip:
                raise ValueError(f"{dn.dns_id}: missing external A target IP")
            grouped[zone].append(f'A("{name}", "{ip}", {meta})')

        elif rtype == "CNAME":
            target = dn.external.target
            if not target:
                raise ValueError(f"{dn.dns_id}: missing CNAME target")
            target = _strip_dot(target) + "."
            grouped[zone].append(f'CNAME("{name}", "{target}", {meta})')

        else:
            # extend if you add more record types
            raise ValueError(f"{dn.dns_id}: unsupported external record_type: {rtype}")

    lines: list[str] = []
    lines.append("// Generated by netops_push/update_cloudflare_dnscontrol.py")
    lines.append('var CF_PROXY_OFF = {"cloudflare_proxy": "off"};')
    lines.append('var CF_PROXY_ON  = {"cloudflare_proxy": "on"};')
    lines.append("")
    lines.append("var NETOPS_SOT_RECORDS = {};")
    for z in zones:
        recs = grouped.get(_strip_dot(z), [])
        lines.append(f'NETOPS_SOT_RECORDS["{_strip_dot(z)}"] = [')
        for r in recs:
            lines.append(f"  {r},")
        lines.append("];")
        lines.append("")
    lines.append("// Usage in dnsconfig.js:")
    lines.append('//   require("PATH/TO/netops_sot_records.js");')
    lines.append('//   D("example.com", REG_NONE, DnsProvider(DNS_CLOUDFLARE), NETOPS_SOT_RECORDS["example.com"]);')
    lines.append("")
    return "\n".join(lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description="Generate dnscontrol records from SOT and run dnscontrol (check/preview/push).")
    ap.add_argument("--assets", required=True, type=Path)
    ap.add_argument("--dns-names", required=True, type=Path)
    ap.add_argument("--services", required=True, type=Path)
    ap.add_argument("--vlans", required=True, type=Path)

    ap.add_argument("--cache-dir", default=Path("cache"), type=Path)
    ap.add_argument("--dnscontrol-dir", required=True, type=Path)
    ap.add_argument("--dnscontrol-bin", default="dnscontrol")

    ap.add_argument("--zones", nargs="*", default=None, help="e.g. moyer.wtf thomasmoyer.org (defaults to globals.base_domain)")
    ap.add_argument("--include-path", default=None, help="Override output JS file path; default is cache/dnscontrol/netops_sot_records.js")

    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--check-only", action="store_true")
    ap.add_argument("--no-check", action="store_true")

    args = ap.parse_args()

    sot = load_sot(
        assets_path=args.assets,
        dns_names_path=args.dns_names,
        services_path=args.services,
        vlans_path=args.vlans,
    )

    zones = args.zones if args.zones else ([sot.globals.base_domain] if sot.globals.base_domain else [])
    if not zones:
        raise ValueError("No zones specified and globals.base_domain is empty; use --zones")

    out_path = Path(args.include_path) if args.include_path else (args.cache_dir / "dnscontrol" / "netops_sot_records.js")
    ensure_dir(out_path.parent)

    content = generate_dnscontrol_include(sot=sot, zones=zones)
    out_path.write_text(content, encoding="utf-8")
    print(f"Wrote: {out_path}")

    # Run dnscontrol in dnscontrol-dir, assuming dnsconfig.js already requires this file.
    # If you need the require(), add something like:
    #   require("../cache/dnscontrol/netops_sot_records.js");
    env = os.environ.copy()

    if not args.no_check:
        run_cmd([args.dnscontrol_bin, "check"], cwd=args.dnscontrol_dir, capture=False, check=True)

    if args.check_only:
        return 0

    run_cmd([args.dnscontrol_bin, "preview"], cwd=args.dnscontrol_dir, capture=False, check=True)

    if args.dry_run:
        return 0

    run_cmd([args.dnscontrol_bin, "push"], cwd=args.dnscontrol_dir, capture=False, check=True)
    print("Cloudflare (dnscontrol) updated.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

