---
- name: Fail if target is not Debian family
  ansible.builtin.assert:
    that:
      - ansible_os_family == "Debian"
    fail_msg: "Kanidm client setup supports Debian-based systems only."

- name: Apply kanidm_client role
  ansible.builtin.include_role:
    name: kanidm_client

- name: Swap pam_kanidm and pam_unix auth order in common-auth
  ansible.builtin.replace:
    path: /etc/pam.d/common-auth
    regexp: '^(auth\s+\[success=2 default=ignore\]\s+)pam_unix\.so nullok\n(auth\s+\[success=1 default=ignore\]\s+)pam_kanidm\.so ignore_unknown_user$'
    replace: '\1pam_kanidm.so ignore_unknown_user\n\2pam_unix.so nullok'
