version: "3.9"

services:
  timew-webhook:
    build:
      context: .
      dockerfile: Dockerfile
    image: local/timew-webhook:latest
    env_file: .env
    environment:
      - TOKEN=${TOKEN}
    ports:
      - "${PORT:-9000}:8000"
    user: "${PUID:-0}:${PGID:-0}"
    volumes:
      - "${TIMEW_HOME}/.timewarrior:/var/lib/timew/.timewarrior"
    restart: unless-stopped
